//! Infrastructure layer
//!
//! Generated by backbone-schema. Do not edit manually.
// <<< CUSTOM: Add auth module export
pub mod auth;
// <<< CUSTOM: Add messaging module export
pub mod messaging;
// >>> END CUSTOM

pub mod persistence;