//! State machine for SecurityEvent workflow
//!
//! Generated by metaphor-schema

use serde::{Deserialize, Serialize};
use std::str::FromStr;

/// States for SecurityEvent workflow
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SecurityEventState {
    /// Initial state
    False,
    /// Final state
    True,
}

impl Default for SecurityEventState {
    fn default() -> Self {
        Self::False
    }
}

impl std::fmt::Display for SecurityEventState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::False => write!(f, "false"),
            Self::True => write!(f, "true"),
        }
    }
}

impl FromStr for SecurityEventState {
    type Err = StateMachineError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "false" => Ok(Self::False),
            "true" => Ok(Self::True),
            _ => Err(StateMachineError::InvalidState(s.to_string())),
        }
    }
}

impl SecurityEventState {
    /// Check if this is the initial state
    pub fn is_initial(&self) -> bool {
        matches!(self, Self::False)
    }

    /// Check if this is a final state
    pub fn is_final(&self) -> bool {
        matches!(self, Self::True)
    }

    /// Get all possible states
    pub fn all() -> Vec<Self> {
        vec![
            Self::False,
            Self::True,
        ]
    }
}

/// Transitions for SecurityEvent workflow
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SecurityEventTransition {
    /// false -> true
    Resolve,
    /// false -> true
    AutoResolve,
}

impl std::fmt::Display for SecurityEventTransition {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Resolve => write!(f, "resolve"),
            Self::AutoResolve => write!(f, "auto_resolve"),
        }
    }
}

impl FromStr for SecurityEventTransition {
    type Err = StateMachineError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "resolve" => Ok(Self::Resolve),
            "auto_resolve" => Ok(Self::AutoResolve),
            _ => Err(StateMachineError::InvalidTransition(s.to_string())),
        }
    }
}

impl SecurityEventTransition {
    /// Get the target state of this transition
    pub fn target_state(&self) -> SecurityEventState {
        match self {
            Self::Resolve => SecurityEventState::True,
            Self::AutoResolve => SecurityEventState::True,
        }
    }

    /// Get all transitions
    pub fn all() -> Vec<Self> {
        vec![
            Self::Resolve,
            Self::AutoResolve,
        ]
    }

    /// Get allowed roles for this transition
    pub fn allowed_roles(&self) -> &'static [&'static str] {
        match self {
            Self::Resolve => &["admin", "security_analyst"],
            Self::AutoResolve => &["system"],
        }
    }
}

use super::StateMachineError;

/// State machine for SecurityEvent workflow
#[derive(Debug, Clone)]
pub struct SecurityEventStateMachine {
    current_state: SecurityEventState,
}

impl SecurityEventStateMachine {
    /// Create a new state machine with initial state
    pub fn new() -> Self {
        Self {
            current_state: SecurityEventState::default(),
        }
    }

    /// Create from an existing state
    pub fn from_state(state: SecurityEventState) -> Self {
        Self { current_state: state }
    }

    /// Get the current state
    pub fn current_state(&self) -> SecurityEventState {
        self.current_state
    }

    /// Check if a transition is allowed from the current state
    pub fn can_transition(&self, transition: SecurityEventTransition) -> bool {
        if matches!(self.current_state, SecurityEventState::True) {
            return false;
        }

        match (self.current_state, transition) {
            (SecurityEventState::False, SecurityEventTransition::Resolve) => true,
            (SecurityEventState::False, SecurityEventTransition::AutoResolve) => true,
            _ => false,
        }
    }

    /// Check if a transition is allowed for a given role
    pub fn can_transition_with_role(&self, transition: SecurityEventTransition, role: &str) -> bool {
        if !self.can_transition(transition) {
            return false;
        }

        let allowed_roles = transition.allowed_roles();
        if allowed_roles.is_empty() {
            return true; // No role restriction
        }

        allowed_roles.iter().any(|r| *r == role || *r == "*")
    }

    /// Apply a transition, returning the new state
    pub fn transition(&mut self, transition: SecurityEventTransition) -> Result<SecurityEventState, StateMachineError> {
        if !self.can_transition(transition) {
            return Err(StateMachineError::TransitionNotAllowed {
                transition: transition.to_string(),
                from: self.current_state.to_string(),
            });
        }

        self.current_state = transition.target_state();
        Ok(self.current_state)
    }

    /// Apply a transition with role check
    pub fn transition_with_role(&mut self, transition: SecurityEventTransition, role: &str) -> Result<SecurityEventState, StateMachineError> {
        // Check basic transition validity first
        if !self.can_transition(transition) {
            return Err(StateMachineError::TransitionNotAllowed {
                transition: transition.to_string(),
                from: self.current_state.to_string(),
            });
        }

        // Check role authorization
        if !self.can_transition_with_role(transition, role) {
            return Err(StateMachineError::RoleNotAuthorized {
                role: role.to_string(),
                transition: transition.to_string(),
            });
        }

        self.current_state = transition.target_state();
        Ok(self.current_state)
    }

    /// Get all available transitions from the current state
    pub fn available_transitions(&self) -> Vec<SecurityEventTransition> {
        SecurityEventTransition::all()
            .into_iter()
            .filter(|t| self.can_transition(*t))
            .collect()
    }

    /// Get all available transitions for a given role
    pub fn available_transitions_for_role(&self, role: &str) -> Vec<SecurityEventTransition> {
        SecurityEventTransition::all()
            .into_iter()
            .filter(|t| self.can_transition_with_role(*t, role))
            .collect()
    }

    /// Attempt to transition directly to a target state.
    ///
    /// Finds any transition that leads to the target state and applies it.
    /// Returns Err if no valid transition leads from current state to target.
    pub fn transition_to_state(&mut self, target: SecurityEventState) -> Result<SecurityEventState, StateMachineError> {
        let valid = SecurityEventTransition::all().into_iter()
            .filter(|t| self.can_transition(*t))
            .find(|t| t.target_state() == target);
        match valid {
            Some(t) => self.transition(t),
            None => Err(StateMachineError::TransitionNotAllowed {
                transition: target.to_string(),
                from: self.current_state.to_string(),
            }),
        }
    }
}

impl Default for SecurityEventStateMachine {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_initial_state() {
        let sm = SecurityEventStateMachine::new();
        assert_eq!(sm.current_state(), SecurityEventState::False);
        assert!(sm.current_state().is_initial());
    }

    #[test]
    fn test_valid_transition() {
        let mut sm = SecurityEventStateMachine::from_state(SecurityEventState::False);
        assert!(sm.can_transition(SecurityEventTransition::Resolve));
        let result = sm.transition(SecurityEventTransition::Resolve);
        assert!(result.is_ok());
        assert_eq!(sm.current_state(), SecurityEventState::True);
    }

    #[test]
    fn test_invalid_transition() {
        let mut sm = SecurityEventStateMachine::from_state(SecurityEventState::True);
        // Resolve is not valid from True state
        let result = sm.transition(SecurityEventTransition::Resolve);
        assert!(result.is_err());
    }

    #[test]
    fn test_state_parsing() {
        let state: SecurityEventState = "false".parse().unwrap();
        assert_eq!(state, SecurityEventState::False);
    }

    #[test]
    fn test_available_transitions() {
        let sm = SecurityEventStateMachine::new();
        let available = sm.available_transitions();
        // Should have at least some transitions available from initial state
        assert!(!available.is_empty() || sm.current_state().is_final());
    }
}
