//! Bulk operations for OrganizationUser entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateOrganizationUserDto;
use crate::application::service::OrganizationUserService;
use crate::domain::entity::OrganizationUser;

/// Bulk operation handler for OrganizationUser entities.
///
/// Wraps `OrganizationUserService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type OrganizationUserBulkService = GenericBulkService<OrganizationUser, CreateOrganizationUserDto, OrganizationUserService>;

// <<< CUSTOM
// END CUSTOM
