//! Bulk operations for PasswordResetToken entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreatePasswordResetTokenDto;
use crate::application::service::PasswordResetTokenService;
use crate::domain::entity::PasswordResetToken;

/// Bulk operation handler for PasswordResetToken entities.
///
/// Wraps `PasswordResetTokenService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type PasswordResetTokenBulkService = GenericBulkService<PasswordResetToken, CreatePasswordResetTokenDto, PasswordResetTokenService>;

// <<< CUSTOM
// END CUSTOM
