//! Bulk operations for ResourcePermission entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateResourcePermissionDto;
use crate::application::service::ResourcePermissionService;
use crate::domain::entity::ResourcePermission;

/// Bulk operation handler for ResourcePermission entities.
///
/// Wraps `ResourcePermissionService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ResourcePermissionBulkService = GenericBulkService<ResourcePermission, CreateResourcePermissionDto, ResourcePermissionService>;

// <<< CUSTOM
// END CUSTOM
