//! Bulk operations for RolePermission entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateRolePermissionDto;
use crate::application::service::RolePermissionService;
use crate::domain::entity::RolePermission;

/// Bulk operation handler for RolePermission entities.
///
/// Wraps `RolePermissionService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type RolePermissionBulkService = GenericBulkService<RolePermission, CreateRolePermissionDto, RolePermissionService>;

// <<< CUSTOM
// END CUSTOM
