//! Bulk operations for SecurityEvent entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateSecurityEventDto;
use crate::application::service::SecurityEventService;
use crate::domain::entity::SecurityEvent;

/// Bulk operation handler for SecurityEvent entities.
///
/// Wraps `SecurityEventService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type SecurityEventBulkService = GenericBulkService<SecurityEvent, CreateSecurityEventDto, SecurityEventService>;

// <<< CUSTOM
// END CUSTOM
