//! BulkOperation DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::BulkOperation;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::BulkOperationStatus;
use crate::domain::entity::BulkOperationType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new BulkOperation
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateBulkOperationDto {
    pub operation_type: BulkOperationType,
    pub status: BulkOperationStatus,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub created_by: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub total_records: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub processed_records: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub successful_records: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub failed_records: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub skipped_records: i32,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input_file_path: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_file_path: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_file_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    pub progress_percentage: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub started_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub estimated_completion: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(range(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub retry_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub max_retries: i32,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a BulkOperation
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateBulkOperationDto {
    pub operation_type: BulkOperationType,
    pub status: BulkOperationStatus,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub created_by: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub total_records: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub processed_records: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub successful_records: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub failed_records: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub skipped_records: i32,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input_file_path: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_file_path: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_file_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    pub progress_percentage: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub started_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub estimated_completion: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(range(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub retry_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub max_retries: i32,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a BulkOperation
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchBulkOperationDto {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub operation_type: Option<BulkOperationType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<BulkOperationStatus>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_records: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub processed_records: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub successful_records: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failed_records: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub skipped_records: Option<i32>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input_file_path: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_file_path: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_file_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub progress_percentage: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub started_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub estimated_completion: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retry_count: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_retries: Option<i32>,
}

impl PatchBulkOperationDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.operation_type.is_some() || self.status.is_some() || self.created_by.is_some() || self.total_records.is_some() || self.processed_records.is_some() || self.successful_records.is_some() || self.failed_records.is_some() || self.skipped_records.is_some() || self.input_file_path.is_some() || self.output_file_path.is_some() || self.error_file_path.is_some() || self.parameters.is_some() || self.progress_percentage.is_some() || self.started_at.is_some() || self.completed_at.is_some() || self.estimated_completion.is_some() || self.error_message.is_some() || self.retry_count.is_some() || self.max_retries.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for BulkOperation entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BulkOperationResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    pub operation_type: BulkOperationType,
    pub status: BulkOperationStatus,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub created_by: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub total_records: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub processed_records: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub successful_records: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub failed_records: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub skipped_records: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input_file_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_file_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_file_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = 3.14))]
    pub progress_percentage: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub started_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub estimated_completion: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub retry_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub max_retries: i32,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for BulkOperation entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BulkOperationListResponseDto {
    /// List of items
    pub items: Vec<BulkOperationResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl BulkOperationListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<BulkOperationResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BulkOperationSummaryDto {
    pub id: Uuid,
    pub operation_type: BulkOperationType,
    pub status: BulkOperationStatus,
    pub created_by: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<BulkOperation> for BulkOperationResponseDto {
    fn from(entity: BulkOperation) -> Self {
        Self {
            id: entity.id,
            operation_type: entity.operation_type,
            status: entity.status,
            created_by: entity.created_by,
            total_records: entity.total_records,
            processed_records: entity.processed_records,
            successful_records: entity.successful_records,
            failed_records: entity.failed_records,
            skipped_records: entity.skipped_records,
            input_file_path: entity.input_file_path,
            output_file_path: entity.output_file_path,
            error_file_path: entity.error_file_path,
            parameters: entity.parameters,
            progress_percentage: entity.progress_percentage,
            started_at: entity.started_at,
            completed_at: entity.completed_at,
            estimated_completion: entity.estimated_completion,
            error_message: entity.error_message,
            retry_count: entity.retry_count,
            max_retries: entity.max_retries,
            metadata: entity.metadata,
        }
    }
}

impl From<BulkOperation> for BulkOperationSummaryDto {
    fn from(entity: BulkOperation) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            operation_type: entity.operation_type,
            status: entity.status,
            created_by: entity.created_by,
            created_at,
        }
    }
}

impl From<CreateBulkOperationDto> for BulkOperation {
    fn from(dto: CreateBulkOperationDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            operation_type: dto.operation_type,
            status: dto.status,
            created_by: dto.created_by,
            total_records: dto.total_records,
            processed_records: dto.processed_records,
            successful_records: dto.successful_records,
            failed_records: dto.failed_records,
            skipped_records: dto.skipped_records,
            input_file_path: dto.input_file_path,
            output_file_path: dto.output_file_path,
            error_file_path: dto.error_file_path,
            parameters: dto.parameters,
            progress_percentage: dto.progress_percentage,
            started_at: dto.started_at,
            completed_at: dto.completed_at,
            estimated_completion: dto.estimated_completion,
            error_message: dto.error_message,
            retry_count: dto.retry_count,
            max_retries: dto.max_retries,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&BulkOperation> for BulkOperationResponseDto {
    fn from(entity: &BulkOperation) -> Self {
        Self {
            id: entity.id.clone(),
            operation_type: entity.operation_type.clone(),
            status: entity.status.clone(),
            created_by: entity.created_by.clone(),
            total_records: entity.total_records.clone(),
            processed_records: entity.processed_records.clone(),
            successful_records: entity.successful_records.clone(),
            failed_records: entity.failed_records.clone(),
            skipped_records: entity.skipped_records.clone(),
            input_file_path: entity.input_file_path.clone(),
            output_file_path: entity.output_file_path.clone(),
            error_file_path: entity.error_file_path.clone(),
            parameters: entity.parameters.clone(),
            progress_percentage: entity.progress_percentage.clone(),
            started_at: entity.started_at.clone(),
            completed_at: entity.completed_at.clone(),
            estimated_completion: entity.estimated_completion.clone(),
            error_message: entity.error_message.clone(),
            retry_count: entity.retry_count.clone(),
            max_retries: entity.max_retries.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateBulkOperationDto> for BulkOperation {
    fn from_create_dto(dto: CreateBulkOperationDto) -> backbone_core::ServiceResult<Self> {
        Ok(BulkOperation::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateBulkOperationDto> for BulkOperation {
    fn apply_update(mut self, dto: UpdateBulkOperationDto) -> backbone_core::ServiceResult<Self> {
        self.operation_type = dto.operation_type;
        self.status = dto.status;
        self.created_by = dto.created_by;
        self.total_records = dto.total_records;
        self.processed_records = dto.processed_records;
        self.successful_records = dto.successful_records;
        self.failed_records = dto.failed_records;
        self.skipped_records = dto.skipped_records;
        self.input_file_path = dto.input_file_path;
        self.output_file_path = dto.output_file_path;
        self.error_file_path = dto.error_file_path;
        self.parameters = dto.parameters;
        self.progress_percentage = dto.progress_percentage;
        self.started_at = dto.started_at;
        self.completed_at = dto.completed_at;
        self.estimated_completion = dto.estimated_completion;
        self.error_message = dto.error_message;
        self.retry_count = dto.retry_count;
        self.max_retries = dto.max_retries;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to BulkOperation here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
