//! MFABackupCode DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::MFABackupCode;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::CompromiseDetectionMethod;
use crate::domain::entity::GenerationMethod;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new MFABackupCode
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMFABackupCodeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub batch_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code_hash: String,
    #[cfg_attr(feature = "validation", validate(range(min = 1), range(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub code_index: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub generated_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated_by: Option<Uuid>,
    pub generation_method: GenerationMethod,
    #[cfg_attr(feature = "validation", validate(length(max = 45)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub generation_ip: String,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub algorithm_version: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub used_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(range(max = 45)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub used_ip: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub used_user_agent: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verification_attempt: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_since_generation: Option<i32>,
    #[cfg_attr(feature = "validation", validate(range(min = 0), range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage_risk_score: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_consumed: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub consumption_attempts: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub successful_verification: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_revoked: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revoked_by: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revocation_reason: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub compromised: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub compromised_detected_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub compromise_detection_method: Option<CompromiseDetectionMethod>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub expires_at: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub created_with_expiry: bool,
    #[cfg_attr(feature = "validation", validate(range(min = 0), range(max = 168)))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub grace_period_hours: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub auto_renew_enabled: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub renewal_reminder_sent: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_access_before_expiry: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub creation_notification_sent: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub expiry_warning_sent: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub usage_notification_sent: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub security_alert_sent: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_notification_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub gdpr_compliant: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub audit_log_required: bool,
    #[cfg_attr(feature = "validation", validate(range(min = 30), range(max = 1825)))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub data_retention_days: i32,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a MFABackupCode
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMFABackupCodeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub batch_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code_hash: String,
    #[cfg_attr(feature = "validation", validate(range(min = 1), range(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub code_index: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub generated_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated_by: Option<Uuid>,
    pub generation_method: GenerationMethod,
    #[cfg_attr(feature = "validation", validate(length(max = 45)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub generation_ip: String,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub algorithm_version: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub used_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(range(max = 45)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub used_ip: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub used_user_agent: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verification_attempt: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_since_generation: Option<i32>,
    #[cfg_attr(feature = "validation", validate(range(min = 0), range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage_risk_score: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_consumed: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub consumption_attempts: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub successful_verification: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_revoked: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revoked_by: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revocation_reason: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub compromised: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub compromised_detected_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub compromise_detection_method: Option<CompromiseDetectionMethod>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub expires_at: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub created_with_expiry: bool,
    #[cfg_attr(feature = "validation", validate(range(min = 0), range(max = 168)))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub grace_period_hours: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub auto_renew_enabled: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub renewal_reminder_sent: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_access_before_expiry: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub creation_notification_sent: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub expiry_warning_sent: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub usage_notification_sent: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub security_alert_sent: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_notification_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub gdpr_compliant: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub audit_log_required: bool,
    #[cfg_attr(feature = "validation", validate(range(min = 30), range(max = 1825)))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub data_retention_days: i32,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a MFABackupCode
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMFABackupCodeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub batch_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code_hash: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code_index: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generated_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generated_by: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generation_method: Option<GenerationMethod>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generation_ip: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub algorithm_version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub used_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub used_ip: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub used_user_agent: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verification_attempt: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub time_since_generation: Option<i32>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage_risk_score: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_consumed: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub consumption_attempts: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub successful_verification: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_revoked: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub revoked_by: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub revocation_reason: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compromised: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compromised_detected_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compromise_detection_method: Option<CompromiseDetectionMethod>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_with_expiry: Option<bool>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub grace_period_hours: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub auto_renew_enabled: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub renewal_reminder_sent: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_access_before_expiry: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub creation_notification_sent: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expiry_warning_sent: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage_notification_sent: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub security_alert_sent: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_notification_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gdpr_compliant: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub audit_log_required: Option<bool>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data_retention_days: Option<i32>,
}

impl PatchMFABackupCodeDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.user_id.is_some() || self.device_id.is_some() || self.batch_id.is_some() || self.code.is_some() || self.code_hash.is_some() || self.code_index.is_some() || self.generated_at.is_some() || self.generated_by.is_some() || self.generation_method.is_some() || self.generation_ip.is_some() || self.algorithm_version.is_some() || self.used_at.is_some() || self.used_ip.is_some() || self.used_user_agent.is_some() || self.session_id.is_some() || self.verification_attempt.is_some() || self.time_since_generation.is_some() || self.usage_risk_score.is_some() || self.is_consumed.is_some() || self.consumption_attempts.is_some() || self.successful_verification.is_some() || self.is_revoked.is_some() || self.revoked_at.is_some() || self.revoked_by.is_some() || self.revocation_reason.is_some() || self.compromised.is_some() || self.compromised_detected_at.is_some() || self.compromise_detection_method.is_some() || self.expires_at.is_some() || self.created_with_expiry.is_some() || self.grace_period_hours.is_some() || self.auto_renew_enabled.is_some() || self.renewal_reminder_sent.is_some() || self.last_access_before_expiry.is_some() || self.creation_notification_sent.is_some() || self.expiry_warning_sent.is_some() || self.usage_notification_sent.is_some() || self.security_alert_sent.is_some() || self.last_notification_at.is_some() || self.gdpr_compliant.is_some() || self.audit_log_required.is_some() || self.data_retention_days.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for MFABackupCode entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MFABackupCodeResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_id: Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub batch_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code_hash: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub code_index: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub generated_at: DateTime<Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generated_by: Option<Uuid>,
    pub generation_method: GenerationMethod,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub generation_ip: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub algorithm_version: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub used_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub used_ip: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub used_user_agent: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verification_attempt: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub time_since_generation: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage_risk_score: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_consumed: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub consumption_attempts: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub successful_verification: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_revoked: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub revoked_by: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub revocation_reason: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub compromised: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compromised_detected_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compromise_detection_method: Option<CompromiseDetectionMethod>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub expires_at: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub created_with_expiry: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub grace_period_hours: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub auto_renew_enabled: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub renewal_reminder_sent: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_access_before_expiry: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub creation_notification_sent: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub expiry_warning_sent: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub usage_notification_sent: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub security_alert_sent: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_notification_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub gdpr_compliant: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub audit_log_required: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub data_retention_days: i32,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for MFABackupCode entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MFABackupCodeListResponseDto {
    /// List of items
    pub items: Vec<MFABackupCodeResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MFABackupCodeListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MFABackupCodeResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MFABackupCodeSummaryDto {
    pub id: Uuid,
    pub user_id: Uuid,
    pub device_id: Option<Uuid>,
    pub batch_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<MFABackupCode> for MFABackupCodeResponseDto {
    fn from(entity: MFABackupCode) -> Self {
        Self {
            id: entity.id,
            user_id: entity.user_id,
            device_id: entity.device_id,
            batch_id: entity.batch_id,
            code: entity.code,
            code_hash: entity.code_hash,
            code_index: entity.code_index,
            generated_at: entity.generated_at,
            generated_by: entity.generated_by,
            generation_method: entity.generation_method,
            generation_ip: entity.generation_ip,
            algorithm_version: entity.algorithm_version,
            used_at: entity.used_at,
            used_ip: entity.used_ip,
            used_user_agent: entity.used_user_agent,
            session_id: entity.session_id,
            verification_attempt: entity.verification_attempt,
            time_since_generation: entity.time_since_generation,
            usage_risk_score: entity.usage_risk_score,
            is_consumed: entity.is_consumed,
            consumption_attempts: entity.consumption_attempts,
            successful_verification: entity.successful_verification,
            is_revoked: entity.is_revoked,
            revoked_at: entity.revoked_at,
            revoked_by: entity.revoked_by,
            revocation_reason: entity.revocation_reason,
            compromised: entity.compromised,
            compromised_detected_at: entity.compromised_detected_at,
            compromise_detection_method: entity.compromise_detection_method,
            expires_at: entity.expires_at,
            created_with_expiry: entity.created_with_expiry,
            grace_period_hours: entity.grace_period_hours,
            auto_renew_enabled: entity.auto_renew_enabled,
            renewal_reminder_sent: entity.renewal_reminder_sent,
            last_access_before_expiry: entity.last_access_before_expiry,
            creation_notification_sent: entity.creation_notification_sent,
            expiry_warning_sent: entity.expiry_warning_sent,
            usage_notification_sent: entity.usage_notification_sent,
            security_alert_sent: entity.security_alert_sent,
            last_notification_at: entity.last_notification_at,
            gdpr_compliant: entity.gdpr_compliant,
            audit_log_required: entity.audit_log_required,
            data_retention_days: entity.data_retention_days,
            metadata: entity.metadata,
        }
    }
}

impl From<MFABackupCode> for MFABackupCodeSummaryDto {
    fn from(entity: MFABackupCode) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            user_id: entity.user_id,
            device_id: entity.device_id,
            batch_id: entity.batch_id,
            created_at,
        }
    }
}

impl From<CreateMFABackupCodeDto> for MFABackupCode {
    fn from(dto: CreateMFABackupCodeDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            user_id: dto.user_id,
            device_id: dto.device_id,
            batch_id: dto.batch_id,
            code: dto.code,
            code_hash: dto.code_hash,
            code_index: dto.code_index,
            generated_at: dto.generated_at,
            generated_by: dto.generated_by,
            generation_method: dto.generation_method,
            generation_ip: dto.generation_ip,
            algorithm_version: dto.algorithm_version,
            used_at: dto.used_at,
            used_ip: dto.used_ip,
            used_user_agent: dto.used_user_agent,
            session_id: dto.session_id,
            verification_attempt: dto.verification_attempt,
            time_since_generation: dto.time_since_generation,
            usage_risk_score: dto.usage_risk_score,
            is_consumed: dto.is_consumed,
            consumption_attempts: dto.consumption_attempts,
            successful_verification: dto.successful_verification,
            is_revoked: dto.is_revoked,
            revoked_at: dto.revoked_at,
            revoked_by: dto.revoked_by,
            revocation_reason: dto.revocation_reason,
            compromised: dto.compromised,
            compromised_detected_at: dto.compromised_detected_at,
            compromise_detection_method: dto.compromise_detection_method,
            expires_at: dto.expires_at,
            created_with_expiry: dto.created_with_expiry,
            grace_period_hours: dto.grace_period_hours,
            auto_renew_enabled: dto.auto_renew_enabled,
            renewal_reminder_sent: dto.renewal_reminder_sent,
            last_access_before_expiry: dto.last_access_before_expiry,
            creation_notification_sent: dto.creation_notification_sent,
            expiry_warning_sent: dto.expiry_warning_sent,
            usage_notification_sent: dto.usage_notification_sent,
            security_alert_sent: dto.security_alert_sent,
            last_notification_at: dto.last_notification_at,
            gdpr_compliant: dto.gdpr_compliant,
            audit_log_required: dto.audit_log_required,
            data_retention_days: dto.data_retention_days,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&MFABackupCode> for MFABackupCodeResponseDto {
    fn from(entity: &MFABackupCode) -> Self {
        Self {
            id: entity.id.clone(),
            user_id: entity.user_id.clone(),
            device_id: entity.device_id.clone(),
            batch_id: entity.batch_id.clone(),
            code: entity.code.clone(),
            code_hash: entity.code_hash.clone(),
            code_index: entity.code_index.clone(),
            generated_at: entity.generated_at.clone(),
            generated_by: entity.generated_by.clone(),
            generation_method: entity.generation_method.clone(),
            generation_ip: entity.generation_ip.clone(),
            algorithm_version: entity.algorithm_version.clone(),
            used_at: entity.used_at.clone(),
            used_ip: entity.used_ip.clone(),
            used_user_agent: entity.used_user_agent.clone(),
            session_id: entity.session_id.clone(),
            verification_attempt: entity.verification_attempt.clone(),
            time_since_generation: entity.time_since_generation.clone(),
            usage_risk_score: entity.usage_risk_score.clone(),
            is_consumed: entity.is_consumed.clone(),
            consumption_attempts: entity.consumption_attempts.clone(),
            successful_verification: entity.successful_verification.clone(),
            is_revoked: entity.is_revoked.clone(),
            revoked_at: entity.revoked_at.clone(),
            revoked_by: entity.revoked_by.clone(),
            revocation_reason: entity.revocation_reason.clone(),
            compromised: entity.compromised.clone(),
            compromised_detected_at: entity.compromised_detected_at.clone(),
            compromise_detection_method: entity.compromise_detection_method.clone(),
            expires_at: entity.expires_at.clone(),
            created_with_expiry: entity.created_with_expiry.clone(),
            grace_period_hours: entity.grace_period_hours.clone(),
            auto_renew_enabled: entity.auto_renew_enabled.clone(),
            renewal_reminder_sent: entity.renewal_reminder_sent.clone(),
            last_access_before_expiry: entity.last_access_before_expiry.clone(),
            creation_notification_sent: entity.creation_notification_sent.clone(),
            expiry_warning_sent: entity.expiry_warning_sent.clone(),
            usage_notification_sent: entity.usage_notification_sent.clone(),
            security_alert_sent: entity.security_alert_sent.clone(),
            last_notification_at: entity.last_notification_at.clone(),
            gdpr_compliant: entity.gdpr_compliant.clone(),
            audit_log_required: entity.audit_log_required.clone(),
            data_retention_days: entity.data_retention_days.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMFABackupCodeDto> for MFABackupCode {
    fn from_create_dto(dto: CreateMFABackupCodeDto) -> backbone_core::ServiceResult<Self> {
        Ok(MFABackupCode::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMFABackupCodeDto> for MFABackupCode {
    fn apply_update(mut self, dto: UpdateMFABackupCodeDto) -> backbone_core::ServiceResult<Self> {
        self.user_id = dto.user_id;
        self.device_id = dto.device_id;
        self.batch_id = dto.batch_id;
        self.code = dto.code;
        self.code_hash = dto.code_hash;
        self.code_index = dto.code_index;
        self.generated_at = dto.generated_at;
        self.generated_by = dto.generated_by;
        self.generation_method = dto.generation_method;
        self.generation_ip = dto.generation_ip;
        self.algorithm_version = dto.algorithm_version;
        self.used_at = dto.used_at;
        self.used_ip = dto.used_ip;
        self.used_user_agent = dto.used_user_agent;
        self.session_id = dto.session_id;
        self.verification_attempt = dto.verification_attempt;
        self.time_since_generation = dto.time_since_generation;
        self.usage_risk_score = dto.usage_risk_score;
        self.is_consumed = dto.is_consumed;
        self.consumption_attempts = dto.consumption_attempts;
        self.successful_verification = dto.successful_verification;
        self.is_revoked = dto.is_revoked;
        self.revoked_at = dto.revoked_at;
        self.revoked_by = dto.revoked_by;
        self.revocation_reason = dto.revocation_reason;
        self.compromised = dto.compromised;
        self.compromised_detected_at = dto.compromised_detected_at;
        self.compromise_detection_method = dto.compromise_detection_method;
        self.expires_at = dto.expires_at;
        self.created_with_expiry = dto.created_with_expiry;
        self.grace_period_hours = dto.grace_period_hours;
        self.auto_renew_enabled = dto.auto_renew_enabled;
        self.renewal_reminder_sent = dto.renewal_reminder_sent;
        self.last_access_before_expiry = dto.last_access_before_expiry;
        self.creation_notification_sent = dto.creation_notification_sent;
        self.expiry_warning_sent = dto.expiry_warning_sent;
        self.usage_notification_sent = dto.usage_notification_sent;
        self.security_alert_sent = dto.security_alert_sent;
        self.last_notification_at = dto.last_notification_at;
        self.gdpr_compliant = dto.gdpr_compliant;
        self.audit_log_required = dto.audit_log_required;
        self.data_retention_days = dto.data_retention_days;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to MFABackupCode here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
