//! DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! This module provides DTOs for the presentation layer,
//! with validation and OpenAPI schema support.

pub mod analytics_event_dto;
pub mod analytics_metric_dto;
pub mod analytics_report_dto;
pub mod anonymization_record_dto;
pub mod audit_log_dto;
pub mod backup_code_dto;
pub mod bulk_operation_dto;
pub mod bulk_operation_result_dto;
pub mod data_export_dto;
pub mod device_trust_dto;
pub mod direct_permission_grant_dto;
pub mod effective_permission_cache_dto;
pub mod email_verification_token_dto;
pub mod impersonation_session_dto;
pub mod ldap_directory_dto;
pub mod mfa_backup_code_dto;
pub mod mfa_device_dto;
pub mod mfa_session_dto;
pub mod notification_dto;
pub mod notification_template_dto;
pub mod notification_log_dto;
pub mod notification_preference_dto;
pub mod o_auth_provider_dto;
pub mod user_o_auth_link_dto;
pub mod organization_permission_dto;
pub mod organization_role_dto;
pub mod organization_user_dto;
pub mod password_creation_context_dto;
pub mod password_expiration_settings_dto;
pub mod password_history_dto;
pub mod password_history_settings_dto;
pub mod password_policy_dto;
pub mod password_requirements_dto;
pub mod password_reset_dto;
pub mod password_reset_security_dto;
pub mod password_reset_token_dto;
pub mod password_reset_verification_details_dto;
pub mod permission_dto;
pub mod permission_conflict_dto;
pub mod resource_permission_dto;
pub mod role_dto;
pub mod role_assignment_dto;
pub mod role_permission_dto;
pub mod saml_provider_dto;
pub mod security_event_dto;
pub mod session_dto;
pub mod session_limit_dto;
pub mod system_settings_dto;
pub mod temporary_permission_dto;
pub mod user_dto;
pub mod profile_dto;
pub mod user_permission_dto;
pub mod user_role_dto;
pub mod user_saml_link_dto;
pub mod user_settings_dto;
pub mod workflow_dto;
pub mod workflow_step_dto;
pub mod workflow_definition_dto;
pub mod workflow_action_dto;
pub mod workflow_execution_dto;
pub mod workflow_action_execution_dto;

// Re-exports
pub use analytics_event_dto::{
    CreateAnalyticsEventDto,
    UpdateAnalyticsEventDto,
    PatchAnalyticsEventDto,
    AnalyticsEventResponseDto,
    AnalyticsEventListResponseDto,
    AnalyticsEventSummaryDto,
};
pub use analytics_metric_dto::{
    CreateAnalyticsMetricDto,
    UpdateAnalyticsMetricDto,
    PatchAnalyticsMetricDto,
    AnalyticsMetricResponseDto,
    AnalyticsMetricListResponseDto,
    AnalyticsMetricSummaryDto,
};
pub use analytics_report_dto::{
    CreateAnalyticsReportDto,
    UpdateAnalyticsReportDto,
    PatchAnalyticsReportDto,
    AnalyticsReportResponseDto,
    AnalyticsReportListResponseDto,
    AnalyticsReportSummaryDto,
};
pub use anonymization_record_dto::{
    CreateAnonymizationRecordDto,
    UpdateAnonymizationRecordDto,
    PatchAnonymizationRecordDto,
    AnonymizationRecordResponseDto,
    AnonymizationRecordListResponseDto,
    AnonymizationRecordSummaryDto,
};
pub use audit_log_dto::{
    CreateAuditLogDto,
    UpdateAuditLogDto,
    PatchAuditLogDto,
    AuditLogResponseDto,
    AuditLogListResponseDto,
    AuditLogSummaryDto,
};
pub use backup_code_dto::{
    CreateBackupCodeDto,
    UpdateBackupCodeDto,
    PatchBackupCodeDto,
    BackupCodeResponseDto,
    BackupCodeListResponseDto,
    BackupCodeSummaryDto,
};
pub use bulk_operation_dto::{
    CreateBulkOperationDto,
    UpdateBulkOperationDto,
    PatchBulkOperationDto,
    BulkOperationResponseDto,
    BulkOperationListResponseDto,
    BulkOperationSummaryDto,
};
pub use bulk_operation_result_dto::{
    CreateBulkOperationResultDto,
    UpdateBulkOperationResultDto,
    PatchBulkOperationResultDto,
    BulkOperationResultResponseDto,
    BulkOperationResultListResponseDto,
    BulkOperationResultSummaryDto,
};
pub use data_export_dto::{
    CreateDataExportDto,
    UpdateDataExportDto,
    PatchDataExportDto,
    DataExportResponseDto,
    DataExportListResponseDto,
    DataExportSummaryDto,
};
pub use device_trust_dto::{
    CreateDeviceTrustDto,
    UpdateDeviceTrustDto,
    PatchDeviceTrustDto,
    DeviceTrustResponseDto,
    DeviceTrustListResponseDto,
    DeviceTrustSummaryDto,
};
pub use direct_permission_grant_dto::{
    CreateDirectPermissionGrantDto,
    UpdateDirectPermissionGrantDto,
    PatchDirectPermissionGrantDto,
    DirectPermissionGrantResponseDto,
    DirectPermissionGrantListResponseDto,
    DirectPermissionGrantSummaryDto,
};
pub use effective_permission_cache_dto::{
    CreateEffectivePermissionCacheDto,
    UpdateEffectivePermissionCacheDto,
    PatchEffectivePermissionCacheDto,
    EffectivePermissionCacheResponseDto,
    EffectivePermissionCacheListResponseDto,
    EffectivePermissionCacheSummaryDto,
};
pub use email_verification_token_dto::{
    CreateEmailVerificationTokenDto,
    UpdateEmailVerificationTokenDto,
    PatchEmailVerificationTokenDto,
    EmailVerificationTokenResponseDto,
    EmailVerificationTokenListResponseDto,
    EmailVerificationTokenSummaryDto,
};
pub use impersonation_session_dto::{
    CreateImpersonationSessionDto,
    UpdateImpersonationSessionDto,
    PatchImpersonationSessionDto,
    ImpersonationSessionResponseDto,
    ImpersonationSessionListResponseDto,
    ImpersonationSessionSummaryDto,
};
pub use ldap_directory_dto::{
    CreateLDAPDirectoryDto,
    UpdateLDAPDirectoryDto,
    PatchLDAPDirectoryDto,
    LDAPDirectoryResponseDto,
    LDAPDirectoryListResponseDto,
    LDAPDirectorySummaryDto,
};
pub use mfa_backup_code_dto::{
    CreateMFABackupCodeDto,
    UpdateMFABackupCodeDto,
    PatchMFABackupCodeDto,
    MFABackupCodeResponseDto,
    MFABackupCodeListResponseDto,
    MFABackupCodeSummaryDto,
};
pub use mfa_device_dto::{
    CreateMFADeviceDto,
    UpdateMFADeviceDto,
    PatchMFADeviceDto,
    MFADeviceResponseDto,
    MFADeviceListResponseDto,
    MFADeviceSummaryDto,
};
pub use mfa_session_dto::{
    CreateMFASessionDto,
    UpdateMFASessionDto,
    PatchMFASessionDto,
    MFASessionResponseDto,
    MFASessionListResponseDto,
    MFASessionSummaryDto,
};
pub use notification_dto::{
    CreateNotificationDto,
    UpdateNotificationDto,
    PatchNotificationDto,
    NotificationResponseDto,
    NotificationListResponseDto,
    NotificationSummaryDto,
};
pub use notification_template_dto::{
    CreateNotificationTemplateDto,
    UpdateNotificationTemplateDto,
    PatchNotificationTemplateDto,
    NotificationTemplateResponseDto,
    NotificationTemplateListResponseDto,
    NotificationTemplateSummaryDto,
};
pub use notification_log_dto::{
    CreateNotificationLogDto,
    UpdateNotificationLogDto,
    PatchNotificationLogDto,
    NotificationLogResponseDto,
    NotificationLogListResponseDto,
    NotificationLogSummaryDto,
};
pub use notification_preference_dto::{
    CreateNotificationPreferenceDto,
    UpdateNotificationPreferenceDto,
    PatchNotificationPreferenceDto,
    NotificationPreferenceResponseDto,
    NotificationPreferenceListResponseDto,
    NotificationPreferenceSummaryDto,
};
pub use o_auth_provider_dto::{
    CreateOAuthProviderDto,
    UpdateOAuthProviderDto,
    PatchOAuthProviderDto,
    OAuthProviderResponseDto,
    OAuthProviderListResponseDto,
    OAuthProviderSummaryDto,
};
pub use user_o_auth_link_dto::{
    CreateUserOAuthLinkDto,
    UpdateUserOAuthLinkDto,
    PatchUserOAuthLinkDto,
    UserOAuthLinkResponseDto,
    UserOAuthLinkListResponseDto,
    UserOAuthLinkSummaryDto,
};
pub use organization_permission_dto::{
    CreateOrganizationPermissionDto,
    UpdateOrganizationPermissionDto,
    PatchOrganizationPermissionDto,
    OrganizationPermissionResponseDto,
    OrganizationPermissionListResponseDto,
    OrganizationPermissionSummaryDto,
};
pub use organization_role_dto::{
    CreateOrganizationRoleDto,
    UpdateOrganizationRoleDto,
    PatchOrganizationRoleDto,
    OrganizationRoleResponseDto,
    OrganizationRoleListResponseDto,
    OrganizationRoleSummaryDto,
};
pub use organization_user_dto::{
    CreateOrganizationUserDto,
    UpdateOrganizationUserDto,
    PatchOrganizationUserDto,
    OrganizationUserResponseDto,
    OrganizationUserListResponseDto,
    OrganizationUserSummaryDto,
};
pub use password_creation_context_dto::{
    CreatePasswordCreationContextDto,
    UpdatePasswordCreationContextDto,
    PatchPasswordCreationContextDto,
    PasswordCreationContextResponseDto,
    PasswordCreationContextListResponseDto,
    PasswordCreationContextSummaryDto,
};
pub use password_expiration_settings_dto::{
    CreatePasswordExpirationSettingsDto,
    UpdatePasswordExpirationSettingsDto,
    PatchPasswordExpirationSettingsDto,
    PasswordExpirationSettingsResponseDto,
    PasswordExpirationSettingsListResponseDto,
    PasswordExpirationSettingsSummaryDto,
};
pub use password_history_dto::{
    CreatePasswordHistoryDto,
    UpdatePasswordHistoryDto,
    PatchPasswordHistoryDto,
    PasswordHistoryResponseDto,
    PasswordHistoryListResponseDto,
    PasswordHistorySummaryDto,
};
pub use password_history_settings_dto::{
    CreatePasswordHistorySettingsDto,
    UpdatePasswordHistorySettingsDto,
    PatchPasswordHistorySettingsDto,
    PasswordHistorySettingsResponseDto,
    PasswordHistorySettingsListResponseDto,
    PasswordHistorySettingsSummaryDto,
};
pub use password_policy_dto::{
    CreatePasswordPolicyDto,
    UpdatePasswordPolicyDto,
    PatchPasswordPolicyDto,
    PasswordPolicyResponseDto,
    PasswordPolicyListResponseDto,
    PasswordPolicySummaryDto,
};
pub use password_requirements_dto::{
    CreatePasswordRequirementsDto,
    UpdatePasswordRequirementsDto,
    PatchPasswordRequirementsDto,
    PasswordRequirementsResponseDto,
    PasswordRequirementsListResponseDto,
    PasswordRequirementsSummaryDto,
};
pub use password_reset_dto::{
    CreatePasswordResetDto,
    UpdatePasswordResetDto,
    PatchPasswordResetDto,
    PasswordResetResponseDto,
    PasswordResetListResponseDto,
    PasswordResetSummaryDto,
};
pub use password_reset_security_dto::{
    CreatePasswordResetSecurityDto,
    UpdatePasswordResetSecurityDto,
    PatchPasswordResetSecurityDto,
    PasswordResetSecurityResponseDto,
    PasswordResetSecurityListResponseDto,
    PasswordResetSecuritySummaryDto,
};
pub use password_reset_token_dto::{
    CreatePasswordResetTokenDto,
    UpdatePasswordResetTokenDto,
    PatchPasswordResetTokenDto,
    PasswordResetTokenResponseDto,
    PasswordResetTokenListResponseDto,
    PasswordResetTokenSummaryDto,
};
pub use password_reset_verification_details_dto::{
    CreatePasswordResetVerificationDetailsDto,
    UpdatePasswordResetVerificationDetailsDto,
    PatchPasswordResetVerificationDetailsDto,
    PasswordResetVerificationDetailsResponseDto,
    PasswordResetVerificationDetailsListResponseDto,
    PasswordResetVerificationDetailsSummaryDto,
};
pub use permission_dto::{
    CreatePermissionDto,
    UpdatePermissionDto,
    PatchPermissionDto,
    PermissionResponseDto,
    PermissionListResponseDto,
    PermissionSummaryDto,
};
pub use permission_conflict_dto::{
    CreatePermissionConflictDto,
    UpdatePermissionConflictDto,
    PatchPermissionConflictDto,
    PermissionConflictResponseDto,
    PermissionConflictListResponseDto,
    PermissionConflictSummaryDto,
};
pub use resource_permission_dto::{
    CreateResourcePermissionDto,
    UpdateResourcePermissionDto,
    PatchResourcePermissionDto,
    ResourcePermissionResponseDto,
    ResourcePermissionListResponseDto,
    ResourcePermissionSummaryDto,
};
pub use role_dto::{
    CreateRoleDto,
    UpdateRoleDto,
    PatchRoleDto,
    RoleResponseDto,
    RoleListResponseDto,
    RoleSummaryDto,
};
pub use role_assignment_dto::{
    CreateRoleAssignmentDto,
    UpdateRoleAssignmentDto,
    PatchRoleAssignmentDto,
    RoleAssignmentResponseDto,
    RoleAssignmentListResponseDto,
    RoleAssignmentSummaryDto,
};
pub use role_permission_dto::{
    CreateRolePermissionDto,
    UpdateRolePermissionDto,
    PatchRolePermissionDto,
    RolePermissionResponseDto,
    RolePermissionListResponseDto,
    RolePermissionSummaryDto,
};
pub use saml_provider_dto::{
    CreateSAMLProviderDto,
    UpdateSAMLProviderDto,
    PatchSAMLProviderDto,
    SAMLProviderResponseDto,
    SAMLProviderListResponseDto,
    SAMLProviderSummaryDto,
};
pub use security_event_dto::{
    CreateSecurityEventDto,
    UpdateSecurityEventDto,
    PatchSecurityEventDto,
    SecurityEventResponseDto,
    SecurityEventListResponseDto,
    SecurityEventSummaryDto,
};
pub use session_dto::{
    CreateSessionDto,
    UpdateSessionDto,
    PatchSessionDto,
    SessionResponseDto,
    SessionListResponseDto,
    SessionSummaryDto,
};
pub use session_limit_dto::{
    CreateSessionLimitDto,
    UpdateSessionLimitDto,
    PatchSessionLimitDto,
    SessionLimitResponseDto,
    SessionLimitListResponseDto,
    SessionLimitSummaryDto,
};
pub use system_settings_dto::{
    CreateSystemSettingsDto,
    UpdateSystemSettingsDto,
    PatchSystemSettingsDto,
    SystemSettingsResponseDto,
    SystemSettingsListResponseDto,
    SystemSettingsSummaryDto,
};
pub use temporary_permission_dto::{
    CreateTemporaryPermissionDto,
    UpdateTemporaryPermissionDto,
    PatchTemporaryPermissionDto,
    TemporaryPermissionResponseDto,
    TemporaryPermissionListResponseDto,
    TemporaryPermissionSummaryDto,
};
pub use user_dto::{
    CreateUserDto,
    UpdateUserDto,
    PatchUserDto,
    UserResponseDto,
    UserListResponseDto,
    UserSummaryDto,
};
pub use profile_dto::{
    CreateProfileDto,
    UpdateProfileDto,
    PatchProfileDto,
    ProfileResponseDto,
    ProfileListResponseDto,
    ProfileSummaryDto,
};
pub use user_permission_dto::{
    CreateUserPermissionDto,
    UpdateUserPermissionDto,
    PatchUserPermissionDto,
    UserPermissionResponseDto,
    UserPermissionListResponseDto,
    UserPermissionSummaryDto,
};
pub use user_role_dto::{
    CreateUserRoleDto,
    UpdateUserRoleDto,
    PatchUserRoleDto,
    UserRoleResponseDto,
    UserRoleListResponseDto,
    UserRoleSummaryDto,
};
pub use user_saml_link_dto::{
    CreateUserSAMLLinkDto,
    UpdateUserSAMLLinkDto,
    PatchUserSAMLLinkDto,
    UserSAMLLinkResponseDto,
    UserSAMLLinkListResponseDto,
    UserSAMLLinkSummaryDto,
};
pub use user_settings_dto::{
    CreateUserSettingsDto,
    UpdateUserSettingsDto,
    PatchUserSettingsDto,
    UserSettingsResponseDto,
    UserSettingsListResponseDto,
    UserSettingsSummaryDto,
};
pub use workflow_dto::{
    CreateWorkflowDto,
    UpdateWorkflowDto,
    PatchWorkflowDto,
    WorkflowResponseDto,
    WorkflowListResponseDto,
    WorkflowSummaryDto,
};
pub use workflow_step_dto::{
    CreateWorkflowStepDto,
    UpdateWorkflowStepDto,
    PatchWorkflowStepDto,
    WorkflowStepResponseDto,
    WorkflowStepListResponseDto,
    WorkflowStepSummaryDto,
};
pub use workflow_definition_dto::{
    CreateWorkflowDefinitionDto,
    UpdateWorkflowDefinitionDto,
    PatchWorkflowDefinitionDto,
    WorkflowDefinitionResponseDto,
    WorkflowDefinitionListResponseDto,
    WorkflowDefinitionSummaryDto,
};
pub use workflow_action_dto::{
    CreateWorkflowActionDto,
    UpdateWorkflowActionDto,
    PatchWorkflowActionDto,
    WorkflowActionResponseDto,
    WorkflowActionListResponseDto,
    WorkflowActionSummaryDto,
};
pub use workflow_execution_dto::{
    CreateWorkflowExecutionDto,
    UpdateWorkflowExecutionDto,
    PatchWorkflowExecutionDto,
    WorkflowExecutionResponseDto,
    WorkflowExecutionListResponseDto,
    WorkflowExecutionSummaryDto,
};
pub use workflow_action_execution_dto::{
    CreateWorkflowActionExecutionDto,
    UpdateWorkflowActionExecutionDto,
    PatchWorkflowActionExecutionDto,
    WorkflowActionExecutionResponseDto,
    WorkflowActionExecutionListResponseDto,
    WorkflowActionExecutionSummaryDto,
};

// Common pagination types
use serde::Serialize;

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

/// Pagination parameters for list requests
#[derive(Debug, Clone, Default, serde::Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct PaginationParams {
    /// Page number (1-indexed)
    #[serde(default = "default_page")]
    pub page: u32,
    /// Items per page
    #[serde(default = "default_per_page")]
    pub per_page: u32,
    /// Field to sort by
    pub sort_by: Option<String>,
    /// Sort order (asc/desc)
    pub sort_order: Option<String>,
}

fn default_page() -> u32 { 1 }
fn default_per_page() -> u32 { 20 }

/// API response wrapper
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApiResponse<T> {
    pub success: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<T>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ApiError>,
}

#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct ApiError {
    pub code: String,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
}

impl<T> ApiResponse<T> {
    pub fn ok(data: T) -> Self {
        Self { success: true, data: Some(data), error: None }
    }

    pub fn err(code: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            success: false,
            data: None,
            error: Some(ApiError {
                code: code.into(),
                message: message.into(),
                details: None,
            }),
        }
    }
}
