//! NotificationTemplate DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::NotificationTemplate;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::NotificationChannel;
use crate::domain::entity::NotificationType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new NotificationTemplate
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateNotificationTemplateDto {
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub notification_type: NotificationType,
    pub channel: NotificationChannel,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subject_template: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub message_template: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub variables: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub language: String,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a NotificationTemplate
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateNotificationTemplateDto {
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub notification_type: NotificationType,
    pub channel: NotificationChannel,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subject_template: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub message_template: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub variables: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub language: String,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a NotificationTemplate
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchNotificationTemplateDto {
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notification_type: Option<NotificationType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channel: Option<NotificationChannel>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject_template: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_template: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub variables: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
}

impl PatchNotificationTemplateDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some() || self.notification_type.is_some() || self.channel.is_some() || self.subject_template.is_some() || self.message_template.is_some() || self.variables.is_some() || self.is_active.is_some() || self.language.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for NotificationTemplate entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct NotificationTemplateResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub notification_type: NotificationType,
    pub channel: NotificationChannel,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject_template: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub message_template: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub variables: Option<serde_json::Value>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub language: String,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for NotificationTemplate entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct NotificationTemplateListResponseDto {
    /// List of items
    pub items: Vec<NotificationTemplateResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl NotificationTemplateListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<NotificationTemplateResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct NotificationTemplateSummaryDto {
    pub id: Uuid,
    pub name: String,
    pub notification_type: NotificationType,
    pub channel: NotificationChannel,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<NotificationTemplate> for NotificationTemplateResponseDto {
    fn from(entity: NotificationTemplate) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            notification_type: entity.notification_type,
            channel: entity.channel,
            subject_template: entity.subject_template,
            message_template: entity.message_template,
            variables: entity.variables,
            is_active: entity.is_active,
            language: entity.language,
            metadata: entity.metadata,
        }
    }
}

impl From<NotificationTemplate> for NotificationTemplateSummaryDto {
    fn from(entity: NotificationTemplate) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            notification_type: entity.notification_type,
            channel: entity.channel,
            created_at,
        }
    }
}

impl From<CreateNotificationTemplateDto> for NotificationTemplate {
    fn from(dto: CreateNotificationTemplateDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            notification_type: dto.notification_type,
            channel: dto.channel,
            subject_template: dto.subject_template,
            message_template: dto.message_template,
            variables: dto.variables,
            is_active: dto.is_active,
            language: dto.language,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&NotificationTemplate> for NotificationTemplateResponseDto {
    fn from(entity: &NotificationTemplate) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            notification_type: entity.notification_type.clone(),
            channel: entity.channel.clone(),
            subject_template: entity.subject_template.clone(),
            message_template: entity.message_template.clone(),
            variables: entity.variables.clone(),
            is_active: entity.is_active.clone(),
            language: entity.language.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateNotificationTemplateDto> for NotificationTemplate {
    fn from_create_dto(dto: CreateNotificationTemplateDto) -> backbone_core::ServiceResult<Self> {
        Ok(NotificationTemplate::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateNotificationTemplateDto> for NotificationTemplate {
    fn apply_update(mut self, dto: UpdateNotificationTemplateDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.notification_type = dto.notification_type;
        self.channel = dto.channel;
        self.subject_template = dto.subject_template;
        self.message_template = dto.message_template;
        self.variables = dto.variables;
        self.is_active = dto.is_active;
        self.language = dto.language;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to NotificationTemplate here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
