//! PasswordReset DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PasswordReset;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::PasswordResetStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PasswordReset
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePasswordResetDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub token: String,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub token_hash: String,
    #[cfg_attr(feature = "validation", validate(email))]
    #[cfg_attr(feature = "openapi", schema(example = "user@example.com"))]
    pub email: String,
    pub status: PasswordResetStatus,
    #[cfg_attr(feature = "validation", validate(range(min = 1), range(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub max_attempts: i32,
    #[cfg_attr(feature = "validation", validate(range(min = 0)))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub attempts_remaining: i32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_attempt_at: Option<DateTime<Utc>>,
    pub request_metadata: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verification_details_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completion_details_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub security_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_fingerprint: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 45)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verified_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub used_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub expires_at: DateTime<Utc>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PasswordReset
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePasswordResetDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub token: String,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub token_hash: String,
    #[cfg_attr(feature = "validation", validate(email))]
    #[cfg_attr(feature = "openapi", schema(example = "user@example.com"))]
    pub email: String,
    pub status: PasswordResetStatus,
    #[cfg_attr(feature = "validation", validate(range(min = 1), range(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub max_attempts: i32,
    #[cfg_attr(feature = "validation", validate(range(min = 0)))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub attempts_remaining: i32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_attempt_at: Option<DateTime<Utc>>,
    pub request_metadata: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verification_details_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completion_details_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub security_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_fingerprint: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 45)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verified_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub used_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub expires_at: DateTime<Utc>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PasswordReset
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPasswordResetDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token_hash: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "user@example.com"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<PasswordResetStatus>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_attempts: Option<i32>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attempts_remaining: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_attempt_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub request_metadata: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verification_details_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completion_details_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub security_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_fingerprint: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verified_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub used_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<DateTime<Utc>>,
}

impl PatchPasswordResetDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.user_id.is_some() || self.token.is_some() || self.token_hash.is_some() || self.email.is_some() || self.status.is_some() || self.max_attempts.is_some() || self.attempts_remaining.is_some() || self.last_attempt_at.is_some() || self.request_metadata.is_some() || self.verification_details_id.is_some() || self.completion_details_id.is_some() || self.security_id.is_some() || self.device_fingerprint.is_some() || self.ip_address.is_some() || self.user_agent.is_some() || self.verified_at.is_some() || self.used_at.is_some() || self.expires_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PasswordReset entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PasswordResetResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub token: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub token_hash: String,
    #[cfg_attr(feature = "openapi", schema(example = "user@example.com"))]
    pub email: String,
    pub status: PasswordResetStatus,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub max_attempts: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub attempts_remaining: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_attempt_at: Option<DateTime<Utc>>,
    pub request_metadata: serde_json::Value,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verification_details_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completion_details_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub security_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_fingerprint: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verified_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub used_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub expires_at: DateTime<Utc>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PasswordReset entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PasswordResetListResponseDto {
    /// List of items
    pub items: Vec<PasswordResetResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PasswordResetListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PasswordResetResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PasswordResetSummaryDto {
    pub id: Uuid,
    pub user_id: Uuid,
    pub token: String,
    pub token_hash: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PasswordReset> for PasswordResetResponseDto {
    fn from(entity: PasswordReset) -> Self {
        Self {
            id: entity.id,
            user_id: entity.user_id,
            token: entity.token,
            token_hash: entity.token_hash,
            email: entity.email,
            status: entity.status,
            max_attempts: entity.max_attempts,
            attempts_remaining: entity.attempts_remaining,
            last_attempt_at: entity.last_attempt_at,
            request_metadata: entity.request_metadata,
            verification_details_id: entity.verification_details_id,
            completion_details_id: entity.completion_details_id,
            security_id: entity.security_id,
            device_fingerprint: entity.device_fingerprint,
            ip_address: entity.ip_address,
            user_agent: entity.user_agent,
            verified_at: entity.verified_at,
            used_at: entity.used_at,
            expires_at: entity.expires_at,
            metadata: entity.metadata,
        }
    }
}

impl From<PasswordReset> for PasswordResetSummaryDto {
    fn from(entity: PasswordReset) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            user_id: entity.user_id,
            token: entity.token,
            token_hash: entity.token_hash,
            created_at,
        }
    }
}

impl From<CreatePasswordResetDto> for PasswordReset {
    fn from(dto: CreatePasswordResetDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            user_id: dto.user_id,
            token: dto.token,
            token_hash: dto.token_hash,
            email: dto.email,
            status: dto.status,
            max_attempts: dto.max_attempts,
            attempts_remaining: dto.attempts_remaining,
            last_attempt_at: dto.last_attempt_at,
            request_metadata: dto.request_metadata,
            verification_details_id: dto.verification_details_id,
            completion_details_id: dto.completion_details_id,
            security_id: dto.security_id,
            device_fingerprint: dto.device_fingerprint,
            ip_address: dto.ip_address,
            user_agent: dto.user_agent,
            verified_at: dto.verified_at,
            used_at: dto.used_at,
            expires_at: dto.expires_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PasswordReset> for PasswordResetResponseDto {
    fn from(entity: &PasswordReset) -> Self {
        Self {
            id: entity.id.clone(),
            user_id: entity.user_id.clone(),
            token: entity.token.clone(),
            token_hash: entity.token_hash.clone(),
            email: entity.email.clone(),
            status: entity.status.clone(),
            max_attempts: entity.max_attempts.clone(),
            attempts_remaining: entity.attempts_remaining.clone(),
            last_attempt_at: entity.last_attempt_at.clone(),
            request_metadata: entity.request_metadata.clone(),
            verification_details_id: entity.verification_details_id.clone(),
            completion_details_id: entity.completion_details_id.clone(),
            security_id: entity.security_id.clone(),
            device_fingerprint: entity.device_fingerprint.clone(),
            ip_address: entity.ip_address.clone(),
            user_agent: entity.user_agent.clone(),
            verified_at: entity.verified_at.clone(),
            used_at: entity.used_at.clone(),
            expires_at: entity.expires_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePasswordResetDto> for PasswordReset {
    fn from_create_dto(dto: CreatePasswordResetDto) -> backbone_core::ServiceResult<Self> {
        Ok(PasswordReset::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePasswordResetDto> for PasswordReset {
    fn apply_update(mut self, dto: UpdatePasswordResetDto) -> backbone_core::ServiceResult<Self> {
        self.user_id = dto.user_id;
        self.token = dto.token;
        self.token_hash = dto.token_hash;
        self.email = dto.email;
        self.status = dto.status;
        self.max_attempts = dto.max_attempts;
        self.attempts_remaining = dto.attempts_remaining;
        self.last_attempt_at = dto.last_attempt_at;
        self.request_metadata = dto.request_metadata;
        self.verification_details_id = dto.verification_details_id;
        self.completion_details_id = dto.completion_details_id;
        self.security_id = dto.security_id;
        self.device_fingerprint = dto.device_fingerprint;
        self.ip_address = dto.ip_address;
        self.user_agent = dto.user_agent;
        self.verified_at = dto.verified_at;
        self.used_at = dto.used_at;
        self.expires_at = dto.expires_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PasswordReset here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
