//! Specifications for BackupCode aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Entity-specific predicate structs implementing `backbone_core::Specification`.
//! Combinators (AND/OR/NOT) are available via the trait methods — no duplication.

use backbone_core::Specification;
use crate::domain::entity::BackupCode;

pub use backbone_core::{AndSpecification, OrSpecification, NotSpecification};

// ─── Entity-specific predicates ──────────────────────────────────────────────
//
// Add entity-specific predicate structs below.
// Each predicate implements `Specification<BackupCode>` and can be combined
// using `.and()`, `.or()`, `.not()` from the trait.
//
// Example:
//   let spec = ActiveSpec.and(VerifiedSpec);
//   if spec.is_satisfied_by(&entity) { ... }

// <<< CUSTOM
// Add predicate structs here. Example:
//
// pub struct ActiveBackupCodeSpec;
// impl Specification<BackupCode> for ActiveBackupCodeSpec {
//     fn is_satisfied_by(&self, e: &BackupCode) -> bool {
//         // e.is_active
//         todo!()
//     }
// }
// <<< CUSTOM SPECIFICATIONS START >>>
// Add your custom specifications here
// pub struct BackupCodeHasValidEmailSpec;
// impl BackupCodeSpecification for BackupCodeHasValidEmailSpec {
//     fn is_satisfied_by(&self, entity: &BackupCode) -> bool {
//         entity.email.contains('@')
// END CUSTOM
// END CUSTOM