//! Domain service for MFASession aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This service contains domain business logic for MFASession operations.
//! Add your custom business rules and domain operations here.

// ============================================================================
// IMPORTS - Add custom imports below
// ============================================================================

use anyhow::{Result, anyhow};

use crate::MFASession;
// <<< CUSTOM IMPORTS START >>>

// <<< CUSTOM IMPORTS START >>>
// Add your custom imports here
// <<< CUSTOM IMPORTS END >>>

// ============================================================================
// DOMAIN SERVICE
// ============================================================================

/// Domain service for MFASession business operations
///
/// This service contains:
/// - Business validation rules
/// - Domain operations that span multiple entities
/// - Complex business logic
///
/// Note: This is a stateless service. State should be in entities.
pub struct MFASessionDomainService;

impl MFASessionDomainService {
    /// Create a new domain service instance
    pub fn new() -> Self {
        Self
    }

    // =========================================================================
    // Generated Business Operations
    // =========================================================================

    /// Validate a mfa_session entity for business rules
    ///
    /// Override this method to add custom validation logic.
    pub fn validate(&self, entity: &MFASession) -> Result<()> {
        // Default validation - check required fields
        if entity.session_token.is_empty() {
            return Err(anyhow!("session_token is required"));
        }
        if entity.session_hash.is_empty() {
            return Err(anyhow!("session_hash is required"));
        }
        if entity.ip_address.is_empty() {
            return Err(anyhow!("ip_address is required"));
        }
        Ok(())
    }

    /// Check if a mfa_session can be created
    ///
    /// Add custom business rules that must be satisfied before creation.
    pub fn can_create(&self, entity: &MFASession) -> Result<bool> {
        self.validate(entity)?;
        Ok(true)
    }

    /// Check if a mfa_session can be updated
    pub fn can_update(&self, _current: &MFASession, _updated: &MFASession) -> Result<bool> {
        // Add update permission/business logic here
        Ok(true)
    }

    /// Check if a mfa_session can be deleted
    pub fn can_delete(&self, _entity: &MFASession) -> Result<bool> {
        // Add deletion permission/business logic here
        Ok(true)
    }

    // =========================================================================
    // Custom Business Operations
    // =========================================================================
    // <<< CUSTOM OPERATIONS START >>>

    // <<< CUSTOM OPERATIONS START >>>
    // Add your custom domain operations here
    // Example:
    // pub fn calculate_something(&self, entity: &MFASession) -> Result<i32> {
    //     // Business logic here
    //     Ok(0)
    // }
    // <<< CUSTOM OPERATIONS END >>>
}

impl Default for MFASessionDomainService {
    fn default() -> Self {
        Self::new()
    }
}