//! Domain policy for NotificationLog aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::NotificationLog;

/// Domain policy for NotificationLog — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<NotificationLog>` in the `// <<< CUSTOM` zone.
pub type NotificationLogDomainPolicy = PermitAllPolicy<NotificationLog>;

// <<< CUSTOM
// END CUSTOM
