//! Domain policy for RoleAssignment aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::RoleAssignment;

/// Domain policy for RoleAssignment — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<RoleAssignment>` in the `// <<< CUSTOM` zone.
pub type RoleAssignmentDomainPolicy = PermitAllPolicy<RoleAssignment>;

// <<< CUSTOM
// END CUSTOM
