//! Domain service for UserPermission aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This service contains domain business logic for UserPermission operations.
//! Add your custom business rules and domain operations here.

// ============================================================================
// IMPORTS - Add custom imports below
// ============================================================================

use anyhow::{Result, anyhow};

use crate::UserPermission;
// <<< CUSTOM IMPORTS START >>>

// <<< CUSTOM IMPORTS START >>>
// Add your custom imports here
// <<< CUSTOM IMPORTS END >>>

// ============================================================================
// DOMAIN SERVICE
// ============================================================================

/// Domain service for UserPermission business operations
///
/// This service contains:
/// - Business validation rules
/// - Domain operations that span multiple entities
/// - Complex business logic
///
/// Note: This is a stateless service. State should be in entities.
pub struct UserPermissionDomainService;

impl UserPermissionDomainService {
    /// Create a new domain service instance
    pub fn new() -> Self {
        Self
    }

    // =========================================================================
    // Generated Business Operations
    // =========================================================================

    /// Validate a user_permission entity for business rules
    ///
    /// Override this method to add custom validation logic.
    pub fn validate(&self, entity: &UserPermission) -> Result<()> {
        // Default validation - check required fields
        if entity.reason.is_empty() {
            return Err(anyhow!("reason is required"));
        }
        Ok(())
    }

    /// Check if a user_permission can be created
    ///
    /// Add custom business rules that must be satisfied before creation.
    pub fn can_create(&self, entity: &UserPermission) -> Result<bool> {
        self.validate(entity)?;
        Ok(true)
    }

    /// Check if a user_permission can be updated
    pub fn can_update(&self, _current: &UserPermission, _updated: &UserPermission) -> Result<bool> {
        // Add update permission/business logic here
        Ok(true)
    }

    /// Check if a user_permission can be deleted
    pub fn can_delete(&self, _entity: &UserPermission) -> Result<bool> {
        // Add deletion permission/business logic here
        Ok(true)
    }

    // =========================================================================
    // Custom Business Operations
    // =========================================================================
    // <<< CUSTOM OPERATIONS START >>>

    // <<< CUSTOM OPERATIONS START >>>
    // Add your custom domain operations here
    // Example:
    // pub fn calculate_something(&self, entity: &UserPermission) -> Result<i32> {
    //     // Business logic here
    //     Ok(0)
    // }
    // <<< CUSTOM OPERATIONS END >>>
}

impl Default for UserPermissionDomainService {
    fn default() -> Self {
        Self::new()
    }
}