//! Domain service for UserRole aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This service contains domain business logic for UserRole operations.
//! Add your custom business rules and domain operations here.

// ============================================================================
// IMPORTS - Add custom imports below
// ============================================================================

use anyhow::Result;

use crate::UserRole;
// <<< CUSTOM IMPORTS START >>>

// <<< CUSTOM IMPORTS START >>>
// Add your custom imports here
// <<< CUSTOM IMPORTS END >>>

// ============================================================================
// DOMAIN SERVICE
// ============================================================================

/// Domain service for UserRole business operations
///
/// This service contains:
/// - Business validation rules
/// - Domain operations that span multiple entities
/// - Complex business logic
///
/// Note: This is a stateless service. State should be in entities.
pub struct UserRoleDomainService;

impl UserRoleDomainService {
    /// Create a new domain service instance
    pub fn new() -> Self {
        Self
    }

    // =========================================================================
    // Generated Business Operations
    // =========================================================================

    /// Validate a user_role entity for business rules
    ///
    /// Override this method to add custom validation logic.
    pub fn validate(&self, _entity: &UserRole) -> Result<()> {
        // Default validation - check required fields
        Ok(())
    }

    /// Check if a user_role can be created
    ///
    /// Add custom business rules that must be satisfied before creation.
    pub fn can_create(&self, entity: &UserRole) -> Result<bool> {
        self.validate(entity)?;
        Ok(true)
    }

    /// Check if a user_role can be updated
    pub fn can_update(&self, _current: &UserRole, _updated: &UserRole) -> Result<bool> {
        // Add update permission/business logic here
        Ok(true)
    }

    /// Check if a user_role can be deleted
    pub fn can_delete(&self, _entity: &UserRole) -> Result<bool> {
        // Add deletion permission/business logic here
        Ok(true)
    }

    // =========================================================================
    // Custom Business Operations
    // =========================================================================
    // <<< CUSTOM OPERATIONS START >>>

    // <<< CUSTOM OPERATIONS START >>>
    // Add your custom domain operations here
    // Example:
    // pub fn calculate_something(&self, entity: &UserRole) -> Result<i32> {
    //     // Business logic here
    //     Ok(0)
    // }
    // <<< CUSTOM OPERATIONS END >>>
}

impl Default for UserRoleDomainService {
    fn default() -> Self {
        Self::new()
    }
}