//! Application service for RolePermission entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `role_permission_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateRolePermissionDto, UpdateRolePermissionDto};
use crate::domain::entity::RolePermission;
use crate::infrastructure::persistence::RolePermissionRepository;

/// Application service for RolePermission entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `role_permission_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct RolePermissionServiceCustom {
///     inner: Arc<RolePermissionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type RolePermissionService = GenericCrudService<
    RolePermission,
    CreateRolePermissionDto,
    UpdateRolePermissionDto,
    RolePermissionRepository,
>;

// <<< CUSTOM
// END CUSTOM
