//! Application service for SessionLimit entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `session_limit_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateSessionLimitDto, UpdateSessionLimitDto};
use crate::domain::entity::SessionLimit;
use crate::infrastructure::persistence::SessionLimitRepository;

/// Application service for SessionLimit entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `session_limit_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct SessionLimitServiceCustom {
///     inner: Arc<SessionLimitService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type SessionLimitService = GenericCrudService<
    SessionLimit,
    CreateSessionLimitDto,
    UpdateSessionLimitDto,
    SessionLimitRepository,
>;

// <<< CUSTOM
// END CUSTOM
