//! Application service for SystemSettings entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `system_settings_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateSystemSettingsDto, UpdateSystemSettingsDto};
use crate::domain::entity::SystemSettings;
use crate::infrastructure::persistence::SystemSettingsRepository;

/// Application service for SystemSettings entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `system_settings_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct SystemSettingsServiceCustom {
///     inner: Arc<SystemSettingsService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type SystemSettingsService = GenericCrudService<
    SystemSettings,
    CreateSystemSettingsDto,
    UpdateSystemSettingsDto,
    SystemSettingsRepository,
>;

// <<< CUSTOM
// END CUSTOM
