//! Commands for AuditLog aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! CQRS Commands represent intent to change state.

use async_trait::async_trait;
use anyhow::Result;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::domain::entity::AuditLog;
use crate::infrastructure::persistence::AuditLogRepository;
use super::CommandHandler;

// ============================================================================
// COMMAND TRAIT (DEPRECATED)
// ============================================================================

/// Command trait for AuditLog operations
///
/// **DEPRECATED**: Use the generic `CommandHandler<C>` trait from `mod.rs` instead.
/// This trait is kept for backwards compatibility.
#[deprecated(since = "0.2.0", note = "Use CommandHandler<C> trait instead")]
#[async_trait]
pub trait AuditLogCommand: Send + Sync {
    type Output;
    async fn execute(&self) -> Result<Self::Output>;
}

// ============================================================================
// CREATE COMMAND
// ============================================================================

/// Command to create a new audit_log
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateAuditLogCommand {
    pub user_id: Option<Uuid>,
    pub action: String,
    pub details: Option<serde_json::Value>,
    pub severity: AuditLogSeverity,
    pub ip_address: Option<String>,
    pub user_agent: Option<String>,
    pub session_id: Option<Uuid>,
    pub resource_type: Option<String>,
    pub resource_id: Option<String>,
    pub timestamp: DateTime<Utc>,
    pub archived: bool,
    pub archived_at: Option<DateTime<Utc>>,
    pub archive_location: Option<String>,
    pub metadata: serde_json::Value,
}

/// Handler for CreateAuditLogCommand
pub struct CreateAuditLogHandler<R: AuditLogRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: AuditLogRepository> CreateAuditLogHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: AuditLogRepository + 'static> CommandHandler<CreateAuditLogCommand> for CreateAuditLogHandler<R> {
    type Output = AuditLog;

    async fn handle(&self, cmd: CreateAuditLogCommand) -> Result<Self::Output> {
        let entity = AuditLog::builder()
            .id(Uuid::new_v4().to_string())
            .user_id(cmd.user_id)
            .action(cmd.action)
            .details(cmd.details)
            .severity(cmd.severity)
            .ip_address(cmd.ip_address)
            .user_agent(cmd.user_agent)
            .session_id(cmd.session_id)
            .resource_type(cmd.resource_type)
            .resource_id(cmd.resource_id)
            .timestamp(cmd.timestamp)
            .archived(cmd.archived)
            .archived_at(cmd.archived_at)
            .archive_location(cmd.archive_location)
            .metadata(cmd.metadata)
            .build()?;

        self.repository.save(&entity).await
    }
}

// ============================================================================
// UPDATE COMMAND
// ============================================================================

/// Command to update an existing audit_log
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateAuditLogCommand {
    pub id: String,
    pub user_id: Option<Uuid>,
    pub action: Option<String>,
    pub details: Option<serde_json::Value>,
    pub severity: Option<AuditLogSeverity>,
    pub ip_address: Option<String>,
    pub user_agent: Option<String>,
    pub session_id: Option<Uuid>,
    pub resource_type: Option<String>,
    pub resource_id: Option<String>,
    pub timestamp: Option<DateTime<Utc>>,
    pub archived: Option<bool>,
    pub archived_at: Option<DateTime<Utc>>,
    pub archive_location: Option<String>,
    pub metadata: Option<serde_json::Value>,
}

/// Handler for UpdateAuditLogCommand
pub struct UpdateAuditLogHandler<R: AuditLogRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: AuditLogRepository> UpdateAuditLogHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: AuditLogRepository + 'static> CommandHandler<UpdateAuditLogCommand> for UpdateAuditLogHandler<R> {
    type Output = Option<AuditLog>;

    async fn handle(&self, cmd: UpdateAuditLogCommand) -> Result<Self::Output> {
        let existing = self.repository.find_by_id(&cmd.id).await?;

        let Some(mut entity) = existing else {
            return Ok(None);
        };

        // Apply updates
        entity.user_id = cmd.user_id;
        if let Some(value) = cmd.action {
            entity.action = value;
        }
        entity.details = cmd.details;
        if let Some(value) = cmd.severity {
            entity.severity = value;
        }
        entity.ip_address = cmd.ip_address;
        entity.user_agent = cmd.user_agent;
        entity.session_id = cmd.session_id;
        entity.resource_type = cmd.resource_type;
        entity.resource_id = cmd.resource_id;
        if let Some(value) = cmd.timestamp {
            entity.timestamp = value;
        }
        if let Some(value) = cmd.archived {
            entity.archived = value;
        }
        entity.archived_at = cmd.archived_at;
        entity.archive_location = cmd.archive_location;
        if let Some(value) = cmd.metadata {
            entity.metadata = value;
        }

        self.repository.update(&cmd.id, &entity).await
    }
}

// ============================================================================
// DELETE COMMAND
// ============================================================================

/// Command to delete a audit_log
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeleteAuditLogCommand {
    pub id: String,
    pub hard_delete: bool,
}

/// Handler for DeleteAuditLogCommand
pub struct DeleteAuditLogHandler<R: AuditLogRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: AuditLogRepository> DeleteAuditLogHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: AuditLogRepository + 'static> CommandHandler<DeleteAuditLogCommand> for DeleteAuditLogHandler<R> {
    type Output = bool;

    async fn handle(&self, cmd: DeleteAuditLogCommand) -> Result<Self::Output> {
        if cmd.hard_delete {
            self.repository.delete(&cmd.id).await
        } else {
            self.repository.soft_delete(&cmd.id).await
        }
    }
}

// ============================================================================
// CUSTOM COMMANDS
// ============================================================================
// <<< CUSTOM COMMANDS START >>>

// <<< CUSTOM COMMANDS START >>>
// Add your custom commands here
// Example:
//
// #[derive(Debug, Clone, Serialize, Deserialize)]
// pub struct ActivateAuditLogCommand {
//     pub id: String,
// }
// <<< CUSTOM COMMANDS END >>>