//! Commands for EmailVerificationToken aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! CQRS Commands represent intent to change state.

use async_trait::async_trait;
use anyhow::Result;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::domain::entity::EmailVerificationToken;
use crate::infrastructure::persistence::EmailVerificationTokenRepository;
use super::CommandHandler;

// ============================================================================
// COMMAND TRAIT (DEPRECATED)
// ============================================================================

/// Command trait for EmailVerificationToken operations
///
/// **DEPRECATED**: Use the generic `CommandHandler<C>` trait from `mod.rs` instead.
/// This trait is kept for backwards compatibility.
#[deprecated(since = "0.2.0", note = "Use CommandHandler<C> trait instead")]
#[async_trait]
pub trait EmailVerificationTokenCommand: Send + Sync {
    type Output;
    async fn execute(&self) -> Result<Self::Output>;
}

// ============================================================================
// CREATE COMMAND
// ============================================================================

/// Command to create a new email_verification_token
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateEmailVerificationTokenCommand {
    pub user_id: Uuid,
    pub token: String,
    pub email: String,
    pub token_type: EmailVerificationType,
    pub old_email: Option<String>,
    pub expires_at: DateTime<Utc>,
    pub verified_at: Option<DateTime<Utc>>,
    pub attempts: i32,
    pub max_attempts: i32,
    pub status: EmailVerificationTokenStatus,
    pub ip_address: Option<String>,
    pub user_agent: Option<String>,
    pub metadata: serde_json::Value,
}

/// Handler for CreateEmailVerificationTokenCommand
pub struct CreateEmailVerificationTokenHandler<R: EmailVerificationTokenRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: EmailVerificationTokenRepository> CreateEmailVerificationTokenHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: EmailVerificationTokenRepository + 'static> CommandHandler<CreateEmailVerificationTokenCommand> for CreateEmailVerificationTokenHandler<R> {
    type Output = EmailVerificationToken;

    async fn handle(&self, cmd: CreateEmailVerificationTokenCommand) -> Result<Self::Output> {
        let entity = EmailVerificationToken::builder()
            .id(Uuid::new_v4().to_string())
            .user_id(cmd.user_id)
            .token(cmd.token)
            .email(cmd.email)
            .token_type(cmd.token_type)
            .old_email(cmd.old_email)
            .expires_at(cmd.expires_at)
            .verified_at(cmd.verified_at)
            .attempts(cmd.attempts)
            .max_attempts(cmd.max_attempts)
            .status(cmd.status)
            .ip_address(cmd.ip_address)
            .user_agent(cmd.user_agent)
            .metadata(cmd.metadata)
            .build()?;

        self.repository.save(&entity).await
    }
}

// ============================================================================
// UPDATE COMMAND
// ============================================================================

/// Command to update an existing email_verification_token
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateEmailVerificationTokenCommand {
    pub id: String,
    pub user_id: Option<Uuid>,
    pub token: Option<String>,
    pub email: Option<String>,
    pub token_type: Option<EmailVerificationType>,
    pub old_email: Option<String>,
    pub expires_at: Option<DateTime<Utc>>,
    pub verified_at: Option<DateTime<Utc>>,
    pub attempts: Option<i32>,
    pub max_attempts: Option<i32>,
    pub status: Option<EmailVerificationTokenStatus>,
    pub ip_address: Option<String>,
    pub user_agent: Option<String>,
    pub metadata: Option<serde_json::Value>,
}

/// Handler for UpdateEmailVerificationTokenCommand
pub struct UpdateEmailVerificationTokenHandler<R: EmailVerificationTokenRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: EmailVerificationTokenRepository> UpdateEmailVerificationTokenHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: EmailVerificationTokenRepository + 'static> CommandHandler<UpdateEmailVerificationTokenCommand> for UpdateEmailVerificationTokenHandler<R> {
    type Output = Option<EmailVerificationToken>;

    async fn handle(&self, cmd: UpdateEmailVerificationTokenCommand) -> Result<Self::Output> {
        let existing = self.repository.find_by_id(&cmd.id).await?;

        let Some(mut entity) = existing else {
            return Ok(None);
        };

        // Apply updates
        if let Some(value) = cmd.user_id {
            entity.user_id = value;
        }
        if let Some(value) = cmd.token {
            entity.token = value;
        }
        if let Some(value) = cmd.email {
            entity.email = value;
        }
        if let Some(value) = cmd.token_type {
            entity.token_type = value;
        }
        entity.old_email = cmd.old_email;
        if let Some(value) = cmd.expires_at {
            entity.expires_at = value;
        }
        entity.verified_at = cmd.verified_at;
        if let Some(value) = cmd.attempts {
            entity.attempts = value;
        }
        if let Some(value) = cmd.max_attempts {
            entity.max_attempts = value;
        }
        if let Some(value) = cmd.status {
            entity.status = value;
        }
        entity.ip_address = cmd.ip_address;
        entity.user_agent = cmd.user_agent;
        if let Some(value) = cmd.metadata {
            entity.metadata = value;
        }

        self.repository.update(&cmd.id, &entity).await
    }
}

// ============================================================================
// DELETE COMMAND
// ============================================================================

/// Command to delete a email_verification_token
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeleteEmailVerificationTokenCommand {
    pub id: String,
    pub hard_delete: bool,
}

/// Handler for DeleteEmailVerificationTokenCommand
pub struct DeleteEmailVerificationTokenHandler<R: EmailVerificationTokenRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: EmailVerificationTokenRepository> DeleteEmailVerificationTokenHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: EmailVerificationTokenRepository + 'static> CommandHandler<DeleteEmailVerificationTokenCommand> for DeleteEmailVerificationTokenHandler<R> {
    type Output = bool;

    async fn handle(&self, cmd: DeleteEmailVerificationTokenCommand) -> Result<Self::Output> {
        if cmd.hard_delete {
            self.repository.delete(&cmd.id).await
        } else {
            self.repository.soft_delete(&cmd.id).await
        }
    }
}

// ============================================================================
// CUSTOM COMMANDS
// ============================================================================
// <<< CUSTOM COMMANDS START >>>

// <<< CUSTOM COMMANDS START >>>
// Add your custom commands here
// Example:
//
// #[derive(Debug, Clone, Serialize, Deserialize)]
// pub struct ActivateEmailVerificationTokenCommand {
//     pub id: String,
// }
// <<< CUSTOM COMMANDS END >>>