//! Commands for Profile aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! CQRS Commands represent intent to change state.

use async_trait::async_trait;
use anyhow::Result;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::domain::entity::Profile;
use crate::infrastructure::persistence::ProfileRepository;
use super::CommandHandler;

// ============================================================================
// COMMAND TRAIT (DEPRECATED)
// ============================================================================

/// Command trait for Profile operations
///
/// **DEPRECATED**: Use the generic `CommandHandler<C>` trait from `mod.rs` instead.
/// This trait is kept for backwards compatibility.
#[deprecated(since = "0.2.0", note = "Use CommandHandler<C> trait instead")]
#[async_trait]
pub trait ProfileCommand: Send + Sync {
    type Output;
    async fn execute(&self) -> Result<Self::Output>;
}

// ============================================================================
// CREATE COMMAND
// ============================================================================

/// Command to create a new profile
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateProfileCommand {
    pub first_name: String,
    pub middle_name: Option<String>,
    pub last_name: Option<String>,
    pub dob: Option<NaiveDate>,
    pub pob: Option<String>,
    pub gender: Option<Gender>,
    pub phone_number: Option<String>,
    pub profile_picture_url: Option<String>,
    pub metadata: serde_json::Value,
}

/// Handler for CreateProfileCommand
pub struct CreateProfileHandler<R: ProfileRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: ProfileRepository> CreateProfileHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: ProfileRepository + 'static> CommandHandler<CreateProfileCommand> for CreateProfileHandler<R> {
    type Output = Profile;

    async fn handle(&self, cmd: CreateProfileCommand) -> Result<Self::Output> {
        let entity = Profile::builder()
            .id(Uuid::new_v4().to_string())
            .first_name(cmd.first_name)
            .middle_name(cmd.middle_name)
            .last_name(cmd.last_name)
            .dob(cmd.dob)
            .pob(cmd.pob)
            .gender(cmd.gender)
            .phone_number(cmd.phone_number)
            .profile_picture_url(cmd.profile_picture_url)
            .metadata(cmd.metadata)
            .build()?;

        self.repository.save(&entity).await
    }
}

// ============================================================================
// UPDATE COMMAND
// ============================================================================

/// Command to update an existing profile
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateProfileCommand {
    pub id: String,
    pub first_name: Option<String>,
    pub middle_name: Option<String>,
    pub last_name: Option<String>,
    pub dob: Option<NaiveDate>,
    pub pob: Option<String>,
    pub gender: Option<Gender>,
    pub phone_number: Option<String>,
    pub profile_picture_url: Option<String>,
    pub metadata: Option<serde_json::Value>,
}

/// Handler for UpdateProfileCommand
pub struct UpdateProfileHandler<R: ProfileRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: ProfileRepository> UpdateProfileHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: ProfileRepository + 'static> CommandHandler<UpdateProfileCommand> for UpdateProfileHandler<R> {
    type Output = Option<Profile>;

    async fn handle(&self, cmd: UpdateProfileCommand) -> Result<Self::Output> {
        let existing = self.repository.find_by_id(&cmd.id).await?;

        let Some(mut entity) = existing else {
            return Ok(None);
        };

        // Apply updates
        if let Some(value) = cmd.first_name {
            entity.first_name = value;
        }
        entity.middle_name = cmd.middle_name;
        entity.last_name = cmd.last_name;
        entity.dob = cmd.dob;
        entity.pob = cmd.pob;
        entity.gender = cmd.gender;
        entity.phone_number = cmd.phone_number;
        entity.profile_picture_url = cmd.profile_picture_url;
        if let Some(value) = cmd.metadata {
            entity.metadata = value;
        }

        self.repository.update(&cmd.id, &entity).await
    }
}

// ============================================================================
// DELETE COMMAND
// ============================================================================

/// Command to delete a profile
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeleteProfileCommand {
    pub id: String,
    pub hard_delete: bool,
}

/// Handler for DeleteProfileCommand
pub struct DeleteProfileHandler<R: ProfileRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: ProfileRepository> DeleteProfileHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: ProfileRepository + 'static> CommandHandler<DeleteProfileCommand> for DeleteProfileHandler<R> {
    type Output = bool;

    async fn handle(&self, cmd: DeleteProfileCommand) -> Result<Self::Output> {
        if cmd.hard_delete {
            self.repository.delete(&cmd.id).await
        } else {
            self.repository.soft_delete(&cmd.id).await
        }
    }
}

// ============================================================================
// CUSTOM COMMANDS
// ============================================================================
// <<< CUSTOM COMMANDS START >>>

// <<< CUSTOM COMMANDS START >>>
// Add your custom commands here
// Example:
//
// #[derive(Debug, Clone, Serialize, Deserialize)]
// pub struct ActivateProfileCommand {
//     pub id: String,
// }
// <<< CUSTOM COMMANDS END >>>