//! Commands for User aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! CQRS Commands represent intent to change state.

use async_trait::async_trait;
use anyhow::Result;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::domain::entity::User;
use crate::infrastructure::persistence::UserRepository;
use super::CommandHandler;

// ============================================================================
// COMMAND TRAIT (DEPRECATED)
// ============================================================================

/// Command trait for User operations
///
/// **DEPRECATED**: Use the generic `CommandHandler<C>` trait from `mod.rs` instead.
/// This trait is kept for backwards compatibility.
#[deprecated(since = "0.2.0", note = "Use CommandHandler<C> trait instead")]
#[async_trait]
pub trait UserCommand: Send + Sync {
    type Output;
    async fn execute(&self) -> Result<Self::Output>;
}

// ============================================================================
// CREATE COMMAND
// ============================================================================

/// Command to create a new user
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateUserCommand {
    pub username: String,
    pub email: String,
    pub password_hash: String,
    pub status: UserStatus,
    pub email_verified: bool,
    pub failed_login_attempts: i32,
    pub locked_until: Option<DateTime<Utc>>,
    pub last_login: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Handler for CreateUserCommand
pub struct CreateUserHandler<R: UserRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: UserRepository> CreateUserHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: UserRepository + 'static> CommandHandler<CreateUserCommand> for CreateUserHandler<R> {
    type Output = User;

    async fn handle(&self, cmd: CreateUserCommand) -> Result<Self::Output> {
        let entity = User::builder()
            .id(Uuid::new_v4().to_string())
            .username(cmd.username)
            .email(cmd.email)
            .password_hash(cmd.password_hash)
            .status(cmd.status)
            .email_verified(cmd.email_verified)
            .failed_login_attempts(cmd.failed_login_attempts)
            .locked_until(cmd.locked_until)
            .last_login(cmd.last_login)
            .metadata(cmd.metadata)
            .build()?;

        self.repository.save(&entity).await
    }
}

// ============================================================================
// UPDATE COMMAND
// ============================================================================

/// Command to update an existing user
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateUserCommand {
    pub id: String,
    pub username: Option<String>,
    pub email: Option<String>,
    pub password_hash: Option<String>,
    pub status: Option<UserStatus>,
    pub email_verified: Option<bool>,
    pub failed_login_attempts: Option<i32>,
    pub locked_until: Option<DateTime<Utc>>,
    pub last_login: Option<DateTime<Utc>>,
    pub metadata: Option<serde_json::Value>,
}

/// Handler for UpdateUserCommand
pub struct UpdateUserHandler<R: UserRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: UserRepository> UpdateUserHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: UserRepository + 'static> CommandHandler<UpdateUserCommand> for UpdateUserHandler<R> {
    type Output = Option<User>;

    async fn handle(&self, cmd: UpdateUserCommand) -> Result<Self::Output> {
        let existing = self.repository.find_by_id(&cmd.id).await?;

        let Some(mut entity) = existing else {
            return Ok(None);
        };

        // Apply updates
        if let Some(value) = cmd.username {
            entity.username = value;
        }
        if let Some(value) = cmd.email {
            entity.email = value;
        }
        if let Some(value) = cmd.password_hash {
            entity.password_hash = value;
        }
        if let Some(value) = cmd.status {
            entity.status = value;
        }
        if let Some(value) = cmd.email_verified {
            entity.email_verified = value;
        }
        if let Some(value) = cmd.failed_login_attempts {
            entity.failed_login_attempts = value;
        }
        entity.locked_until = cmd.locked_until;
        entity.last_login = cmd.last_login;
        if let Some(value) = cmd.metadata {
            entity.metadata = value;
        }

        self.repository.update(&cmd.id, &entity).await
    }
}

// ============================================================================
// DELETE COMMAND
// ============================================================================

/// Command to delete a user
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeleteUserCommand {
    pub id: String,
    pub hard_delete: bool,
}

/// Handler for DeleteUserCommand
pub struct DeleteUserHandler<R: UserRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: UserRepository> DeleteUserHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: UserRepository + 'static> CommandHandler<DeleteUserCommand> for DeleteUserHandler<R> {
    type Output = bool;

    async fn handle(&self, cmd: DeleteUserCommand) -> Result<Self::Output> {
        if cmd.hard_delete {
            self.repository.delete(&cmd.id).await
        } else {
            self.repository.soft_delete(&cmd.id).await
        }
    }
}

// ============================================================================
// CUSTOM COMMANDS
// ============================================================================
// <<< CUSTOM COMMANDS START >>>

// <<< CUSTOM COMMANDS START >>>
// Add your custom commands here
// Example:
//
// #[derive(Debug, Clone, Serialize, Deserialize)]
// pub struct ActivateUserCommand {
//     pub id: String,
// }
// <<< CUSTOM COMMANDS END >>>