//! Commands for WorkflowStep aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! CQRS Commands represent intent to change state.

use async_trait::async_trait;
use anyhow::Result;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::domain::entity::WorkflowStep;
use crate::infrastructure::persistence::WorkflowStepRepository;
use super::CommandHandler;

// ============================================================================
// COMMAND TRAIT (DEPRECATED)
// ============================================================================

/// Command trait for WorkflowStep operations
///
/// **DEPRECATED**: Use the generic `CommandHandler<C>` trait from `mod.rs` instead.
/// This trait is kept for backwards compatibility.
#[deprecated(since = "0.2.0", note = "Use CommandHandler<C> trait instead")]
#[async_trait]
pub trait WorkflowStepCommand: Send + Sync {
    type Output;
    async fn execute(&self) -> Result<Self::Output>;
}

// ============================================================================
// CREATE COMMAND
// ============================================================================

/// Command to create a new workflow_step
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateWorkflowStepCommand {
    pub workflow_id: Uuid,
    pub step_number: i32,
    pub step_type: WorkflowStepType,
    pub step_name: String,
    pub description: Option<String>,
    pub status: WorkflowStepStatus,
    pub parameters: Option<serde_json::Value>,
    pub result: Option<serde_json::Value>,
    pub started_at: Option<DateTime<Utc>>,
    pub completed_at: Option<DateTime<Utc>>,
    pub failed_at: Option<DateTime<Utc>>,
    pub duration_ms: Option<i32>,
    pub error_message: Option<String>,
    pub retry_count: i32,
    pub metadata: serde_json::Value,
}

/// Handler for CreateWorkflowStepCommand
pub struct CreateWorkflowStepHandler<R: WorkflowStepRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: WorkflowStepRepository> CreateWorkflowStepHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: WorkflowStepRepository + 'static> CommandHandler<CreateWorkflowStepCommand> for CreateWorkflowStepHandler<R> {
    type Output = WorkflowStep;

    async fn handle(&self, cmd: CreateWorkflowStepCommand) -> Result<Self::Output> {
        let entity = WorkflowStep::builder()
            .id(Uuid::new_v4().to_string())
            .workflow_id(cmd.workflow_id)
            .step_number(cmd.step_number)
            .step_type(cmd.step_type)
            .step_name(cmd.step_name)
            .description(cmd.description)
            .status(cmd.status)
            .parameters(cmd.parameters)
            .result(cmd.result)
            .started_at(cmd.started_at)
            .completed_at(cmd.completed_at)
            .failed_at(cmd.failed_at)
            .duration_ms(cmd.duration_ms)
            .error_message(cmd.error_message)
            .retry_count(cmd.retry_count)
            .metadata(cmd.metadata)
            .build()?;

        self.repository.save(&entity).await
    }
}

// ============================================================================
// UPDATE COMMAND
// ============================================================================

/// Command to update an existing workflow_step
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateWorkflowStepCommand {
    pub id: String,
    pub workflow_id: Option<Uuid>,
    pub step_number: Option<i32>,
    pub step_type: Option<WorkflowStepType>,
    pub step_name: Option<String>,
    pub description: Option<String>,
    pub status: Option<WorkflowStepStatus>,
    pub parameters: Option<serde_json::Value>,
    pub result: Option<serde_json::Value>,
    pub started_at: Option<DateTime<Utc>>,
    pub completed_at: Option<DateTime<Utc>>,
    pub failed_at: Option<DateTime<Utc>>,
    pub duration_ms: Option<i32>,
    pub error_message: Option<String>,
    pub retry_count: Option<i32>,
    pub metadata: Option<serde_json::Value>,
}

/// Handler for UpdateWorkflowStepCommand
pub struct UpdateWorkflowStepHandler<R: WorkflowStepRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: WorkflowStepRepository> UpdateWorkflowStepHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: WorkflowStepRepository + 'static> CommandHandler<UpdateWorkflowStepCommand> for UpdateWorkflowStepHandler<R> {
    type Output = Option<WorkflowStep>;

    async fn handle(&self, cmd: UpdateWorkflowStepCommand) -> Result<Self::Output> {
        let existing = self.repository.find_by_id(&cmd.id).await?;

        let Some(mut entity) = existing else {
            return Ok(None);
        };

        // Apply updates
        if let Some(value) = cmd.workflow_id {
            entity.workflow_id = value;
        }
        if let Some(value) = cmd.step_number {
            entity.step_number = value;
        }
        if let Some(value) = cmd.step_type {
            entity.step_type = value;
        }
        if let Some(value) = cmd.step_name {
            entity.step_name = value;
        }
        entity.description = cmd.description;
        if let Some(value) = cmd.status {
            entity.status = value;
        }
        entity.parameters = cmd.parameters;
        entity.result = cmd.result;
        entity.started_at = cmd.started_at;
        entity.completed_at = cmd.completed_at;
        entity.failed_at = cmd.failed_at;
        entity.duration_ms = cmd.duration_ms;
        entity.error_message = cmd.error_message;
        if let Some(value) = cmd.retry_count {
            entity.retry_count = value;
        }
        if let Some(value) = cmd.metadata {
            entity.metadata = value;
        }

        self.repository.update(&cmd.id, &entity).await
    }
}

// ============================================================================
// DELETE COMMAND
// ============================================================================

/// Command to delete a workflow_step
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeleteWorkflowStepCommand {
    pub id: String,
    pub hard_delete: bool,
}

/// Handler for DeleteWorkflowStepCommand
pub struct DeleteWorkflowStepHandler<R: WorkflowStepRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: WorkflowStepRepository> DeleteWorkflowStepHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: WorkflowStepRepository + 'static> CommandHandler<DeleteWorkflowStepCommand> for DeleteWorkflowStepHandler<R> {
    type Output = bool;

    async fn handle(&self, cmd: DeleteWorkflowStepCommand) -> Result<Self::Output> {
        if cmd.hard_delete {
            self.repository.delete(&cmd.id).await
        } else {
            self.repository.soft_delete(&cmd.id).await
        }
    }
}

// ============================================================================
// CUSTOM COMMANDS
// ============================================================================
// <<< CUSTOM COMMANDS START >>>

// <<< CUSTOM COMMANDS START >>>
// Add your custom commands here
// Example:
//
// #[derive(Debug, Clone, Serialize, Deserialize)]
// pub struct ActivateWorkflowStepCommand {
//     pub id: String,
// }
// <<< CUSTOM COMMANDS END >>>