//! Auth configuration for PasswordCreationContext handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This module provides:
//! - Permission definitions for CRUD operations
//! - Role-based guards
//! - Auth middleware configuration

use std::sync::Arc;

use crate::application::middleware::auth::AuthContext;
use axum::{
    extract::{Request, State},
    http::StatusCode,
    middleware::Next,
    response::Response,
};

// ==========================================================================
// Permission Constants
// ==========================================================================

/// Permission identifiers for PasswordCreationContext operations
pub mod password_creation_contexts {
    /// Permission to list password_creation_context entities
    pub const LIST: &str = "password_creation_context:list";
    /// Permission to read password_creation_context entity details
    pub const READ: &str = "password_creation_context:read";
    /// Permission to create password_creation_context entities
    pub const CREATE: &str = "password_creation_context:create";
    /// Permission to update password_creation_context entities
    pub const UPDATE: &str = "password_creation_context:update";
    /// Permission to delete password_creation_context entities
    pub const DELETE: &str = "password_creation_context:delete";
    /// Permission to restore deleted password_creation_context entities
    pub const RESTORE: &str = "password_creation_context:restore";
    /// Permission to view password_creation_context trash
    pub const TRASH: &str = "password_creation_context:trash";
    /// Permission to empty password_creation_context trash (permanent delete)
    pub const EMPTY_TRASH: &str = "password_creation_context:empty_trash";
    /// Permission to bulk create password_creation_context entities
    pub const BULK_CREATE: &str = "password_creation_context:bulk_create";
    /// Permission to upsert password_creation_context entities
    pub const UPSERT: &str = "password_creation_context:upsert";

    /// Get all permissions for this entity
    pub fn all() -> Vec<&'static str> {
        vec![
            LIST,
            READ,
            CREATE,
            UPDATE,
            DELETE,
            RESTORE,
            TRASH,
            EMPTY_TRASH,
            BULK_CREATE,
            UPSERT,
        ]
    }
}

// ==========================================================================
// Permission Checking
// ==========================================================================

/// Check if auth context has a specific permission
pub fn has_permission(auth: &AuthContext, permission: &str) -> bool {
    auth.has_permission(permission)
}

/// Check if auth context has a specific role
pub fn has_role(auth: &AuthContext, role: &str) -> bool {
    auth.has_role(role)
}

/// Check if auth context has all of the required roles
pub fn has_all_roles(auth: &AuthContext, roles: &[&str]) -> bool {
    auth.has_all_roles(roles)
}

/// Check if auth context has any of the required permissions
pub fn has_any_permission(auth: &AuthContext, permissions: &[&str]) -> bool {
    permissions.iter().any(|p| auth.has_permission(p))
}

// ==========================================================================
// Permission Guards (Axum Middleware)
// ==========================================================================

/// Note: Axum middleware should be implemented as async fn, not impl Fn
/// This avoids E0562: `impl Trait` is not allowed in the return type of `Fn` trait bounds

// ==========================================================================
// PasswordCreationContext Specific Guards
// ==========================================================================

/// Guard that requires list permission for password_creation_context
pub async fn require_list_password_creation_context(
    auth: axum::extract::Extension<AuthContext>,
    request: Request,
    next: Next,
) -> Result<Response, StatusCode> {
    if has_permission(&auth, password_creation_contexts::LIST) {
        Ok(next.run(request).await)
    } else {
        Err(StatusCode::FORBIDDEN)
    }
}

/// Guard that requires read permission for password_creation_context
pub async fn require_read_password_creation_context(
    auth: axum::extract::Extension<AuthContext>,
    request: Request,
    next: Next,
) -> Result<Response, StatusCode> {
    if has_permission(&auth, password_creation_contexts::READ) {
        Ok(next.run(request).await)
    } else {
        Err(StatusCode::FORBIDDEN)
    }
}

/// Guard that requires create permission for password_creation_context
pub async fn require_create_password_creation_context(
    auth: axum::extract::Extension<AuthContext>,
    request: Request,
    next: Next,
) -> Result<Response, StatusCode> {
    if has_permission(&auth, password_creation_contexts::CREATE) {
        Ok(next.run(request).await)
    } else {
        Err(StatusCode::FORBIDDEN)
    }
}

/// Guard that requires update permission for password_creation_context
pub async fn require_update_password_creation_context(
    auth: axum::extract::Extension<AuthContext>,
    request: Request,
    next: Next,
) -> Result<Response, StatusCode> {
    if has_permission(&auth, password_creation_contexts::UPDATE) {
        Ok(next.run(request).await)
    } else {
        Err(StatusCode::FORBIDDEN)
    }
}

/// Guard that requires delete permission for password_creation_context
pub async fn require_delete_password_creation_context(
    auth: axum::extract::Extension<AuthContext>,
    request: Request,
    next: Next,
) -> Result<Response, StatusCode> {
    if has_permission(&auth, password_creation_contexts::DELETE) {
        Ok(next.run(request).await)
    } else {
        Err(StatusCode::FORBIDDEN)
    }
}

/// Guard that requires restore permission for password_creation_context
pub async fn require_restore_password_creation_context(
    auth: axum::extract::Extension<AuthContext>,
    request: Request,
    next: Next,
) -> Result<Response, StatusCode> {
    if has_permission(&auth, password_creation_contexts::RESTORE) {
        Ok(next.run(request).await)
    } else {
        Err(StatusCode::FORBIDDEN)
    }
}

/// Guard that requires view trash permission for password_creation_context
pub async fn require_trash_password_creation_context(
    auth: axum::extract::Extension<AuthContext>,
    request: Request,
    next: Next,
) -> Result<Response, StatusCode> {
    if has_permission(&auth, password_creation_contexts::TRASH) {
        Ok(next.run(request).await)
    } else {
        Err(StatusCode::FORBIDDEN)
    }
}

/// Guard that requires empty trash permission for password_creation_context
pub async fn require_empty_trash_password_creation_context(
    auth: axum::extract::Extension<AuthContext>,
    request: Request,
    next: Next,
) -> Result<Response, StatusCode> {
    if has_permission(&auth, password_creation_contexts::EMPTY_TRASH) {
        Ok(next.run(request).await)
    } else {
        Err(StatusCode::FORBIDDEN)
    }
}

