//! Queries for DataExport aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! CQRS Queries represent requests for data without side effects.

use async_trait::async_trait;
use anyhow::Result;
use serde::{Deserialize, Serialize};

use crate::domain::entity::DataExport;
use crate::infrastructure::persistence::{DataExportRepository, PaginationParams, PaginatedResult, DataExportFilter};
use super::QueryHandler;

// ============================================================================
// QUERY TRAIT (DEPRECATED)
// ============================================================================

/// Query trait for DataExport operations
///
/// **DEPRECATED**: Use the generic `QueryHandler<Q>` trait from `mod.rs` instead.
/// This trait is kept for backwards compatibility.
#[deprecated(since = "0.2.0", note = "Use QueryHandler<Q> trait instead")]
#[async_trait]
pub trait DataExportQuery: Send + Sync {
    type Output;
    async fn execute(&self) -> Result<Self::Output>;
}

// ============================================================================
// GET BY ID QUERY
// ============================================================================

/// Query to get a data_export by ID
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetDataExportByIdQuery {
    pub id: String,
}

/// Handler for GetDataExportByIdQuery
pub struct GetDataExportByIdHandler<R: DataExportRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: DataExportRepository> GetDataExportByIdHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: DataExportRepository + 'static> QueryHandler<GetDataExportByIdQuery> for GetDataExportByIdHandler<R> {
    type Output = Option<DataExport>;

    async fn handle(&self, query: GetDataExportByIdQuery) -> Result<Self::Output> {
        self.repository.find_by_id(&query.id).await
    }
}

// ============================================================================
// LIST QUERY
// ============================================================================

/// Query to list data_export entities with pagination
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListDataExportQuery {
    pub page: u32,
    pub per_page: u32,
    pub filter_user_id: Option<Uuid>,
    pub filter_requested_by: Option<Uuid>,
    pub filter_status: Option<DataExportStatus>,
    pub filter_file_path: Option<String>,
    pub filter_file_url: Option<String>,
    pub filter_format: Option<DataExportFormat>,
    pub filter_justification: Option<String>,
}

impl Default for ListDataExportQuery {
    fn default() -> Self {
        Self {
            page: 1,
            per_page: 20,
            filter_user_id: None,
            filter_requested_by: None,
            filter_status: None,
            filter_file_path: None,
            filter_file_url: None,
            filter_format: None,
            filter_justification: None,
        }
    }
}

/// Handler for ListDataExportQuery
pub struct ListDataExportHandler<R: DataExportRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: DataExportRepository> ListDataExportHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: DataExportRepository + 'static> QueryHandler<ListDataExportQuery> for ListDataExportHandler<R> {
    type Output = PaginatedResult<DataExport>;

    async fn handle(&self, query: ListDataExportQuery) -> Result<Self::Output> {
        let params = PaginationParams::new(query.page, query.per_page);

        // Build filter from query parameters
        let filters = DataExportFilter {
            user_id: query.filter_user_id.clone(),
            requested_by: query.filter_requested_by.clone(),
            status: query.filter_status.clone(),
            file_path: query.filter_file_path.clone(),
            file_url: query.filter_file_url.clone(),
            format: query.filter_format.clone(),
            justification: query.filter_justification.clone(),
            ..Default::default()
        };

        // Use list_with_filters if any filters are set
        if filters.has_filters() {
            self.repository.list_with_filters(params, filters).await
        } else {
            self.repository.list(params).await
        }
    }
}

// ============================================================================
// CUSTOM QUERIES
// ============================================================================
// <<< CUSTOM QUERIES START >>>

// <<< CUSTOM QUERIES START >>>
// Add your custom queries here
// Example:
//
// #[derive(Debug, Clone, Serialize, Deserialize)]
// pub struct GetActiveDataExportQuery;
// <<< CUSTOM QUERIES END >>>