//! Queries for DeviceTrust aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! CQRS Queries represent requests for data without side effects.

use async_trait::async_trait;
use anyhow::Result;
use serde::{Deserialize, Serialize};

use crate::domain::entity::DeviceTrust;
use crate::infrastructure::persistence::{DeviceTrustRepository, PaginationParams, PaginatedResult, DeviceTrustFilter};
use super::QueryHandler;

// ============================================================================
// QUERY TRAIT (DEPRECATED)
// ============================================================================

/// Query trait for DeviceTrust operations
///
/// **DEPRECATED**: Use the generic `QueryHandler<Q>` trait from `mod.rs` instead.
/// This trait is kept for backwards compatibility.
#[deprecated(since = "0.2.0", note = "Use QueryHandler<Q> trait instead")]
#[async_trait]
pub trait DeviceTrustQuery: Send + Sync {
    type Output;
    async fn execute(&self) -> Result<Self::Output>;
}

// ============================================================================
// GET BY ID QUERY
// ============================================================================

/// Query to get a device_trust by ID
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetDeviceTrustByIdQuery {
    pub id: String,
}

/// Handler for GetDeviceTrustByIdQuery
pub struct GetDeviceTrustByIdHandler<R: DeviceTrustRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: DeviceTrustRepository> GetDeviceTrustByIdHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: DeviceTrustRepository + 'static> QueryHandler<GetDeviceTrustByIdQuery> for GetDeviceTrustByIdHandler<R> {
    type Output = Option<DeviceTrust>;

    async fn handle(&self, query: GetDeviceTrustByIdQuery) -> Result<Self::Output> {
        self.repository.find_by_id(&query.id).await
    }
}

// ============================================================================
// LIST QUERY
// ============================================================================

/// Query to list device_trust entities with pagination
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListDeviceTrustQuery {
    pub page: u32,
    pub per_page: u32,
    pub filter_user_id: Option<Uuid>,
    pub filter_device_fingerprint: Option<String>,
    pub filter_device_name: Option<String>,
    pub filter_device_type: Option<DeviceTrustType>,
    pub filter_trust_level: Option<TrustLevel>,
    pub filter_is_trusted: Option<bool>,
    pub filter_requires_mfa: Option<bool>,
}

impl Default for ListDeviceTrustQuery {
    fn default() -> Self {
        Self {
            page: 1,
            per_page: 20,
            filter_user_id: None,
            filter_device_fingerprint: None,
            filter_device_name: None,
            filter_device_type: None,
            filter_trust_level: None,
            filter_is_trusted: None,
            filter_requires_mfa: None,
        }
    }
}

/// Handler for ListDeviceTrustQuery
pub struct ListDeviceTrustHandler<R: DeviceTrustRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: DeviceTrustRepository> ListDeviceTrustHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: DeviceTrustRepository + 'static> QueryHandler<ListDeviceTrustQuery> for ListDeviceTrustHandler<R> {
    type Output = PaginatedResult<DeviceTrust>;

    async fn handle(&self, query: ListDeviceTrustQuery) -> Result<Self::Output> {
        let params = PaginationParams::new(query.page, query.per_page);

        // Build filter from query parameters
        let filters = DeviceTrustFilter {
            user_id: query.filter_user_id.clone(),
            device_fingerprint: query.filter_device_fingerprint.clone(),
            device_name: query.filter_device_name.clone(),
            device_type: query.filter_device_type.clone(),
            trust_level: query.filter_trust_level.clone(),
            is_trusted: query.filter_is_trusted.clone(),
            requires_mfa: query.filter_requires_mfa.clone(),
            ..Default::default()
        };

        // Use list_with_filters if any filters are set
        if filters.has_filters() {
            self.repository.list_with_filters(params, filters).await
        } else {
            self.repository.list(params).await
        }
    }
}

// ============================================================================
// FIND BY UNIQUE FIELDS
// ============================================================================

/// Query to find device_trust by device_fingerprint
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetDeviceTrustByDeviceFingerprintQuery {
    pub device_fingerprint: String,
}

/// Handler for GetDeviceTrustByDeviceFingerprintQuery
pub struct GetDeviceTrustByDeviceFingerprintHandler<R: DeviceTrustRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: DeviceTrustRepository> GetDeviceTrustByDeviceFingerprintHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: DeviceTrustRepository + 'static> QueryHandler<GetDeviceTrustByDeviceFingerprintQuery> for GetDeviceTrustByDeviceFingerprintHandler<R> {
    type Output = Option<DeviceTrust>;

    async fn handle(&self, query: GetDeviceTrustByDeviceFingerprintQuery) -> Result<Self::Output> {
        self.repository.find_by_device_fingerprint(&query.device_fingerprint).await
    }
}

// ============================================================================
// CUSTOM QUERIES
// ============================================================================
// <<< CUSTOM QUERIES START >>>

// <<< CUSTOM QUERIES START >>>
// Add your custom queries here
// Example:
//
// #[derive(Debug, Clone, Serialize, Deserialize)]
// pub struct GetActiveDeviceTrustQuery;
// <<< CUSTOM QUERIES END >>>