//! Queries for WorkflowAction aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! CQRS Queries represent requests for data without side effects.

use async_trait::async_trait;
use anyhow::Result;
use serde::{Deserialize, Serialize};

use crate::domain::entity::WorkflowAction;
use crate::infrastructure::persistence::{WorkflowActionRepository, PaginationParams, PaginatedResult, WorkflowActionFilter};
use super::QueryHandler;

// ============================================================================
// QUERY TRAIT (DEPRECATED)
// ============================================================================

/// Query trait for WorkflowAction operations
///
/// **DEPRECATED**: Use the generic `QueryHandler<Q>` trait from `mod.rs` instead.
/// This trait is kept for backwards compatibility.
#[deprecated(since = "0.2.0", note = "Use QueryHandler<Q> trait instead")]
#[async_trait]
pub trait WorkflowActionQuery: Send + Sync {
    type Output;
    async fn execute(&self) -> Result<Self::Output>;
}

// ============================================================================
// GET BY ID QUERY
// ============================================================================

/// Query to get a workflow_action by ID
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetWorkflowActionByIdQuery {
    pub id: String,
}

/// Handler for GetWorkflowActionByIdQuery
pub struct GetWorkflowActionByIdHandler<R: WorkflowActionRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: WorkflowActionRepository> GetWorkflowActionByIdHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: WorkflowActionRepository + 'static> QueryHandler<GetWorkflowActionByIdQuery> for GetWorkflowActionByIdHandler<R> {
    type Output = Option<WorkflowAction>;

    async fn handle(&self, query: GetWorkflowActionByIdQuery) -> Result<Self::Output> {
        self.repository.find_by_id(&query.id).await
    }
}

// ============================================================================
// LIST QUERY
// ============================================================================

/// Query to list workflow_action entities with pagination
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListWorkflowActionQuery {
    pub page: u32,
    pub per_page: u32,
    pub filter_workflow_definition_id: Option<Uuid>,
    pub filter_action_type: Option<ActionType>,
    pub filter_action_name: Option<String>,
    pub filter_description: Option<String>,
    pub filter_is_required: Option<bool>,
}

impl Default for ListWorkflowActionQuery {
    fn default() -> Self {
        Self {
            page: 1,
            per_page: 20,
            filter_workflow_definition_id: None,
            filter_action_type: None,
            filter_action_name: None,
            filter_description: None,
            filter_is_required: None,
        }
    }
}

/// Handler for ListWorkflowActionQuery
pub struct ListWorkflowActionHandler<R: WorkflowActionRepository> {
    repository: std::sync::Arc<R>,
}

impl<R: WorkflowActionRepository> ListWorkflowActionHandler<R> {
    pub fn new(repository: std::sync::Arc<R>) -> Self {
        Self { repository }
    }
}

#[async_trait]
impl<R: WorkflowActionRepository + 'static> QueryHandler<ListWorkflowActionQuery> for ListWorkflowActionHandler<R> {
    type Output = PaginatedResult<WorkflowAction>;

    async fn handle(&self, query: ListWorkflowActionQuery) -> Result<Self::Output> {
        let params = PaginationParams::new(query.page, query.per_page);

        // Build filter from query parameters
        let filters = WorkflowActionFilter {
            workflow_definition_id: query.filter_workflow_definition_id.clone(),
            action_type: query.filter_action_type.clone(),
            action_name: query.filter_action_name.clone(),
            description: query.filter_description.clone(),
            is_required: query.filter_is_required.clone(),
            ..Default::default()
        };

        // Use list_with_filters if any filters are set
        if filters.has_filters() {
            self.repository.list_with_filters(params, filters).await
        } else {
            self.repository.list(params).await
        }
    }
}

// ============================================================================
// CUSTOM QUERIES
// ============================================================================
// <<< CUSTOM QUERIES START >>>

// <<< CUSTOM QUERIES START >>>
// Add your custom queries here
// Example:
//
// #[derive(Debug, Clone, Serialize, Deserialize)]
// pub struct GetActiveWorkflowActionQuery;
// <<< CUSTOM QUERIES END >>>