-- BackupCode Seed Data
-- Generated by backbone-schema
--
-- This file contains initial seed data for the backup_codes table.
-- Customize this file to add your initial data.

-- INSERT INTO backup_codes (
--     id,
--     user_id,
--     batch_id,
--     code_hash,
--     code_index,
--     is_used,
--     used_at,
--     used_ip,
--     used_user_agent,
--     expires_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO backup_codes (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

