-- ImpersonationSession Seed Data
-- Generated by backbone-schema
--
-- This file contains initial seed data for the impersonation_sessions table.
-- Customize this file to add your initial data.

-- INSERT INTO impersonation_sessions (
--     id,
--     admin_id,
--     target_user_id,
--     session_id,
--     started_at,
--     ended_at,
--     max_duration_minutes,
--     reason,
--     actions_performed,
--     terminated_by,
--     termination_reason,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO impersonation_sessions (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

