-- IntegrationCredential Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the sapiens.integration_credentials table.
-- Customize this file to add your initial data.

-- INSERT INTO sapiens.integration_credentials (
--     id,
--     company_id,
--     provider,
--     account_ref,
--     purpose,
--     key_id,
--     ciphertext,
--     status,
--     expires_at,
--     rotated_from,
--     last_used_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO sapiens.integration_credentials (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

