-- NotificationTemplate Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the sapiens.notification_templates table.
-- Customize this file to add your initial data.

-- INSERT INTO sapiens.notification_templates (
--     id,
--     name,
--     notification_type,
--     channel,
--     subject_template,
--     message_template,
--     variables,
--     status,
--     language,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO sapiens.notification_templates (id, code, name, status, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', 'active', NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', 'active', NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

