-- PasswordPolicy Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the sapiens.password_policies table.
-- Customize this file to add your initial data.

-- INSERT INTO sapiens.password_policies (
--     id,
--     name,
--     organization_id,
--     status,
--     password_requirements,
--     password_history,
--     reset_settings,
--     expiry_settings,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO sapiens.password_policies (id, code, name, status, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', 'active', NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', 'active', NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

