-- User Seed Data
-- Generated by backbone-schema
--
-- This file contains initial seed data for the users table.
-- Customize this file to add your initial data.

-- INSERT INTO users (
--     id,
--     username,
--     email,
--     password_hash,
--     status,
--     email_verified,
--     failed_login_attempts,
--     locked_until,
--     last_login,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO users (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

