-- UserSettings Seed Data
-- Generated by backbone-schema
--
-- This file contains initial seed data for the user_settings table.
-- Customize this file to add your initial data.

-- INSERT INTO user_settings (
--     id,
--     user_id,
--     theme,
--     language,
--     timezone,
--     notifications_enabled,
--     email_notifications,
--     sms_notifications,
--     mfa_enabled,
--     custom_settings,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO user_settings (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

