-- WorkflowExecution Seed Data
-- Generated by backbone-schema
--
-- This file contains initial seed data for the workflow_executions table.
-- Customize this file to add your initial data.

-- INSERT INTO workflow_executions (
--     id,
--     workflow_id,
--     workflow_definition_id,
--     status,
--     current_action,
--     total_actions,
--     progress_percentage,
--     timeout_minutes,
--     started_at,
--     completed_at,
--     failed_at,
--     cancelled_at,
--     error_message,
--     execution_context,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO workflow_executions (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

