-- Migration: Create data_exports table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS data_exports (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    requested_by UUID NOT NULL,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status data_export_status NOT NULL DEFAULT 'pending',
    file_path TEXT,
    file_url TEXT,
    expires_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    record_count INTEGER,
    format data_export_format NOT NULL DEFAULT 'json',
    justification TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_data_exports_user_id_requested_at ON data_exports (user_id, requested_at);

CREATE INDEX IF NOT EXISTS idx_data_exports_requested_by_requested_at ON data_exports (requested_by, requested_at);

CREATE INDEX IF NOT EXISTS idx_data_exports_status ON data_exports (status);

CREATE INDEX IF NOT EXISTS idx_data_exports_expires_at ON data_exports (expires_at);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_data_exports_metadata_gin ON data_exports USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_data_exports_metadata_deleted_at ON data_exports ((metadata->>'deleted_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION data_exports_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS data_exports_insert_audit ON data_exports;
CREATE TRIGGER data_exports_insert_audit BEFORE INSERT ON data_exports
    FOR EACH ROW EXECUTE FUNCTION data_exports_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS data_exports_update_audit ON data_exports;
CREATE TRIGGER data_exports_update_audit BEFORE UPDATE ON data_exports
    FOR EACH ROW EXECUTE FUNCTION data_exports_audit_timestamp();

