-- Migration: Create ldap_directories table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS ldap_directories (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    display_name TEXT NOT NULL,
    host TEXT NOT NULL,
    port INTEGER NOT NULL DEFAULT 389,
    use_ssl BOOLEAN NOT NULL DEFAULT TRUE,
    use_tls BOOLEAN NOT NULL DEFAULT FALSE,
    bind_dn TEXT NOT NULL,
    bind_password TEXT NOT NULL,
    search_base TEXT NOT NULL,
    search_filter TEXT NOT NULL DEFAULT '(uid={username}))',
    attribute_mapping JSONB NOT NULL DEFAULT '{}',
    sync_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    sync_interval_minutes INTEGER,
    last_sync_at TIMESTAMPTZ,
    last_sync_result JSONB,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    status ldap_directory_status NOT NULL DEFAULT 'draft',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_ldap_directories_name ON ldap_directories (name);

CREATE INDEX IF NOT EXISTS idx_ldap_directories_is_active ON ldap_directories (is_active);

CREATE INDEX IF NOT EXISTS idx_ldap_directories_sync_enabled_last_sync_at ON ldap_directories (sync_enabled, last_sync_at);

CREATE INDEX IF NOT EXISTS idx_ldap_directories_status ON ldap_directories (status);

CREATE UNIQUE INDEX IF NOT EXISTS idx_ldap_directories_name ON ldap_directories (name);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_ldap_directories_metadata_gin ON ldap_directories USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_ldap_directories_metadata_deleted_at ON ldap_directories ((metadata->>'deleted_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION ldap_directories_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS ldap_directories_insert_audit ON ldap_directories;
CREATE TRIGGER ldap_directories_insert_audit BEFORE INSERT ON ldap_directories
    FOR EACH ROW EXECUTE FUNCTION ldap_directories_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS ldap_directories_update_audit ON ldap_directories;
CREATE TRIGGER ldap_directories_update_audit BEFORE UPDATE ON ldap_directories
    FOR EACH ROW EXECUTE FUNCTION ldap_directories_audit_timestamp();

