-- Audit Triggers Migration for sapiens module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: AnalyticsEvent (sapiens.analytics_events)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.analytics_events_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS analytics_events_insert_audit ON sapiens.analytics_events;
CREATE TRIGGER analytics_events_insert_audit BEFORE INSERT ON sapiens.analytics_events
    FOR EACH ROW EXECUTE FUNCTION sapiens.analytics_events_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS analytics_events_update_audit ON sapiens.analytics_events;
CREATE TRIGGER analytics_events_update_audit BEFORE UPDATE ON sapiens.analytics_events
    FOR EACH ROW EXECUTE FUNCTION sapiens.analytics_events_audit_timestamp();

-- ==============================================================================
-- Table: AnalyticsMetric (sapiens.analytics_metrics)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.analytics_metrics_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS analytics_metrics_insert_audit ON sapiens.analytics_metrics;
CREATE TRIGGER analytics_metrics_insert_audit BEFORE INSERT ON sapiens.analytics_metrics
    FOR EACH ROW EXECUTE FUNCTION sapiens.analytics_metrics_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS analytics_metrics_update_audit ON sapiens.analytics_metrics;
CREATE TRIGGER analytics_metrics_update_audit BEFORE UPDATE ON sapiens.analytics_metrics
    FOR EACH ROW EXECUTE FUNCTION sapiens.analytics_metrics_audit_timestamp();

-- ==============================================================================
-- Table: AnalyticsReport (sapiens.analytics_reports)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.analytics_reports_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS analytics_reports_insert_audit ON sapiens.analytics_reports;
CREATE TRIGGER analytics_reports_insert_audit BEFORE INSERT ON sapiens.analytics_reports
    FOR EACH ROW EXECUTE FUNCTION sapiens.analytics_reports_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS analytics_reports_update_audit ON sapiens.analytics_reports;
CREATE TRIGGER analytics_reports_update_audit BEFORE UPDATE ON sapiens.analytics_reports
    FOR EACH ROW EXECUTE FUNCTION sapiens.analytics_reports_audit_timestamp();

-- ==============================================================================
-- Table: AnonymizationRecord (sapiens.anonymization_records)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.anonymization_records_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS anonymization_records_insert_audit ON sapiens.anonymization_records;
CREATE TRIGGER anonymization_records_insert_audit BEFORE INSERT ON sapiens.anonymization_records
    FOR EACH ROW EXECUTE FUNCTION sapiens.anonymization_records_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS anonymization_records_update_audit ON sapiens.anonymization_records;
CREATE TRIGGER anonymization_records_update_audit BEFORE UPDATE ON sapiens.anonymization_records
    FOR EACH ROW EXECUTE FUNCTION sapiens.anonymization_records_audit_timestamp();

-- ==============================================================================
-- Table: AuditLog (sapiens.audit_logs)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.audit_logs_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS audit_logs_insert_audit ON sapiens.audit_logs;
CREATE TRIGGER audit_logs_insert_audit BEFORE INSERT ON sapiens.audit_logs
    FOR EACH ROW EXECUTE FUNCTION sapiens.audit_logs_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS audit_logs_update_audit ON sapiens.audit_logs;
CREATE TRIGGER audit_logs_update_audit BEFORE UPDATE ON sapiens.audit_logs
    FOR EACH ROW EXECUTE FUNCTION sapiens.audit_logs_audit_timestamp();

-- ==============================================================================
-- Table: BackupCode (sapiens.backup_codes)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.backup_codes_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS backup_codes_insert_audit ON sapiens.backup_codes;
CREATE TRIGGER backup_codes_insert_audit BEFORE INSERT ON sapiens.backup_codes
    FOR EACH ROW EXECUTE FUNCTION sapiens.backup_codes_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS backup_codes_update_audit ON sapiens.backup_codes;
CREATE TRIGGER backup_codes_update_audit BEFORE UPDATE ON sapiens.backup_codes
    FOR EACH ROW EXECUTE FUNCTION sapiens.backup_codes_audit_timestamp();

-- ==============================================================================
-- Table: BulkOperation (sapiens.bulk_operations)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.bulk_operations_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS bulk_operations_insert_audit ON sapiens.bulk_operations;
CREATE TRIGGER bulk_operations_insert_audit BEFORE INSERT ON sapiens.bulk_operations
    FOR EACH ROW EXECUTE FUNCTION sapiens.bulk_operations_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS bulk_operations_update_audit ON sapiens.bulk_operations;
CREATE TRIGGER bulk_operations_update_audit BEFORE UPDATE ON sapiens.bulk_operations
    FOR EACH ROW EXECUTE FUNCTION sapiens.bulk_operations_audit_timestamp();

-- ==============================================================================
-- Table: BulkOperationResult (sapiens.bulk_operation_results)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.bulk_operation_results_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS bulk_operation_results_insert_audit ON sapiens.bulk_operation_results;
CREATE TRIGGER bulk_operation_results_insert_audit BEFORE INSERT ON sapiens.bulk_operation_results
    FOR EACH ROW EXECUTE FUNCTION sapiens.bulk_operation_results_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS bulk_operation_results_update_audit ON sapiens.bulk_operation_results;
CREATE TRIGGER bulk_operation_results_update_audit BEFORE UPDATE ON sapiens.bulk_operation_results
    FOR EACH ROW EXECUTE FUNCTION sapiens.bulk_operation_results_audit_timestamp();

-- ==============================================================================
-- Table: DataExport (sapiens.data_exports)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.data_exports_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS data_exports_insert_audit ON sapiens.data_exports;
CREATE TRIGGER data_exports_insert_audit BEFORE INSERT ON sapiens.data_exports
    FOR EACH ROW EXECUTE FUNCTION sapiens.data_exports_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS data_exports_update_audit ON sapiens.data_exports;
CREATE TRIGGER data_exports_update_audit BEFORE UPDATE ON sapiens.data_exports
    FOR EACH ROW EXECUTE FUNCTION sapiens.data_exports_audit_timestamp();

-- ==============================================================================
-- Table: DeviceTrust (sapiens.device_trusts)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.device_trusts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS device_trusts_insert_audit ON sapiens.device_trusts;
CREATE TRIGGER device_trusts_insert_audit BEFORE INSERT ON sapiens.device_trusts
    FOR EACH ROW EXECUTE FUNCTION sapiens.device_trusts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS device_trusts_update_audit ON sapiens.device_trusts;
CREATE TRIGGER device_trusts_update_audit BEFORE UPDATE ON sapiens.device_trusts
    FOR EACH ROW EXECUTE FUNCTION sapiens.device_trusts_audit_timestamp();

-- ==============================================================================
-- Table: DirectPermissionGrant (sapiens.direct_permission_grants)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.direct_permission_grants_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS direct_permission_grants_insert_audit ON sapiens.direct_permission_grants;
CREATE TRIGGER direct_permission_grants_insert_audit BEFORE INSERT ON sapiens.direct_permission_grants
    FOR EACH ROW EXECUTE FUNCTION sapiens.direct_permission_grants_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS direct_permission_grants_update_audit ON sapiens.direct_permission_grants;
CREATE TRIGGER direct_permission_grants_update_audit BEFORE UPDATE ON sapiens.direct_permission_grants
    FOR EACH ROW EXECUTE FUNCTION sapiens.direct_permission_grants_audit_timestamp();

-- ==============================================================================
-- Table: EffectivePermissionCache (sapiens.effective_permission_cache)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.effective_permission_cache_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS effective_permission_cache_insert_audit ON sapiens.effective_permission_cache;
CREATE TRIGGER effective_permission_cache_insert_audit BEFORE INSERT ON sapiens.effective_permission_cache
    FOR EACH ROW EXECUTE FUNCTION sapiens.effective_permission_cache_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS effective_permission_cache_update_audit ON sapiens.effective_permission_cache;
CREATE TRIGGER effective_permission_cache_update_audit BEFORE UPDATE ON sapiens.effective_permission_cache
    FOR EACH ROW EXECUTE FUNCTION sapiens.effective_permission_cache_audit_timestamp();

-- ==============================================================================
-- Table: EmailVerificationToken (sapiens.email_verification_tokens)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.email_verification_tokens_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS email_verification_tokens_insert_audit ON sapiens.email_verification_tokens;
CREATE TRIGGER email_verification_tokens_insert_audit BEFORE INSERT ON sapiens.email_verification_tokens
    FOR EACH ROW EXECUTE FUNCTION sapiens.email_verification_tokens_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS email_verification_tokens_update_audit ON sapiens.email_verification_tokens;
CREATE TRIGGER email_verification_tokens_update_audit BEFORE UPDATE ON sapiens.email_verification_tokens
    FOR EACH ROW EXECUTE FUNCTION sapiens.email_verification_tokens_audit_timestamp();

-- ==============================================================================
-- Table: ImpersonationSession (sapiens.impersonation_sessions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.impersonation_sessions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS impersonation_sessions_insert_audit ON sapiens.impersonation_sessions;
CREATE TRIGGER impersonation_sessions_insert_audit BEFORE INSERT ON sapiens.impersonation_sessions
    FOR EACH ROW EXECUTE FUNCTION sapiens.impersonation_sessions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS impersonation_sessions_update_audit ON sapiens.impersonation_sessions;
CREATE TRIGGER impersonation_sessions_update_audit BEFORE UPDATE ON sapiens.impersonation_sessions
    FOR EACH ROW EXECUTE FUNCTION sapiens.impersonation_sessions_audit_timestamp();

-- ==============================================================================
-- Table: LDAPDirectory (sapiens.ldap_directories)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.ldap_directories_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS ldap_directories_insert_audit ON sapiens.ldap_directories;
CREATE TRIGGER ldap_directories_insert_audit BEFORE INSERT ON sapiens.ldap_directories
    FOR EACH ROW EXECUTE FUNCTION sapiens.ldap_directories_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS ldap_directories_update_audit ON sapiens.ldap_directories;
CREATE TRIGGER ldap_directories_update_audit BEFORE UPDATE ON sapiens.ldap_directories
    FOR EACH ROW EXECUTE FUNCTION sapiens.ldap_directories_audit_timestamp();

-- ==============================================================================
-- Table: MFABackupCode (sapiens.mfa_backup_codes)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.mfa_backup_codes_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mfa_backup_codes_insert_audit ON sapiens.mfa_backup_codes;
CREATE TRIGGER mfa_backup_codes_insert_audit BEFORE INSERT ON sapiens.mfa_backup_codes
    FOR EACH ROW EXECUTE FUNCTION sapiens.mfa_backup_codes_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mfa_backup_codes_update_audit ON sapiens.mfa_backup_codes;
CREATE TRIGGER mfa_backup_codes_update_audit BEFORE UPDATE ON sapiens.mfa_backup_codes
    FOR EACH ROW EXECUTE FUNCTION sapiens.mfa_backup_codes_audit_timestamp();

-- ==============================================================================
-- Table: MFADevice (sapiens.mfa_devices)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.mfa_devices_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mfa_devices_insert_audit ON sapiens.mfa_devices;
CREATE TRIGGER mfa_devices_insert_audit BEFORE INSERT ON sapiens.mfa_devices
    FOR EACH ROW EXECUTE FUNCTION sapiens.mfa_devices_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mfa_devices_update_audit ON sapiens.mfa_devices;
CREATE TRIGGER mfa_devices_update_audit BEFORE UPDATE ON sapiens.mfa_devices
    FOR EACH ROW EXECUTE FUNCTION sapiens.mfa_devices_audit_timestamp();

-- ==============================================================================
-- Table: MFASession (sapiens.mfa_sessions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.mfa_sessions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mfa_sessions_insert_audit ON sapiens.mfa_sessions;
CREATE TRIGGER mfa_sessions_insert_audit BEFORE INSERT ON sapiens.mfa_sessions
    FOR EACH ROW EXECUTE FUNCTION sapiens.mfa_sessions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mfa_sessions_update_audit ON sapiens.mfa_sessions;
CREATE TRIGGER mfa_sessions_update_audit BEFORE UPDATE ON sapiens.mfa_sessions
    FOR EACH ROW EXECUTE FUNCTION sapiens.mfa_sessions_audit_timestamp();

-- ==============================================================================
-- Table: Notification (sapiens.notifications)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.notifications_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS notifications_insert_audit ON sapiens.notifications;
CREATE TRIGGER notifications_insert_audit BEFORE INSERT ON sapiens.notifications
    FOR EACH ROW EXECUTE FUNCTION sapiens.notifications_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS notifications_update_audit ON sapiens.notifications;
CREATE TRIGGER notifications_update_audit BEFORE UPDATE ON sapiens.notifications
    FOR EACH ROW EXECUTE FUNCTION sapiens.notifications_audit_timestamp();

-- ==============================================================================
-- Table: NotificationTemplate (sapiens.notification_templates)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.notification_templates_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS notification_templates_insert_audit ON sapiens.notification_templates;
CREATE TRIGGER notification_templates_insert_audit BEFORE INSERT ON sapiens.notification_templates
    FOR EACH ROW EXECUTE FUNCTION sapiens.notification_templates_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS notification_templates_update_audit ON sapiens.notification_templates;
CREATE TRIGGER notification_templates_update_audit BEFORE UPDATE ON sapiens.notification_templates
    FOR EACH ROW EXECUTE FUNCTION sapiens.notification_templates_audit_timestamp();

-- ==============================================================================
-- Table: NotificationLog (sapiens.notification_logs)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.notification_logs_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS notification_logs_insert_audit ON sapiens.notification_logs;
CREATE TRIGGER notification_logs_insert_audit BEFORE INSERT ON sapiens.notification_logs
    FOR EACH ROW EXECUTE FUNCTION sapiens.notification_logs_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS notification_logs_update_audit ON sapiens.notification_logs;
CREATE TRIGGER notification_logs_update_audit BEFORE UPDATE ON sapiens.notification_logs
    FOR EACH ROW EXECUTE FUNCTION sapiens.notification_logs_audit_timestamp();

-- ==============================================================================
-- Table: NotificationPreference (sapiens.sapiens_notification_preferences)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.sapiens_notification_preferences_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS sapiens_notification_preferences_insert_audit ON sapiens.sapiens_notification_preferences;
CREATE TRIGGER sapiens_notification_preferences_insert_audit BEFORE INSERT ON sapiens.sapiens_notification_preferences
    FOR EACH ROW EXECUTE FUNCTION sapiens.sapiens_notification_preferences_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS sapiens_notification_preferences_update_audit ON sapiens.sapiens_notification_preferences;
CREATE TRIGGER sapiens_notification_preferences_update_audit BEFORE UPDATE ON sapiens.sapiens_notification_preferences
    FOR EACH ROW EXECUTE FUNCTION sapiens.sapiens_notification_preferences_audit_timestamp();

-- ==============================================================================
-- Table: OAuthProvider (sapiens.oauth_providers)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.oauth_providers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS oauth_providers_insert_audit ON sapiens.oauth_providers;
CREATE TRIGGER oauth_providers_insert_audit BEFORE INSERT ON sapiens.oauth_providers
    FOR EACH ROW EXECUTE FUNCTION sapiens.oauth_providers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS oauth_providers_update_audit ON sapiens.oauth_providers;
CREATE TRIGGER oauth_providers_update_audit BEFORE UPDATE ON sapiens.oauth_providers
    FOR EACH ROW EXECUTE FUNCTION sapiens.oauth_providers_audit_timestamp();

-- ==============================================================================
-- Table: UserOAuthLink (sapiens.user_oauth_links)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.user_oauth_links_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS user_oauth_links_insert_audit ON sapiens.user_oauth_links;
CREATE TRIGGER user_oauth_links_insert_audit BEFORE INSERT ON sapiens.user_oauth_links
    FOR EACH ROW EXECUTE FUNCTION sapiens.user_oauth_links_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS user_oauth_links_update_audit ON sapiens.user_oauth_links;
CREATE TRIGGER user_oauth_links_update_audit BEFORE UPDATE ON sapiens.user_oauth_links
    FOR EACH ROW EXECUTE FUNCTION sapiens.user_oauth_links_audit_timestamp();

-- ==============================================================================
-- Table: OrganizationPermission (sapiens.organization_permissions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.organization_permissions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS organization_permissions_insert_audit ON sapiens.organization_permissions;
CREATE TRIGGER organization_permissions_insert_audit BEFORE INSERT ON sapiens.organization_permissions
    FOR EACH ROW EXECUTE FUNCTION sapiens.organization_permissions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS organization_permissions_update_audit ON sapiens.organization_permissions;
CREATE TRIGGER organization_permissions_update_audit BEFORE UPDATE ON sapiens.organization_permissions
    FOR EACH ROW EXECUTE FUNCTION sapiens.organization_permissions_audit_timestamp();

-- ==============================================================================
-- Table: OrganizationRole (sapiens.organization_roles)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.organization_roles_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS organization_roles_insert_audit ON sapiens.organization_roles;
CREATE TRIGGER organization_roles_insert_audit BEFORE INSERT ON sapiens.organization_roles
    FOR EACH ROW EXECUTE FUNCTION sapiens.organization_roles_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS organization_roles_update_audit ON sapiens.organization_roles;
CREATE TRIGGER organization_roles_update_audit BEFORE UPDATE ON sapiens.organization_roles
    FOR EACH ROW EXECUTE FUNCTION sapiens.organization_roles_audit_timestamp();

-- ==============================================================================
-- Table: OrganizationUser (sapiens.organization_users)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.organization_users_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS organization_users_insert_audit ON sapiens.organization_users;
CREATE TRIGGER organization_users_insert_audit BEFORE INSERT ON sapiens.organization_users
    FOR EACH ROW EXECUTE FUNCTION sapiens.organization_users_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS organization_users_update_audit ON sapiens.organization_users;
CREATE TRIGGER organization_users_update_audit BEFORE UPDATE ON sapiens.organization_users
    FOR EACH ROW EXECUTE FUNCTION sapiens.organization_users_audit_timestamp();

-- ==============================================================================
-- Table: PasswordCreationContext (sapiens.password_creation_contexts)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.password_creation_contexts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS password_creation_contexts_insert_audit ON sapiens.password_creation_contexts;
CREATE TRIGGER password_creation_contexts_insert_audit BEFORE INSERT ON sapiens.password_creation_contexts
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_creation_contexts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS password_creation_contexts_update_audit ON sapiens.password_creation_contexts;
CREATE TRIGGER password_creation_contexts_update_audit BEFORE UPDATE ON sapiens.password_creation_contexts
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_creation_contexts_audit_timestamp();

-- ==============================================================================
-- Table: PasswordExpirationSettings (sapiens.password_expiration_settings)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.password_expiration_settings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS password_expiration_settings_insert_audit ON sapiens.password_expiration_settings;
CREATE TRIGGER password_expiration_settings_insert_audit BEFORE INSERT ON sapiens.password_expiration_settings
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_expiration_settings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS password_expiration_settings_update_audit ON sapiens.password_expiration_settings;
CREATE TRIGGER password_expiration_settings_update_audit BEFORE UPDATE ON sapiens.password_expiration_settings
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_expiration_settings_audit_timestamp();

-- ==============================================================================
-- Table: PasswordHistory (sapiens.password_history)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.password_history_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS password_history_insert_audit ON sapiens.password_history;
CREATE TRIGGER password_history_insert_audit BEFORE INSERT ON sapiens.password_history
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_history_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS password_history_update_audit ON sapiens.password_history;
CREATE TRIGGER password_history_update_audit BEFORE UPDATE ON sapiens.password_history
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_history_audit_timestamp();

-- ==============================================================================
-- Table: PasswordHistorySettings (sapiens.password_history_settings)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.password_history_settings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS password_history_settings_insert_audit ON sapiens.password_history_settings;
CREATE TRIGGER password_history_settings_insert_audit BEFORE INSERT ON sapiens.password_history_settings
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_history_settings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS password_history_settings_update_audit ON sapiens.password_history_settings;
CREATE TRIGGER password_history_settings_update_audit BEFORE UPDATE ON sapiens.password_history_settings
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_history_settings_audit_timestamp();

-- ==============================================================================
-- Table: PasswordPolicy (sapiens.password_policies)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.password_policies_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS password_policies_insert_audit ON sapiens.password_policies;
CREATE TRIGGER password_policies_insert_audit BEFORE INSERT ON sapiens.password_policies
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_policies_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS password_policies_update_audit ON sapiens.password_policies;
CREATE TRIGGER password_policies_update_audit BEFORE UPDATE ON sapiens.password_policies
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_policies_audit_timestamp();

-- ==============================================================================
-- Table: PasswordRequirements (sapiens.password_requirements)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.password_requirements_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS password_requirements_insert_audit ON sapiens.password_requirements;
CREATE TRIGGER password_requirements_insert_audit BEFORE INSERT ON sapiens.password_requirements
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_requirements_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS password_requirements_update_audit ON sapiens.password_requirements;
CREATE TRIGGER password_requirements_update_audit BEFORE UPDATE ON sapiens.password_requirements
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_requirements_audit_timestamp();

-- ==============================================================================
-- Table: PasswordReset (sapiens.password_resets)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.password_resets_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS password_resets_insert_audit ON sapiens.password_resets;
CREATE TRIGGER password_resets_insert_audit BEFORE INSERT ON sapiens.password_resets
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_resets_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS password_resets_update_audit ON sapiens.password_resets;
CREATE TRIGGER password_resets_update_audit BEFORE UPDATE ON sapiens.password_resets
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_resets_audit_timestamp();

-- ==============================================================================
-- Table: PasswordResetSecurity (sapiens.password_reset_security)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.password_reset_security_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS password_reset_security_insert_audit ON sapiens.password_reset_security;
CREATE TRIGGER password_reset_security_insert_audit BEFORE INSERT ON sapiens.password_reset_security
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_reset_security_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS password_reset_security_update_audit ON sapiens.password_reset_security;
CREATE TRIGGER password_reset_security_update_audit BEFORE UPDATE ON sapiens.password_reset_security
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_reset_security_audit_timestamp();

-- ==============================================================================
-- Table: PasswordResetToken (sapiens.password_reset_tokens)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.password_reset_tokens_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS password_reset_tokens_insert_audit ON sapiens.password_reset_tokens;
CREATE TRIGGER password_reset_tokens_insert_audit BEFORE INSERT ON sapiens.password_reset_tokens
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_reset_tokens_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS password_reset_tokens_update_audit ON sapiens.password_reset_tokens;
CREATE TRIGGER password_reset_tokens_update_audit BEFORE UPDATE ON sapiens.password_reset_tokens
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_reset_tokens_audit_timestamp();

-- ==============================================================================
-- Table: PasswordResetVerificationDetails (sapiens.password_reset_verification_details)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.password_reset_verification_details_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS password_reset_verification_details_insert_audit ON sapiens.password_reset_verification_details;
CREATE TRIGGER password_reset_verification_details_insert_audit BEFORE INSERT ON sapiens.password_reset_verification_details
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_reset_verification_details_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS password_reset_verification_details_update_audit ON sapiens.password_reset_verification_details;
CREATE TRIGGER password_reset_verification_details_update_audit BEFORE UPDATE ON sapiens.password_reset_verification_details
    FOR EACH ROW EXECUTE FUNCTION sapiens.password_reset_verification_details_audit_timestamp();

-- ==============================================================================
-- Table: Permission (permissions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION permissions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS permissions_insert_audit ON permissions;
CREATE TRIGGER permissions_insert_audit BEFORE INSERT ON permissions
    FOR EACH ROW EXECUTE FUNCTION permissions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS permissions_update_audit ON permissions;
CREATE TRIGGER permissions_update_audit BEFORE UPDATE ON permissions
    FOR EACH ROW EXECUTE FUNCTION permissions_audit_timestamp();

-- ==============================================================================
-- Table: PermissionConflict (sapiens.permission_conflicts)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.permission_conflicts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS permission_conflicts_insert_audit ON sapiens.permission_conflicts;
CREATE TRIGGER permission_conflicts_insert_audit BEFORE INSERT ON sapiens.permission_conflicts
    FOR EACH ROW EXECUTE FUNCTION sapiens.permission_conflicts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS permission_conflicts_update_audit ON sapiens.permission_conflicts;
CREATE TRIGGER permission_conflicts_update_audit BEFORE UPDATE ON sapiens.permission_conflicts
    FOR EACH ROW EXECUTE FUNCTION sapiens.permission_conflicts_audit_timestamp();

-- ==============================================================================
-- Table: ResourcePermission (sapiens.resource_permissions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.resource_permissions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS resource_permissions_insert_audit ON sapiens.resource_permissions;
CREATE TRIGGER resource_permissions_insert_audit BEFORE INSERT ON sapiens.resource_permissions
    FOR EACH ROW EXECUTE FUNCTION sapiens.resource_permissions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS resource_permissions_update_audit ON sapiens.resource_permissions;
CREATE TRIGGER resource_permissions_update_audit BEFORE UPDATE ON sapiens.resource_permissions
    FOR EACH ROW EXECUTE FUNCTION sapiens.resource_permissions_audit_timestamp();

-- ==============================================================================
-- Table: Role (roles)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION roles_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS roles_insert_audit ON roles;
CREATE TRIGGER roles_insert_audit BEFORE INSERT ON roles
    FOR EACH ROW EXECUTE FUNCTION roles_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS roles_update_audit ON roles;
CREATE TRIGGER roles_update_audit BEFORE UPDATE ON roles
    FOR EACH ROW EXECUTE FUNCTION roles_audit_timestamp();

-- ==============================================================================
-- Table: RoleAssignment (sapiens.role_assignments)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.role_assignments_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS role_assignments_insert_audit ON sapiens.role_assignments;
CREATE TRIGGER role_assignments_insert_audit BEFORE INSERT ON sapiens.role_assignments
    FOR EACH ROW EXECUTE FUNCTION sapiens.role_assignments_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS role_assignments_update_audit ON sapiens.role_assignments;
CREATE TRIGGER role_assignments_update_audit BEFORE UPDATE ON sapiens.role_assignments
    FOR EACH ROW EXECUTE FUNCTION sapiens.role_assignments_audit_timestamp();

-- ==============================================================================
-- Table: RolePermission (role_permissions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION role_permissions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS role_permissions_insert_audit ON role_permissions;
CREATE TRIGGER role_permissions_insert_audit BEFORE INSERT ON role_permissions
    FOR EACH ROW EXECUTE FUNCTION role_permissions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS role_permissions_update_audit ON role_permissions;
CREATE TRIGGER role_permissions_update_audit BEFORE UPDATE ON role_permissions
    FOR EACH ROW EXECUTE FUNCTION role_permissions_audit_timestamp();

-- ==============================================================================
-- Table: SAMLProvider (sapiens.saml_providers)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.saml_providers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS saml_providers_insert_audit ON sapiens.saml_providers;
CREATE TRIGGER saml_providers_insert_audit BEFORE INSERT ON sapiens.saml_providers
    FOR EACH ROW EXECUTE FUNCTION sapiens.saml_providers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS saml_providers_update_audit ON sapiens.saml_providers;
CREATE TRIGGER saml_providers_update_audit BEFORE UPDATE ON sapiens.saml_providers
    FOR EACH ROW EXECUTE FUNCTION sapiens.saml_providers_audit_timestamp();

-- ==============================================================================
-- Table: SecurityEvent (sapiens.security_events)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.security_events_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS security_events_insert_audit ON sapiens.security_events;
CREATE TRIGGER security_events_insert_audit BEFORE INSERT ON sapiens.security_events
    FOR EACH ROW EXECUTE FUNCTION sapiens.security_events_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS security_events_update_audit ON sapiens.security_events;
CREATE TRIGGER security_events_update_audit BEFORE UPDATE ON sapiens.security_events
    FOR EACH ROW EXECUTE FUNCTION sapiens.security_events_audit_timestamp();

-- ==============================================================================
-- Table: Session (sapiens.sessions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.sessions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS sessions_insert_audit ON sapiens.sessions;
CREATE TRIGGER sessions_insert_audit BEFORE INSERT ON sapiens.sessions
    FOR EACH ROW EXECUTE FUNCTION sapiens.sessions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS sessions_update_audit ON sapiens.sessions;
CREATE TRIGGER sessions_update_audit BEFORE UPDATE ON sapiens.sessions
    FOR EACH ROW EXECUTE FUNCTION sapiens.sessions_audit_timestamp();

-- ==============================================================================
-- Table: SessionLimit (sapiens.session_limits)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.session_limits_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS session_limits_insert_audit ON sapiens.session_limits;
CREATE TRIGGER session_limits_insert_audit BEFORE INSERT ON sapiens.session_limits
    FOR EACH ROW EXECUTE FUNCTION sapiens.session_limits_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS session_limits_update_audit ON sapiens.session_limits;
CREATE TRIGGER session_limits_update_audit BEFORE UPDATE ON sapiens.session_limits
    FOR EACH ROW EXECUTE FUNCTION sapiens.session_limits_audit_timestamp();

-- ==============================================================================
-- Table: SystemSettings (sapiens.system_settings)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.system_settings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS system_settings_insert_audit ON sapiens.system_settings;
CREATE TRIGGER system_settings_insert_audit BEFORE INSERT ON sapiens.system_settings
    FOR EACH ROW EXECUTE FUNCTION sapiens.system_settings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS system_settings_update_audit ON sapiens.system_settings;
CREATE TRIGGER system_settings_update_audit BEFORE UPDATE ON sapiens.system_settings
    FOR EACH ROW EXECUTE FUNCTION sapiens.system_settings_audit_timestamp();

-- ==============================================================================
-- Table: TemporaryPermission (sapiens.temporary_permissions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.temporary_permissions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS temporary_permissions_insert_audit ON sapiens.temporary_permissions;
CREATE TRIGGER temporary_permissions_insert_audit BEFORE INSERT ON sapiens.temporary_permissions
    FOR EACH ROW EXECUTE FUNCTION sapiens.temporary_permissions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS temporary_permissions_update_audit ON sapiens.temporary_permissions;
CREATE TRIGGER temporary_permissions_update_audit BEFORE UPDATE ON sapiens.temporary_permissions
    FOR EACH ROW EXECUTE FUNCTION sapiens.temporary_permissions_audit_timestamp();

-- ==============================================================================
-- Table: User (users)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION users_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS users_insert_audit ON users;
CREATE TRIGGER users_insert_audit BEFORE INSERT ON users
    FOR EACH ROW EXECUTE FUNCTION users_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS users_update_audit ON users;
CREATE TRIGGER users_update_audit BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION users_audit_timestamp();

-- ==============================================================================
-- Table: Profile (sapiens.profiles)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.profiles_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS profiles_insert_audit ON sapiens.profiles;
CREATE TRIGGER profiles_insert_audit BEFORE INSERT ON sapiens.profiles
    FOR EACH ROW EXECUTE FUNCTION sapiens.profiles_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS profiles_update_audit ON sapiens.profiles;
CREATE TRIGGER profiles_update_audit BEFORE UPDATE ON sapiens.profiles
    FOR EACH ROW EXECUTE FUNCTION sapiens.profiles_audit_timestamp();

-- ==============================================================================
-- Table: UserPermission (user_permissions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION user_permissions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS user_permissions_insert_audit ON user_permissions;
CREATE TRIGGER user_permissions_insert_audit BEFORE INSERT ON user_permissions
    FOR EACH ROW EXECUTE FUNCTION user_permissions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS user_permissions_update_audit ON user_permissions;
CREATE TRIGGER user_permissions_update_audit BEFORE UPDATE ON user_permissions
    FOR EACH ROW EXECUTE FUNCTION user_permissions_audit_timestamp();

-- ==============================================================================
-- Table: UserRole (user_roles)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION user_roles_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS user_roles_insert_audit ON user_roles;
CREATE TRIGGER user_roles_insert_audit BEFORE INSERT ON user_roles
    FOR EACH ROW EXECUTE FUNCTION user_roles_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS user_roles_update_audit ON user_roles;
CREATE TRIGGER user_roles_update_audit BEFORE UPDATE ON user_roles
    FOR EACH ROW EXECUTE FUNCTION user_roles_audit_timestamp();

-- ==============================================================================
-- Table: UserSAMLLink (sapiens.user_saml_links)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.user_saml_links_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS user_saml_links_insert_audit ON sapiens.user_saml_links;
CREATE TRIGGER user_saml_links_insert_audit BEFORE INSERT ON sapiens.user_saml_links
    FOR EACH ROW EXECUTE FUNCTION sapiens.user_saml_links_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS user_saml_links_update_audit ON sapiens.user_saml_links;
CREATE TRIGGER user_saml_links_update_audit BEFORE UPDATE ON sapiens.user_saml_links
    FOR EACH ROW EXECUTE FUNCTION sapiens.user_saml_links_audit_timestamp();

-- ==============================================================================
-- Table: UserSettings (sapiens.user_settings)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.user_settings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS user_settings_insert_audit ON sapiens.user_settings;
CREATE TRIGGER user_settings_insert_audit BEFORE INSERT ON sapiens.user_settings
    FOR EACH ROW EXECUTE FUNCTION sapiens.user_settings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS user_settings_update_audit ON sapiens.user_settings;
CREATE TRIGGER user_settings_update_audit BEFORE UPDATE ON sapiens.user_settings
    FOR EACH ROW EXECUTE FUNCTION sapiens.user_settings_audit_timestamp();

-- ==============================================================================
-- Table: Workflow (sapiens.workflows)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.workflows_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS workflows_insert_audit ON sapiens.workflows;
CREATE TRIGGER workflows_insert_audit BEFORE INSERT ON sapiens.workflows
    FOR EACH ROW EXECUTE FUNCTION sapiens.workflows_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS workflows_update_audit ON sapiens.workflows;
CREATE TRIGGER workflows_update_audit BEFORE UPDATE ON sapiens.workflows
    FOR EACH ROW EXECUTE FUNCTION sapiens.workflows_audit_timestamp();

-- ==============================================================================
-- Table: WorkflowStep (sapiens.workflow_steps)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.workflow_steps_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS workflow_steps_insert_audit ON sapiens.workflow_steps;
CREATE TRIGGER workflow_steps_insert_audit BEFORE INSERT ON sapiens.workflow_steps
    FOR EACH ROW EXECUTE FUNCTION sapiens.workflow_steps_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS workflow_steps_update_audit ON sapiens.workflow_steps;
CREATE TRIGGER workflow_steps_update_audit BEFORE UPDATE ON sapiens.workflow_steps
    FOR EACH ROW EXECUTE FUNCTION sapiens.workflow_steps_audit_timestamp();

-- ==============================================================================
-- Table: WorkflowDefinition (sapiens.workflow_definitions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.workflow_definitions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS workflow_definitions_insert_audit ON sapiens.workflow_definitions;
CREATE TRIGGER workflow_definitions_insert_audit BEFORE INSERT ON sapiens.workflow_definitions
    FOR EACH ROW EXECUTE FUNCTION sapiens.workflow_definitions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS workflow_definitions_update_audit ON sapiens.workflow_definitions;
CREATE TRIGGER workflow_definitions_update_audit BEFORE UPDATE ON sapiens.workflow_definitions
    FOR EACH ROW EXECUTE FUNCTION sapiens.workflow_definitions_audit_timestamp();

-- ==============================================================================
-- Table: WorkflowAction (sapiens.workflow_actions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.workflow_actions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS workflow_actions_insert_audit ON sapiens.workflow_actions;
CREATE TRIGGER workflow_actions_insert_audit BEFORE INSERT ON sapiens.workflow_actions
    FOR EACH ROW EXECUTE FUNCTION sapiens.workflow_actions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS workflow_actions_update_audit ON sapiens.workflow_actions;
CREATE TRIGGER workflow_actions_update_audit BEFORE UPDATE ON sapiens.workflow_actions
    FOR EACH ROW EXECUTE FUNCTION sapiens.workflow_actions_audit_timestamp();

-- ==============================================================================
-- Table: WorkflowExecution (sapiens.workflow_executions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.workflow_executions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS workflow_executions_insert_audit ON sapiens.workflow_executions;
CREATE TRIGGER workflow_executions_insert_audit BEFORE INSERT ON sapiens.workflow_executions
    FOR EACH ROW EXECUTE FUNCTION sapiens.workflow_executions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS workflow_executions_update_audit ON sapiens.workflow_executions;
CREATE TRIGGER workflow_executions_update_audit BEFORE UPDATE ON sapiens.workflow_executions
    FOR EACH ROW EXECUTE FUNCTION sapiens.workflow_executions_audit_timestamp();

-- ==============================================================================
-- Table: WorkflowActionExecution (sapiens.workflow_action_executions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION sapiens.workflow_action_executions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS workflow_action_executions_insert_audit ON sapiens.workflow_action_executions;
CREATE TRIGGER workflow_action_executions_insert_audit BEFORE INSERT ON sapiens.workflow_action_executions
    FOR EACH ROW EXECUTE FUNCTION sapiens.workflow_action_executions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS workflow_action_executions_update_audit ON sapiens.workflow_action_executions;
CREATE TRIGGER workflow_action_executions_update_audit BEFORE UPDATE ON sapiens.workflow_action_executions
    FOR EACH ROW EXECUTE FUNCTION sapiens.workflow_action_executions_audit_timestamp();

