-- Migration: Create security_events table
-- Generated by metaphor-schema

-- Create security_event_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'security_event_type') THEN
        CREATE TYPE security_event_type AS ENUM ('login_failed', 'suspicious_login', 'password_reused', 'account_locked', 'privilege_escalation', 'brute_force_attack', 'malicious_content', 'impersonation_started', 'impersonation_ended', 'mfa_enabled', 'mfa_disabled', 'data_exported', 'data_anonymized', 'rate_limit_exceeded', 'password_reset_request', 'password_changed');
    END IF;
END
$$;

-- Create security_event_severity enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'security_event_severity') THEN
        CREATE TYPE security_event_severity AS ENUM ('low', 'medium', 'high', 'critical');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS sapiens;

CREATE TABLE IF NOT EXISTS sapiens.security_events (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id UUID,
    session_id UUID,
    event_type security_event_type NOT NULL,
    severity security_event_severity NOT NULL,
    ip_address TEXT,
    user_agent TEXT,
    description TEXT,
    details JSONB,
    resolved BOOLEAN NOT NULL DEFAULT FALSE,
    resolved_at TIMESTAMPTZ,
    resolved_by_user_id UUID,
    resolution_notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_security_events_user_id_created_at ON sapiens.security_events (user_id, ((metadata->>'created_at')));

CREATE INDEX IF NOT EXISTS idx_security_events_event_type_created_at ON sapiens.security_events (event_type, ((metadata->>'created_at')));

CREATE INDEX IF NOT EXISTS idx_security_events_severity_resolved ON sapiens.security_events (severity, resolved);

CREATE INDEX IF NOT EXISTS idx_security_events_created_at ON sapiens.security_events (((metadata->>'created_at')));

CREATE INDEX IF NOT EXISTS idx_security_events_ip_address ON sapiens.security_events (ip_address);

CREATE INDEX IF NOT EXISTS idx_security_events_resolved_resolved_at ON sapiens.security_events (resolved, resolved_at);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_security_events_metadata_gin ON sapiens.security_events USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_security_events_metadata_deleted_at ON sapiens.security_events ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_security_events_metadata_created_at ON sapiens.security_events ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_security_events_metadata_updated_at ON sapiens.security_events ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION sapiens.security_events_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS security_events_insert_audit ON sapiens.security_events;
CREATE TRIGGER security_events_insert_audit BEFORE INSERT ON sapiens.security_events
    FOR EACH ROW EXECUTE FUNCTION sapiens.security_events_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS security_events_update_audit ON sapiens.security_events;
CREATE TRIGGER security_events_update_audit BEFORE UPDATE ON sapiens.security_events
    FOR EACH ROW EXECUTE FUNCTION sapiens.security_events_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE sapiens.security_events ADD CONSTRAINT fk_security_events_user_id FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE sapiens.security_events ADD CONSTRAINT fk_security_events_session_id FOREIGN KEY (session_id) REFERENCES sapiens.sessions (id);
