-- Migration: Create mfa_devices table
-- Generated by metaphor-schema

-- Create mfa_device_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mfa_device_type') THEN
        CREATE TYPE mfa_device_type AS ENUM ('totp', 'sms', 'email', 'hardware_key', 'biometric', 'push_notification');
    END IF;
END
$$;

-- Create enrollment_method enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enrollment_method') THEN
        CREATE TYPE enrollment_method AS ENUM ('self_service', 'admin_enforced', 'automatic', 'emergency');
    END IF;
END
$$;

-- Create mfa_device_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mfa_device_status') THEN
        CREATE TYPE mfa_device_status AS ENUM ('active', 'inactive', 'suspended', 'compromised', 'expired', 'revoked');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS sapiens;

CREATE TABLE IF NOT EXISTS sapiens.mfa_devices (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    device_type mfa_device_type NOT NULL,
    device_name TEXT,
    phone_number TEXT,
    email_address TEXT,
    totp_secret TEXT,
    secret TEXT,
    hardware_key_id TEXT,
    push_token TEXT,
    device_fingerprint TEXT,
    manufacturer TEXT,
    model TEXT,
    operating_system TEXT,
    app_version TEXT,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_backup BOOLEAN NOT NULL DEFAULT FALSE,
    requires_verification BOOLEAN NOT NULL DEFAULT TRUE,
    auto_approval_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    trusted_duration_hours INTEGER NOT NULL DEFAULT 24,
    enrolled_at TIMESTAMPTZ NOT NULL DEFAULT 'now()',
    enrolled_by UUID,
    enrollment_method enrollment_method NOT NULL DEFAULT 'self_service',
    enrollment_ip TEXT NOT NULL,
    enrollment_user_agent TEXT,
    verification_attempts INTEGER NOT NULL DEFAULT 0,
    backup_codes_generated BOOLEAN NOT NULL DEFAULT FALSE,
    verified_at TIMESTAMPTZ,
    last_used TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ,
    usage_count INTEGER NOT NULL DEFAULT 0,
    successful_verifications INTEGER NOT NULL DEFAULT 0,
    failed_verifications INTEGER NOT NULL DEFAULT 0,
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    locked_at TIMESTAMPTZ,
    locked_until TIMESTAMPTZ,
    lock_reason TEXT,
    risk_score INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    status mfa_device_status NOT NULL DEFAULT 'active',
    backup_codes_data JSONB,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_mfa_devices_user_id_status ON sapiens.mfa_devices (user_id, status);

CREATE INDEX IF NOT EXISTS idx_mfa_devices_device_type ON sapiens.mfa_devices (device_type);

CREATE INDEX IF NOT EXISTS idx_mfa_devices_is_primary_status ON sapiens.mfa_devices (is_primary, status);

CREATE INDEX IF NOT EXISTS idx_mfa_devices_enrolled_at ON sapiens.mfa_devices (enrolled_at);

CREATE INDEX IF NOT EXISTS idx_mfa_devices_last_used_at ON sapiens.mfa_devices (last_used_at);

CREATE INDEX IF NOT EXISTS idx_mfa_devices_is_locked_status ON sapiens.mfa_devices (is_locked, status);

CREATE INDEX IF NOT EXISTS idx_mfa_devices_risk_score ON sapiens.mfa_devices (risk_score);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_mfa_devices_metadata_gin ON sapiens.mfa_devices USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_mfa_devices_metadata_deleted_at ON sapiens.mfa_devices ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_mfa_devices_metadata_created_at ON sapiens.mfa_devices ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_mfa_devices_metadata_updated_at ON sapiens.mfa_devices ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION sapiens.mfa_devices_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mfa_devices_insert_audit ON sapiens.mfa_devices;
CREATE TRIGGER mfa_devices_insert_audit BEFORE INSERT ON sapiens.mfa_devices
    FOR EACH ROW EXECUTE FUNCTION sapiens.mfa_devices_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mfa_devices_update_audit ON sapiens.mfa_devices;
CREATE TRIGGER mfa_devices_update_audit BEFORE UPDATE ON sapiens.mfa_devices
    FOR EACH ROW EXECUTE FUNCTION sapiens.mfa_devices_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE sapiens.mfa_devices ADD CONSTRAINT fk_mfa_devices_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE;
