-- Migration: Create organization_permissions table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS sapiens;

CREATE TABLE IF NOT EXISTS sapiens.organization_permissions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    permission_id UUID NOT NULL,
    permission_name TEXT,
    resource_id UUID,
    resource_type TEXT,
    role_id UUID,
    granted_by UUID NOT NULL,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ,
    reason TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_organization_permissions_organization_id ON sapiens.organization_permissions (organization_id);

CREATE INDEX IF NOT EXISTS idx_organization_permissions_permission_id ON sapiens.organization_permissions (permission_id);

CREATE INDEX IF NOT EXISTS idx_organization_permissions_role_id ON sapiens.organization_permissions (role_id);

CREATE INDEX IF NOT EXISTS idx_organization_permissions_expires_at ON sapiens.organization_permissions (expires_at);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_organization_permissions_metadata_gin ON sapiens.organization_permissions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_organization_permissions_metadata_deleted_at ON sapiens.organization_permissions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_organization_permissions_metadata_created_at ON sapiens.organization_permissions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_organization_permissions_metadata_updated_at ON sapiens.organization_permissions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION sapiens.organization_permissions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS organization_permissions_insert_audit ON sapiens.organization_permissions;
CREATE TRIGGER organization_permissions_insert_audit BEFORE INSERT ON sapiens.organization_permissions
    FOR EACH ROW EXECUTE FUNCTION sapiens.organization_permissions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS organization_permissions_update_audit ON sapiens.organization_permissions;
CREATE TRIGGER organization_permissions_update_audit BEFORE UPDATE ON sapiens.organization_permissions
    FOR EACH ROW EXECUTE FUNCTION sapiens.organization_permissions_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE sapiens.organization_permissions ADD CONSTRAINT fk_organization_permissions_permission_id FOREIGN KEY (permission_id) REFERENCES permissions (id);
ALTER TABLE sapiens.organization_permissions ADD CONSTRAINT fk_organization_permissions_role_id FOREIGN KEY (role_id) REFERENCES roles (id);
