//! Domain events for DeviceTrust entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::DeviceTrust;

/// Domain events for DeviceTrust — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<DeviceTrust>)` variant.
pub type DeviceTrustEvent = CrudEvent<DeviceTrust>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for DeviceTrust events.
pub type DeviceTrustEventPublisher = Arc<dyn CrudEventPublisher<DeviceTrust> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopDeviceTrustEventPublisher = NoOpCrudEventPublisher<DeviceTrust>;
