//! Event handler trait for NotificationTemplate events
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::NotificationTemplateEvent;

/// Event handler for NotificationTemplate events.
/// Implement this trait to react to NotificationTemplate lifecycle events.
pub trait NotificationTemplateEventHandler: EventHandler<NotificationTemplateEvent> {}
