//! Domain events for PasswordHistory entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PasswordHistory;

/// Domain events for PasswordHistory — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PasswordHistory>)` variant.
pub type PasswordHistoryEvent = CrudEvent<PasswordHistory>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PasswordHistory events.
pub type PasswordHistoryEventPublisher = Arc<dyn CrudEventPublisher<PasswordHistory> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPasswordHistoryEventPublisher = NoOpCrudEventPublisher<PasswordHistory>;
