//! Event handler trait for Permission events
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PermissionEvent;

/// Event handler for Permission events.
/// Implement this trait to react to Permission lifecycle events.
pub trait PermissionEventHandler: EventHandler<PermissionEvent> {}
