//! Event handler trait for SecurityEvent events
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SecurityEventEvent;

/// Event handler for SecurityEvent events.
/// Implement this trait to react to SecurityEvent lifecycle events.
pub trait SecurityEventEventHandler: EventHandler<SecurityEventEvent> {}
