//! Domain events for Workflow entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Workflow;

/// Domain events for Workflow — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Workflow>)` variant.
pub type WorkflowEvent = CrudEvent<Workflow>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Workflow events.
pub type WorkflowEventPublisher = Arc<dyn CrudEventPublisher<Workflow> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopWorkflowEventPublisher = NoOpCrudEventPublisher<Workflow>;
