//! AnalyticsMetric seeder
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Seeds initial AnalyticsMetric data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// ANALYTICSMETRIC SEEDER
// ============================================================================

/// Seeder for analytics_metric
pub struct SeedAnalyticsMetricSeeder;

impl SeedAnalyticsMetricSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedAnalyticsMetricSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedAnalyticsMetricSeeder {
    fn name(&self) -> &'static str {
        "SeedAnalyticsMetricSeeder"
    }

    fn order(&self) -> i32 {
        57
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if analytics_metrics table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM analytics_metrics")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/analytics_metric_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM analytics_metrics")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

