//! PasswordRequirements seeder
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Seeds initial PasswordRequirements data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// PASSWORDREQUIREMENTS SEEDER
// ============================================================================

/// Seeder for password_requirements
pub struct SeedPasswordRequirementsSeeder;

impl SeedPasswordRequirementsSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedPasswordRequirementsSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedPasswordRequirementsSeeder {
    fn name(&self) -> &'static str {
        "SeedPasswordRequirementsSeeder"
    }

    fn order(&self) -> i32 {
        28
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if password_requirements table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM password_requirements")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/password_requirements_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM password_requirements")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

