//! PasswordResetSecurity seeder
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Seeds initial PasswordResetSecurity data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// PASSWORDRESETSECURITY SEEDER
// ============================================================================

/// Seeder for password_reset_security
pub struct SeedPasswordResetSecuritySeeder;

impl SeedPasswordResetSecuritySeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedPasswordResetSecuritySeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedPasswordResetSecuritySeeder {
    fn name(&self) -> &'static str {
        "SeedPasswordResetSecuritySeeder"
    }

    fn order(&self) -> i32 {
        30
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if password_reset_security table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM password_reset_security")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/password_reset_security_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM password_reset_security")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

