//! TemporaryPermission seeder
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Seeds initial TemporaryPermission data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// TEMPORARYPERMISSION SEEDER
// ============================================================================

/// Seeder for temporary_permission
pub struct SeedTemporaryPermissionSeeder;

impl SeedTemporaryPermissionSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedTemporaryPermissionSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedTemporaryPermissionSeeder {
    fn name(&self) -> &'static str {
        "SeedTemporaryPermissionSeeder"
    }

    fn order(&self) -> i32 {
        44
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if temporary_permissions table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM temporary_permissions")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/temporary_permission_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM temporary_permissions")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

