//! UserOAuthLink seeder
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Seeds initial UserOAuthLink data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// USEROAUTHLINK SEEDER
// ============================================================================

/// Seeder for user_o_auth_link
pub struct SeedUserOAuthLinkSeeder;

impl SeedUserOAuthLinkSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedUserOAuthLinkSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedUserOAuthLinkSeeder {
    fn name(&self) -> &'static str {
        "SeedUserOAuthLinkSeeder"
    }

    fn order(&self) -> i32 {
        23
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if user_oauth_links table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM user_oauth_links")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/user_o_auth_link_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM user_oauth_links")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

