//! UserRole seeder
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Seeds initial UserRole data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// USERROLE SEEDER
// ============================================================================

/// Seeder for user_role
pub struct SeedUserRoleSeeder;

impl SeedUserRoleSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedUserRoleSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedUserRoleSeeder {
    fn name(&self) -> &'static str {
        "SeedUserRoleSeeder"
    }

    fn order(&self) -> i32 {
        48
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if user_roles table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM user_roles")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/user_role_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM user_roles")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

