//! User seeder
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Seeds initial User data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// USER SEEDER
// ============================================================================

/// Seeder for user
pub struct SeedUserSeeder;

impl SeedUserSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedUserSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedUserSeeder {
    fn name(&self) -> &'static str {
        "SeedUserSeeder"
    }

    fn order(&self) -> i32 {
        45
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if users table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM users")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/user_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM users")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

