//! Repository trait for Role aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Role aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::Role;
use backbone_core::repository::{DomainPaginationParams, DomainPaginatedResult};

pub type RolePaginationParams = DomainPaginationParams;
pub type RolePaginatedResult = DomainPaginatedResult<Role>;

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RoleFilter {
    pub name: Option<String>,
    pub description: Option<String>,
    pub is_default: Option<bool>,
}

impl RoleFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.description.is_some() || self.is_default.is_some()
    }
}

/// Repository trait for Role aggregate
///
/// This trait defines the persistence contract for Role entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait RoleRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new role entity
    async fn save(&self, entity: &Role) -> Result<Role>;

    /// Find role by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Role>>;

    /// Find all role entities
    async fn find_all(&self) -> Result<Vec<Role>>;

    /// Update role by ID
    async fn update(&self, id: &str, entity: &Role) -> Result<Option<Role>>;

    /// Delete role by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List role with pagination
    async fn list(&self, params: RolePaginationParams) -> Result<RolePaginatedResult>;

    /// List role with pagination and filters
    async fn list_with_filters(&self, params: RolePaginationParams, filters: RoleFilter) -> Result<RolePaginatedResult>;

    /// Count all role entities
    async fn count(&self) -> Result<u64>;

    /// Count role entities matching filters
    async fn count_with_filters(&self, filters: RoleFilter) -> Result<u64>;

    /// Check if role exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete role by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted role by ID
    async fn restore(&self, id: &str) -> Result<Option<Role>>;

    /// List soft-deleted role entities
    async fn list_deleted(&self, params: RolePaginationParams) -> Result<RolePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Query by Unique Fields
    // =========================================================================

    /// Find role by name
    async fn find_by_name(&self, name: &str) -> Result<Option<Role>>;

    // =========================================================================
    // Existence Checks by Unique Fields
    // =========================================================================

    /// Check if role exists by name
    async fn exists_by_name(&self, name: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save role entities
    async fn bulk_save(&self, entities: &[Role]) -> Result<Vec<Role>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
