//! Repository trait for Session aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Session aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Session, DeviceType};
use backbone_core::repository::{DomainPaginationParams, DomainPaginatedResult};

pub type SessionPaginationParams = DomainPaginationParams;
pub type SessionPaginatedResult = DomainPaginatedResult<Session>;

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SessionFilter {
    pub user_id: Option<Uuid>,
    pub token_hash: Option<String>,
    pub remember_me: Option<bool>,
    pub user_agent: Option<String>,
    pub device_type: Option<DeviceType>,
    pub device_fingerprint: Option<String>,
    pub is_active: Option<bool>,
}

impl SessionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.user_id.is_some() || self.token_hash.is_some() || self.remember_me.is_some() || self.user_agent.is_some() || self.device_type.is_some() || self.device_fingerprint.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for Session aggregate
///
/// This trait defines the persistence contract for Session entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SessionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new session entity
    async fn save(&self, entity: &Session) -> Result<Session>;

    /// Find session by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Session>>;

    /// Find all session entities
    async fn find_all(&self) -> Result<Vec<Session>>;

    /// Update session by ID
    async fn update(&self, id: &str, entity: &Session) -> Result<Option<Session>>;

    /// Delete session by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List session with pagination
    async fn list(&self, params: SessionPaginationParams) -> Result<SessionPaginatedResult>;

    /// List session with pagination and filters
    async fn list_with_filters(&self, params: SessionPaginationParams, filters: SessionFilter) -> Result<SessionPaginatedResult>;

    /// Count all session entities
    async fn count(&self) -> Result<u64>;

    /// Count session entities matching filters
    async fn count_with_filters(&self, filters: SessionFilter) -> Result<u64>;

    /// Check if session exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete session by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted session by ID
    async fn restore(&self, id: &str) -> Result<Option<Session>>;

    /// List soft-deleted session entities
    async fn list_deleted(&self, params: SessionPaginationParams) -> Result<SessionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Query by Unique Fields
    // =========================================================================

    /// Find session by token_hash
    async fn find_by_token_hash(&self, token_hash: &str) -> Result<Option<Session>>;

    // =========================================================================
    // Existence Checks by Unique Fields
    // =========================================================================

    /// Check if session exists by token_hash
    async fn exists_by_token_hash(&self, token_hash: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save session entities
    async fn bulk_save(&self, entities: &[Session]) -> Result<Vec<Session>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
