//! Repository trait for UserOAuthLink aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the UserOAuthLink aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{UserOAuthLink, UserOAuthLinkStatus};
use backbone_core::repository::{DomainPaginationParams, DomainPaginatedResult};

pub type UserOAuthLinkPaginationParams = DomainPaginationParams;
pub type UserOAuthLinkPaginatedResult = DomainPaginatedResult<UserOAuthLink>;

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct UserOAuthLinkFilter {
    pub user_id: Option<Uuid>,
    pub oauth_provider_id: Option<Uuid>,
    pub provider_user_id: Option<String>,
    pub provider_email: Option<String>,
    pub provider_username: Option<String>,
    pub is_active: Option<bool>,
    pub access_token: Option<String>,
    pub refresh_token: Option<String>,
    pub is_primary: Option<bool>,
    pub link_status: Option<UserOAuthLinkStatus>,
    pub sync_enabled: Option<bool>,
}

impl UserOAuthLinkFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.user_id.is_some() || self.oauth_provider_id.is_some() || self.provider_user_id.is_some() || self.provider_email.is_some() || self.provider_username.is_some() || self.is_active.is_some() || self.access_token.is_some() || self.refresh_token.is_some() || self.is_primary.is_some() || self.link_status.is_some() || self.sync_enabled.is_some()
    }
}

/// Repository trait for UserOAuthLink aggregate
///
/// This trait defines the persistence contract for UserOAuthLink entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait UserOAuthLinkRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new user_o_auth_link entity
    async fn save(&self, entity: &UserOAuthLink) -> Result<UserOAuthLink>;

    /// Find user_o_auth_link by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<UserOAuthLink>>;

    /// Find all user_o_auth_link entities
    async fn find_all(&self) -> Result<Vec<UserOAuthLink>>;

    /// Update user_o_auth_link by ID
    async fn update(&self, id: &str, entity: &UserOAuthLink) -> Result<Option<UserOAuthLink>>;

    /// Delete user_o_auth_link by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List user_o_auth_link with pagination
    async fn list(&self, params: UserOAuthLinkPaginationParams) -> Result<UserOAuthLinkPaginatedResult>;

    /// List user_o_auth_link with pagination and filters
    async fn list_with_filters(&self, params: UserOAuthLinkPaginationParams, filters: UserOAuthLinkFilter) -> Result<UserOAuthLinkPaginatedResult>;

    /// Count all user_o_auth_link entities
    async fn count(&self) -> Result<u64>;

    /// Count user_o_auth_link entities matching filters
    async fn count_with_filters(&self, filters: UserOAuthLinkFilter) -> Result<u64>;

    /// Check if user_o_auth_link exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete user_o_auth_link by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted user_o_auth_link by ID
    async fn restore(&self, id: &str) -> Result<Option<UserOAuthLink>>;

    /// List soft-deleted user_o_auth_link entities
    async fn list_deleted(&self, params: UserOAuthLinkPaginationParams) -> Result<UserOAuthLinkPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save user_o_auth_link entities
    async fn bulk_save(&self, entities: &[UserOAuthLink]) -> Result<Vec<UserOAuthLink>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
