//! Repository for OrganizationUser entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<OrganizationUser, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::OrganizationUser;

/// Table name for OrganizationUser entities
pub const TABLE_NAME: &str = "organization_users";

/// Repository for OrganizationUser entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct OrganizationUserRepository(
    backbone_orm::GenericCrudRepository<OrganizationUser, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for OrganizationUserRepository {
    type Target = backbone_orm::GenericCrudRepository<OrganizationUser, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl OrganizationUserRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(OrganizationUserRepository, OrganizationUser, soft_delete);
