//! Repository for WorkflowAction entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<WorkflowAction, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::WorkflowAction;

/// Table name for WorkflowAction entities
pub const TABLE_NAME: &str = "workflow_actions";

/// Repository for WorkflowAction entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct WorkflowActionRepository(
    backbone_orm::GenericCrudRepository<WorkflowAction, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for WorkflowActionRepository {
    type Target = backbone_orm::GenericCrudRepository<WorkflowAction, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl WorkflowActionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(WorkflowActionRepository, WorkflowAction, soft_delete);
