//! Repository for WorkflowDefinition entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<WorkflowDefinition, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::WorkflowDefinition;

/// Table name for WorkflowDefinition entities
pub const TABLE_NAME: &str = "workflow_definitions";

/// Repository for WorkflowDefinition entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct WorkflowDefinitionRepository(
    backbone_orm::GenericCrudRepository<WorkflowDefinition, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for WorkflowDefinitionRepository {
    type Target = backbone_orm::GenericCrudRepository<WorkflowDefinition, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl WorkflowDefinitionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

impl WorkflowDefinitionRepository {
    /// Find workflow_definition by name (excludes soft-deleted)
    pub async fn find_by_name(&self, name: &str) -> Result<Option<WorkflowDefinition>> {
        self.find_by_text_field("name", name).await
    }

    /// Check if workflow_definition exists by name (excludes soft-deleted)
    pub async fn exists_by_name(&self, name: &str) -> Result<bool> {
        self.exists_by_text_field("name", name).await
    }

}

backbone_core::impl_crud_repository!(WorkflowDefinitionRepository, WorkflowDefinition, soft_delete);
