//! Validator for AnonymizationRecord entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<AnonymizationRecord>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString, RequiredUuid};
use crate::domain::entity::AnonymizationRecord;

/// Validator type alias for AnonymizationRecord entities.
pub type AnonymizationRecordValidator = EntityValidator<AnonymizationRecord>;

/// Build a validator for AnonymizationRecord with all schema-defined field rules.
pub fn anonymization_record_validator() -> AnonymizationRecordValidator {
    EntityValidator::new()
        .rule(RequiredString::new("original_email", |e: &AnonymizationRecord| &e.original_email))
        .rule(RequiredString::new("original_username", |e: &AnonymizationRecord| &e.original_username))
        .rule(RequiredString::new("reason", |e: &AnonymizationRecord| &e.reason))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
