//! Validator for RoleAssignment entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<RoleAssignment>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredUuid};
use crate::domain::entity::RoleAssignment;

/// Validator type alias for RoleAssignment entities.
pub type RoleAssignmentValidator = EntityValidator<RoleAssignment>;

/// Build a validator for RoleAssignment with all schema-defined field rules.
pub fn role_assignment_validator() -> RoleAssignmentValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("reason", |e: &RoleAssignment| e.reason.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
