//! Auth configuration for AuditLog handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<AuditLog>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::AuditLogService;
use crate::domain::entity::AuditLog;

/// Permission string constants for AuditLog operations.
pub mod permissions {
    pub const LIST:        &str = "audit_log:list";
    pub const READ:        &str = "audit_log:read";
    pub const CREATE:      &str = "audit_log:create";
    pub const UPDATE:      &str = "audit_log:update";
    pub const DELETE:      &str = "audit_log:delete";
    pub const RESTORE:     &str = "audit_log:restore";
    pub const TRASH:       &str = "audit_log:trash";
    pub const EMPTY_TRASH: &str = "audit_log:empty_trash";
    pub const BULK_CREATE: &str = "audit_log:bulk_create";
    pub const UPSERT:      &str = "audit_log:upsert";
}

/// Resource policy for AuditLog — maps CRUD actions to permission strings.
pub struct AuditLogPolicy;

#[async_trait]
impl ResourcePolicy<AuditLog> for AuditLogPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &AuditLog,
        ctx: &backbone_auth::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read   => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update => permissions::UPDATE,
            ResourceAction::Delete => permissions::DELETE,
        };
        ctx.has_permission(required)
    }
}

/// Permission guard for AuditLog handlers.
///
/// Wraps `AuditLogService` and checks `AuditLogPolicy` before delegating.
pub type AuditLogGuard = PermissionGuard<AuditLog, AuditLogService, AuditLogPolicy>;

/// Service-integrated permission guard for AuditLog (for use in generated handlers).
pub type AuditLogServiceGuard = ServicePermissionGuard<AuditLog, AuditLogService, AuditLogPolicy>;

// <<< CUSTOM
// END CUSTOM
