//! Auth configuration for PasswordResetSecurity handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<PasswordResetSecurity>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PasswordResetSecurityService;
use crate::domain::entity::PasswordResetSecurity;

/// Permission string constants for PasswordResetSecurity operations.
pub mod permissions {
    pub const LIST:        &str = "password_reset_security:list";
    pub const READ:        &str = "password_reset_security:read";
    pub const CREATE:      &str = "password_reset_security:create";
    pub const UPDATE:      &str = "password_reset_security:update";
    pub const DELETE:      &str = "password_reset_security:delete";
    pub const RESTORE:     &str = "password_reset_security:restore";
    pub const TRASH:       &str = "password_reset_security:trash";
    pub const EMPTY_TRASH: &str = "password_reset_security:empty_trash";
    pub const BULK_CREATE: &str = "password_reset_security:bulk_create";
    pub const UPSERT:      &str = "password_reset_security:upsert";
}

/// Resource policy for PasswordResetSecurity — maps CRUD actions to permission strings.
pub struct PasswordResetSecurityPolicy;

#[async_trait]
impl ResourcePolicy<PasswordResetSecurity> for PasswordResetSecurityPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &PasswordResetSecurity,
        ctx: &backbone_auth::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read   => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update => permissions::UPDATE,
            ResourceAction::Delete => permissions::DELETE,
        };
        ctx.has_permission(required)
    }
}

/// Permission guard for PasswordResetSecurity handlers.
///
/// Wraps `PasswordResetSecurityService` and checks `PasswordResetSecurityPolicy` before delegating.
pub type PasswordResetSecurityGuard = PermissionGuard<PasswordResetSecurity, PasswordResetSecurityService, PasswordResetSecurityPolicy>;

/// Service-integrated permission guard for PasswordResetSecurity (for use in generated handlers).
pub type PasswordResetSecurityServiceGuard = ServicePermissionGuard<PasswordResetSecurity, PasswordResetSecurityService, PasswordResetSecurityPolicy>;

// <<< CUSTOM
// END CUSTOM
