//! Auth configuration for SAMLProvider handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<SAMLProvider>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::SAMLProviderService;
use crate::domain::entity::SAMLProvider;

/// Permission string constants for SAMLProvider operations.
pub mod permissions {
    pub const LIST:        &str = "saml_provider:list";
    pub const READ:        &str = "saml_provider:read";
    pub const CREATE:      &str = "saml_provider:create";
    pub const UPDATE:      &str = "saml_provider:update";
    pub const DELETE:      &str = "saml_provider:delete";
    pub const RESTORE:     &str = "saml_provider:restore";
    pub const TRASH:       &str = "saml_provider:trash";
    pub const EMPTY_TRASH: &str = "saml_provider:empty_trash";
    pub const BULK_CREATE: &str = "saml_provider:bulk_create";
    pub const UPSERT:      &str = "saml_provider:upsert";
}

/// Resource policy for SAMLProvider — maps CRUD actions to permission strings.
pub struct SAMLProviderPolicy;

#[async_trait]
impl ResourcePolicy<SAMLProvider> for SAMLProviderPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &SAMLProvider,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for SAMLProvider handlers.
///
/// Wraps `SAMLProviderService` and checks `SAMLProviderPolicy` before delegating.
pub type SAMLProviderGuard = PermissionGuard<SAMLProvider>;

/// Service-integrated permission guard for SAMLProvider (for use in generated handlers).
pub type SAMLProviderServiceGuard = ServicePermissionGuard<SAMLProvider, SAMLProviderService, SAMLProviderPolicy>;

// <<< CUSTOM
// END CUSTOM
