//! PasswordHistory Projection (Read Model)
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This is a CQRS projection - an optimized read model for queries.
//! It is updated asynchronously from domain events.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

// ============================================================================
// PROJECTION (READ MODEL)
// ============================================================================

/// PasswordHistory read model optimized for queries
///
/// This projection is denormalized for fast reads.
/// It is updated when domain events are published.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct PasswordHistoryProjection {
    pub id: Uuid,
    pub user_id: Uuid,
    pub password_hash: String,
    pub password_strength: serde_json::Value,
    pub password_metadata: serde_json::Value,
    pub creation_context: serde_json::Value,
    pub status: PasswordHistoryStatus,
    pub usage: serde_json::Value,
    pub expiry: Option<serde_json::Value>,
    pub metadata: serde_json::Value,

    // Projection metadata
    /// Version of the projection (for optimistic locking)
    pub projection_version: i64,
    /// Last event sequence number applied
    pub last_event_sequence: i64,
    /// When this projection was last updated
    pub projection_updated_at: DateTime<Utc>,
}

impl PasswordHistoryProjection {
    /// Create a new projection from entity data
    pub fn new(
        id: Uuid,
        user_id: Uuid,
        password_hash: String,
        password_strength: serde_json::Value,
        password_metadata: serde_json::Value,
        creation_context: serde_json::Value,
        status: PasswordHistoryStatus,
        usage: serde_json::Value,
        expiry: Option<serde_json::Value>,
        metadata: serde_json::Value
    ) -> Self {
        Self {
            id,
            user_id,
            password_hash,
            password_strength,
            password_metadata,
            creation_context,
            status,
            usage,
            expiry,
            metadata,
            projection_version: 1,
            last_event_sequence: 0,
            projection_updated_at: Utc::now(),
        }
    }

    /// Get the projection ID
    pub fn id(&self) -> &Uuid {
        &self.id
    }

    /// Update projection version after applying event
    pub fn apply_event(&mut self, event_sequence: i64) {
        self.projection_version += 1;
        self.last_event_sequence = event_sequence;
        self.projection_updated_at = Utc::now();
    }
}

// ============================================================================
// SUMMARY PROJECTION (LIST VIEW)
// ============================================================================

/// Summary view of PasswordHistory for list displays
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct PasswordHistorySummary {
    pub id: Uuid,
    pub status: PasswordHistoryStatus,
}

// ============================================================================
// CUSTOM PROJECTIONS
// ============================================================================
// <<< CUSTOM PROJECTIONS START >>>

// <<< CUSTOM PROJECTIONS START >>>
// Add custom read models here for specific query use cases
// Example:
//
// #[derive(Debug, Clone, Serialize, Deserialize)]
// pub struct PasswordHistoryDashboard {
//     pub id: Uuid,
//     pub key_metric: i64,
// }
// <<< CUSTOM PROJECTIONS END >>>