//! SAMLProvider Projection (Read Model)
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This is a CQRS projection - an optimized read model for queries.
//! It is updated asynchronously from domain events.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

// ============================================================================
// PROJECTION (READ MODEL)
// ============================================================================

/// SAMLProvider read model optimized for queries
///
/// This projection is denormalized for fast reads.
/// It is updated when domain events are published.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct SAMLProviderProjection {
    pub id: Uuid,
    pub name: String,
    pub display_name: String,
    pub entity_id: String,
    pub sso_url: String,
    pub slo_url: Option<String>,
    pub certificate: String,
    pub acs_url: String,
    pub sls_url: Option<String>,
    pub name_id_format: String,
    pub attribute_mapping: serde_json::Value,
    pub is_active: bool,
    pub status: SAMLProviderStatus,
    pub metadata: serde_json::Value,

    // Projection metadata
    /// Version of the projection (for optimistic locking)
    pub projection_version: i64,
    /// Last event sequence number applied
    pub last_event_sequence: i64,
    /// When this projection was last updated
    pub projection_updated_at: DateTime<Utc>,
}

impl SAMLProviderProjection {
    /// Create a new projection from entity data
    pub fn new(
        id: Uuid,
        name: String,
        display_name: String,
        entity_id: String,
        sso_url: String,
        slo_url: Option<String>,
        certificate: String,
        acs_url: String,
        sls_url: Option<String>,
        name_id_format: String,
        attribute_mapping: serde_json::Value,
        is_active: bool,
        status: SAMLProviderStatus,
        metadata: serde_json::Value
    ) -> Self {
        Self {
            id,
            name,
            display_name,
            entity_id,
            sso_url,
            slo_url,
            certificate,
            acs_url,
            sls_url,
            name_id_format,
            attribute_mapping,
            is_active,
            status,
            metadata,
            projection_version: 1,
            last_event_sequence: 0,
            projection_updated_at: Utc::now(),
        }
    }

    /// Get the projection ID
    pub fn id(&self) -> &Uuid {
        &self.id
    }

    /// Update projection version after applying event
    pub fn apply_event(&mut self, event_sequence: i64) {
        self.projection_version += 1;
        self.last_event_sequence = event_sequence;
        self.projection_updated_at = Utc::now();
    }
}

// ============================================================================
// SUMMARY PROJECTION (LIST VIEW)
// ============================================================================

/// Summary view of SAMLProvider for list displays
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct SAMLProviderSummary {
    pub id: Uuid,
    pub name: String,
    pub display_name: String,
    pub status: SAMLProviderStatus,
}

// ============================================================================
// CUSTOM PROJECTIONS
// ============================================================================
// <<< CUSTOM PROJECTIONS START >>>

// <<< CUSTOM PROJECTIONS START >>>
// Add custom read models here for specific query use cases
// Example:
//
// #[derive(Debug, Clone, Serialize, Deserialize)]
// pub struct SAMLProviderDashboard {
//     pub id: Uuid,
//     pub key_metric: i64,
// }
// <<< CUSTOM PROJECTIONS END >>>