//! Workflow Projection (Read Model)
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This is a CQRS projection - an optimized read model for queries.
//! It is updated asynchronously from domain events.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

// ============================================================================
// PROJECTION (READ MODEL)
// ============================================================================

/// Workflow read model optimized for queries
///
/// This projection is denormalized for fast reads.
/// It is updated when domain events are published.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct WorkflowProjection {
    pub id: Uuid,
    pub workflow_type: WorkflowType,
    pub status: WorkflowStatus,
    pub initiator_id: Uuid,
    pub target_user_id: Option<Uuid>,
    pub title: String,
    pub description: Option<String>,
    pub context: Option<serde_json::Value>,
    pub current_step: i32,
    pub total_steps: i32,
    pub progress_percentage: f64,
    pub started_at: Option<DateTime<Utc>>,
    pub completed_at: Option<DateTime<Utc>>,
    pub failed_at: Option<DateTime<Utc>>,
    pub expires_at: Option<DateTime<Utc>>,
    pub retry_count: i32,
    pub max_retries: i32,
    pub error_message: Option<String>,
    pub metadata: serde_json::Value,

    // Projection metadata
    /// Version of the projection (for optimistic locking)
    pub projection_version: i64,
    /// Last event sequence number applied
    pub last_event_sequence: i64,
    /// When this projection was last updated
    pub projection_updated_at: DateTime<Utc>,
}

impl WorkflowProjection {
    /// Create a new projection from entity data
    pub fn new(
        id: Uuid,
        workflow_type: WorkflowType,
        status: WorkflowStatus,
        initiator_id: Uuid,
        target_user_id: Option<Uuid>,
        title: String,
        description: Option<String>,
        context: Option<serde_json::Value>,
        current_step: i32,
        total_steps: i32,
        progress_percentage: f64,
        started_at: Option<DateTime<Utc>>,
        completed_at: Option<DateTime<Utc>>,
        failed_at: Option<DateTime<Utc>>,
        expires_at: Option<DateTime<Utc>>,
        retry_count: i32,
        max_retries: i32,
        error_message: Option<String>,
        metadata: serde_json::Value
    ) -> Self {
        Self {
            id,
            workflow_type,
            status,
            initiator_id,
            target_user_id,
            title,
            description,
            context,
            current_step,
            total_steps,
            progress_percentage,
            started_at,
            completed_at,
            failed_at,
            expires_at,
            retry_count,
            max_retries,
            error_message,
            metadata,
            projection_version: 1,
            last_event_sequence: 0,
            projection_updated_at: Utc::now(),
        }
    }

    /// Get the projection ID
    pub fn id(&self) -> &Uuid {
        &self.id
    }

    /// Update projection version after applying event
    pub fn apply_event(&mut self, event_sequence: i64) {
        self.projection_version += 1;
        self.last_event_sequence = event_sequence;
        self.projection_updated_at = Utc::now();
    }
}

// ============================================================================
// SUMMARY PROJECTION (LIST VIEW)
// ============================================================================

/// Summary view of Workflow for list displays
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct WorkflowSummary {
    pub id: Uuid,
    pub status: WorkflowStatus,
    pub title: String,
}

// ============================================================================
// CUSTOM PROJECTIONS
// ============================================================================
// <<< CUSTOM PROJECTIONS START >>>

// <<< CUSTOM PROJECTIONS START >>>
// Add custom read models here for specific query use cases
// Example:
//
// #[derive(Debug, Clone, Serialize, Deserialize)]
// pub struct WorkflowDashboard {
//     pub id: Uuid,
//     pub key_metric: i64,
// }
// <<< CUSTOM PROJECTIONS END >>>