//! TemporaryPermissionGrant flow implementation
//!
//! Generated by metaphor-schema
//!
//! Temporary permission grant workflow:
//! - Validate duration (max 30 days)
//! - Check for duplicate grants
//! - Create time-bound permission
//! - Monitor for expiration
//! - Notify before expiry (24 hours)
//! - Auto-revoke on expiration

use serde::{Deserialize, Serialize};
use std::sync::Arc;
use chrono;
use backbone_core::flow::{WorkflowStep, WorkflowContext};

/// Error type for flow execution
#[derive(Debug, Clone, thiserror::Error)]
pub enum FlowError {
    #[error("No current step to execute")]
    NoCurrentStep,

    #[error("Step execution failed: {0}")]
    StepFailed(String),

    #[error("Condition evaluation failed: {0}")]
    ConditionFailed(String),

    #[error("Compensation failed: {0}")]
    CompensationFailed(String),

    #[error("Flow timed out")]
    Timeout,

    #[error("Flow cancelled")]
    Cancelled,

    #[error("Invalid state transition: {from} -> {to}")]
    InvalidTransition { from: String, to: String },
}

/// Execution status for TemporaryPermissionGrant flow
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TemporaryPermissionGrantFlowStatus {
    /// Flow is pending execution
    Pending,
    /// Flow is currently running
    Running,
    /// Flow is waiting for an event or condition
    Waiting,
    /// Flow completed successfully
    Completed,
    /// Flow failed
    Failed,
    /// Flow was cancelled
    Cancelled,
    /// Flow is compensating (rolling back)
    Compensating,
}

/// Steps in TemporaryPermissionGrant flow
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TemporaryPermissionGrantFlowStep {
    /// validate_duration
    ValidateDuration,
    /// check_duration
    CheckDuration,
    /// log_validation_error
    LogValidationError,
    /// check_duplicates
    CheckDuplicates,
    /// handle_duplicate
    HandleDuplicate,
    /// log_duplicate
    LogDuplicate,
    /// activate_permission
    ActivatePermission,
    /// log_activation_error
    LogActivationError,
    /// log_activation
    LogActivation,
    /// notify_user
    NotifyUser,
    /// invalidate_cache
    InvalidateCache,
    /// await_expiry
    AwaitExpiry,
    /// log_expiry
    LogExpiry,
    /// check_and_expire
    CheckAndExpire,
    /// handle_expiry_check
    HandleExpiryCheck,
    /// auto_expire
    AutoExpire,
    /// log_auto_expiry
    LogAutoExpiry,
    /// log_already_revoked
    LogAlreadyRevoked,
    /// invalidate_cache_after_expiry
    InvalidateCacheAfterExpiry,
    /// notify_expiry
    NotifyExpiry,
    /// complete
    Complete,
    /// workflow_failed
    WorkflowFailed,
}

/// Instance of TemporaryPermissionGrant flow execution
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TemporaryPermissionGrantFlowInstance {
    /// Unique instance ID
    pub id: String,
    /// Current status
    pub status: TemporaryPermissionGrantFlowStatus,
    /// Current step
    pub current_step: Option<TemporaryPermissionGrantFlowStep>,
    /// Flow context (variables)
    pub context: serde_json::Value,
    /// Completed steps
    pub completed_steps: Vec<TemporaryPermissionGrantFlowStep>,
    /// Error if failed
    pub error: Option<String>,
    /// Created timestamp
    pub created_at: chrono::DateTime<chrono::Utc>,
    /// Updated timestamp
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

impl TemporaryPermissionGrantFlowInstance {
    /// Create a new flow instance
    pub fn new(id: impl Into<String>) -> Self {
        let now = chrono::Utc::now();
        Self {
            id: id.into(),
            status: TemporaryPermissionGrantFlowStatus::Pending,
            current_step: None,
            context: serde_json::json!({}),
            completed_steps: Vec::new(),
            error: None,
            created_at: now,
            updated_at: now,
        }
    }

    /// Check if flow is complete
    pub fn is_complete(&self) -> bool {
        matches!(
            self.status,
            TemporaryPermissionGrantFlowStatus::Completed | TemporaryPermissionGrantFlowStatus::Failed | TemporaryPermissionGrantFlowStatus::Cancelled
        )
    }

    /// Check if flow is running
    pub fn is_running(&self) -> bool {
        matches!(
            self.status,
            TemporaryPermissionGrantFlowStatus::Running | TemporaryPermissionGrantFlowStatus::Waiting
        )
    }

    /// Set a context variable
    pub fn set_context(&mut self, key: &str, value: serde_json::Value) {
        if let serde_json::Value::Object(ref mut map) = self.context {
            map.insert(key.to_string(), value);
        }
        self.updated_at = chrono::Utc::now();
    }

    /// Get a context variable
    pub fn get_context(&self, key: &str) -> Option<&serde_json::Value> {
        if let serde_json::Value::Object(ref map) = self.context {
            map.get(key)
        } else {
            None
        }
    }
}

// Phase 1: FlowInstance satisfies backbone_core::flow::WorkflowContext.
// The entity() accessor requires the entity to be carried in the instance;
// add `pub entity: TemporaryPermissionGrant` in the // <<< CUSTOM section and remove the todo!.
#[allow(unused_variables)]
impl WorkflowContext<TemporaryPermissionGrantFlowInstance> for TemporaryPermissionGrantFlowInstance {
    fn entity(&self) -> &TemporaryPermissionGrantFlowInstance { self }
    fn set_var(&mut self, key: &str, value: serde_json::Value) {
        self.set_context(key, value);
    }
    fn get_var(&self, key: &str) -> Option<&serde_json::Value> {
        self.get_context(key)
    }
}

/// Step handler trait for TemporaryPermissionGrant flow
#[async_trait::async_trait]
pub trait TemporaryPermissionGrantStepHandler: Send + Sync {
    /// Handle validate_duration step
    async fn handle_validate_duration(
        &self,
        instance: &mut TemporaryPermissionGrantFlowInstance,
    ) -> Result<Option<TemporaryPermissionGrantFlowStep>, FlowError>;

    /// Evaluate condition for check_duration step
    async fn evaluate_check_duration(
        &self,
        instance: &TemporaryPermissionGrantFlowInstance,
    ) -> Result<TemporaryPermissionGrantFlowStep, FlowError>;

    /// Handle log_validation_error step
    async fn handle_log_validation_error(
        &self,
        instance: &mut TemporaryPermissionGrantFlowInstance,
    ) -> Result<Option<TemporaryPermissionGrantFlowStep>, FlowError>;

    /// Handle check_duplicates step
    async fn handle_check_duplicates(
        &self,
        instance: &mut TemporaryPermissionGrantFlowInstance,
    ) -> Result<Option<TemporaryPermissionGrantFlowStep>, FlowError>;

    /// Evaluate condition for handle_duplicate step
    async fn evaluate_handle_duplicate(
        &self,
        instance: &TemporaryPermissionGrantFlowInstance,
    ) -> Result<TemporaryPermissionGrantFlowStep, FlowError>;

    /// Handle log_duplicate step
    async fn handle_log_duplicate(
        &self,
        instance: &mut TemporaryPermissionGrantFlowInstance,
    ) -> Result<Option<TemporaryPermissionGrantFlowStep>, FlowError>;

    /// Handle activate_permission step
    async fn handle_activate_permission(
        &self,
        instance: &mut TemporaryPermissionGrantFlowInstance,
    ) -> Result<Option<TemporaryPermissionGrantFlowStep>, FlowError>;

    /// Handle log_activation_error step
    async fn handle_log_activation_error(
        &self,
        instance: &mut TemporaryPermissionGrantFlowInstance,
    ) -> Result<Option<TemporaryPermissionGrantFlowStep>, FlowError>;

    /// Handle log_activation step
    async fn handle_log_activation(
        &self,
        instance: &mut TemporaryPermissionGrantFlowInstance,
    ) -> Result<Option<TemporaryPermissionGrantFlowStep>, FlowError>;

    /// Handle notify_user step
    async fn handle_notify_user(
        &self,
        instance: &mut TemporaryPermissionGrantFlowInstance,
    ) -> Result<Option<TemporaryPermissionGrantFlowStep>, FlowError>;

    /// Handle invalidate_cache step
    async fn handle_invalidate_cache(
        &self,
        instance: &mut TemporaryPermissionGrantFlowInstance,
    ) -> Result<Option<TemporaryPermissionGrantFlowStep>, FlowError>;

    /// Handle wait step await_expiry (returns when event received or timeout)
    async fn handle_await_expiry(
        &self,
        instance: &mut TemporaryPermissionGrantFlowInstance,
    ) -> Result<Option<TemporaryPermissionGrantFlowStep>, FlowError>;

    /// Handle log_expiry step
    async fn handle_log_expiry(
        &self,
        instance: &mut TemporaryPermissionGrantFlowInstance,
    ) -> Result<Option<TemporaryPermissionGrantFlowStep>, FlowError>;

    /// Handle check_and_expire step
    async fn handle_check_and_expire(
        &self,
        instance: &mut TemporaryPermissionGrantFlowInstance,
    ) -> Result<Option<TemporaryPermissionGrantFlowStep>, FlowError>;

    /// Evaluate condition for handle_expiry_check step
    async fn evaluate_handle_expiry_check(
        &self,
        instance: &TemporaryPermissionGrantFlowInstance,
    ) -> Result<TemporaryPermissionGrantFlowStep, FlowError>;

    /// Handle auto_expire step
    async fn handle_auto_expire(
        &self,
        instance: &mut TemporaryPermissionGrantFlowInstance,
    ) -> Result<Option<TemporaryPermissionGrantFlowStep>, FlowError>;

    /// Handle log_auto_expiry step
    async fn handle_log_auto_expiry(
        &self,
        instance: &mut TemporaryPermissionGrantFlowInstance,
    ) -> Result<Option<TemporaryPermissionGrantFlowStep>, FlowError>;

    /// Handle log_already_revoked step
    async fn handle_log_already_revoked(
        &self,
        instance: &mut TemporaryPermissionGrantFlowInstance,
    ) -> Result<Option<TemporaryPermissionGrantFlowStep>, FlowError>;

    /// Handle invalidate_cache_after_expiry step
    async fn handle_invalidate_cache_after_expiry(
        &self,
        instance: &mut TemporaryPermissionGrantFlowInstance,
    ) -> Result<Option<TemporaryPermissionGrantFlowStep>, FlowError>;

    /// Handle notify_expiry step
    async fn handle_notify_expiry(
        &self,
        instance: &mut TemporaryPermissionGrantFlowInstance,
    ) -> Result<Option<TemporaryPermissionGrantFlowStep>, FlowError>;

    /// Handle terminal step complete
    async fn handle_complete(
        &self,
        instance: &mut TemporaryPermissionGrantFlowInstance,
    ) -> Result<(), FlowError>;

    /// Handle terminal step workflow_failed
    async fn handle_workflow_failed(
        &self,
        instance: &mut TemporaryPermissionGrantFlowInstance,
    ) -> Result<(), FlowError>;

}

/// Executor for TemporaryPermissionGrant flow
pub struct TemporaryPermissionGrantFlowExecutor<H: TemporaryPermissionGrantStepHandler> {
    handler: Arc<H>,
}

impl<H: TemporaryPermissionGrantStepHandler> TemporaryPermissionGrantFlowExecutor<H> {
    /// Create a new flow executor
    pub fn new(handler: Arc<H>) -> Self {
        Self { handler }
    }

    /// Start a new flow instance
    pub async fn start(&self, instance_id: impl Into<String>) -> Result<TemporaryPermissionGrantFlowInstance, FlowError> {
        let mut instance = TemporaryPermissionGrantFlowInstance::new(instance_id);
        instance.status = TemporaryPermissionGrantFlowStatus::Running;
        instance.current_step = Some(TemporaryPermissionGrantFlowStep::ValidateDuration);
        Ok(instance)
    }

    /// Execute the current step
    pub async fn execute_step(&self, instance: &mut TemporaryPermissionGrantFlowInstance) -> Result<(), FlowError> {
        let current_step = match instance.current_step {
            Some(step) => step,
            None => return Err(FlowError::NoCurrentStep),
        };

        let next_step = match current_step {
            TemporaryPermissionGrantFlowStep::ValidateDuration => {
                self.handler.handle_validate_duration(instance).await?
            }
            TemporaryPermissionGrantFlowStep::CheckDuration => {
                let next = self.handler.evaluate_check_duration(instance).await?;
                Some(next)
            }
            TemporaryPermissionGrantFlowStep::LogValidationError => {
                self.handler.handle_log_validation_error(instance).await?
            }
            TemporaryPermissionGrantFlowStep::CheckDuplicates => {
                self.handler.handle_check_duplicates(instance).await?
            }
            TemporaryPermissionGrantFlowStep::HandleDuplicate => {
                let next = self.handler.evaluate_handle_duplicate(instance).await?;
                Some(next)
            }
            TemporaryPermissionGrantFlowStep::LogDuplicate => {
                self.handler.handle_log_duplicate(instance).await?
            }
            TemporaryPermissionGrantFlowStep::ActivatePermission => {
                self.handler.handle_activate_permission(instance).await?
            }
            TemporaryPermissionGrantFlowStep::LogActivationError => {
                self.handler.handle_log_activation_error(instance).await?
            }
            TemporaryPermissionGrantFlowStep::LogActivation => {
                self.handler.handle_log_activation(instance).await?
            }
            TemporaryPermissionGrantFlowStep::NotifyUser => {
                self.handler.handle_notify_user(instance).await?
            }
            TemporaryPermissionGrantFlowStep::InvalidateCache => {
                self.handler.handle_invalidate_cache(instance).await?
            }
            TemporaryPermissionGrantFlowStep::AwaitExpiry => {
                self.handler.handle_await_expiry(instance).await?
            }
            TemporaryPermissionGrantFlowStep::LogExpiry => {
                self.handler.handle_log_expiry(instance).await?
            }
            TemporaryPermissionGrantFlowStep::CheckAndExpire => {
                self.handler.handle_check_and_expire(instance).await?
            }
            TemporaryPermissionGrantFlowStep::HandleExpiryCheck => {
                let next = self.handler.evaluate_handle_expiry_check(instance).await?;
                Some(next)
            }
            TemporaryPermissionGrantFlowStep::AutoExpire => {
                self.handler.handle_auto_expire(instance).await?
            }
            TemporaryPermissionGrantFlowStep::LogAutoExpiry => {
                self.handler.handle_log_auto_expiry(instance).await?
            }
            TemporaryPermissionGrantFlowStep::LogAlreadyRevoked => {
                self.handler.handle_log_already_revoked(instance).await?
            }
            TemporaryPermissionGrantFlowStep::InvalidateCacheAfterExpiry => {
                self.handler.handle_invalidate_cache_after_expiry(instance).await?
            }
            TemporaryPermissionGrantFlowStep::NotifyExpiry => {
                self.handler.handle_notify_expiry(instance).await?
            }
            TemporaryPermissionGrantFlowStep::Complete => {
                self.handler.handle_complete(instance).await?;
                None // Terminal step
            }
            TemporaryPermissionGrantFlowStep::WorkflowFailed => {
                self.handler.handle_workflow_failed(instance).await?;
                None // Terminal step
            }
        };

        // Mark current step as completed
        instance.completed_steps.push(current_step);

        // Move to next step
        match next_step {
            Some(next) => {
                instance.current_step = Some(next);
            }
            None => {
                instance.current_step = None;
                instance.status = TemporaryPermissionGrantFlowStatus::Completed;
            }
        }

        instance.updated_at = chrono::Utc::now();
        Ok(())
    }

    /// Run the flow to completion
    pub async fn run(&self, instance: &mut TemporaryPermissionGrantFlowInstance) -> Result<(), FlowError> {
        while !instance.is_complete() && instance.status != TemporaryPermissionGrantFlowStatus::Waiting {
            self.execute_step(instance).await?;
        }
        Ok(())
    }

    /// Cancel the flow
    pub fn cancel(&self, instance: &mut TemporaryPermissionGrantFlowInstance) {
        instance.status = TemporaryPermissionGrantFlowStatus::Cancelled;
        instance.updated_at = chrono::Utc::now();
    }

    /// Mark flow as failed
    pub fn fail(&self, instance: &mut TemporaryPermissionGrantFlowInstance, error: impl Into<String>) {
        instance.status = TemporaryPermissionGrantFlowStatus::Failed;
        instance.error = Some(error.into());
        instance.updated_at = chrono::Utc::now();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_flow_instance_creation() {
        let instance = TemporaryPermissionGrantFlowInstance::new("test-1");
        assert_eq!(instance.id, "test-1");
        assert_eq!(instance.status, TemporaryPermissionGrantFlowStatus::Pending);
        assert!(!instance.is_complete());
    }

    #[test]
    fn test_flow_context() {
        let mut instance = TemporaryPermissionGrantFlowInstance::new("test-2");
        instance.set_context("key", serde_json::json!("value"));
        let value = instance.get_context("key");
        assert_eq!(value, Some(&serde_json::json!("value")));
    }

    #[test]
    fn test_flow_status_transitions() {
        let mut instance = TemporaryPermissionGrantFlowInstance::new("test-3");
        assert!(!instance.is_running());

        instance.status = TemporaryPermissionGrantFlowStatus::Running;
        assert!(instance.is_running());
        assert!(!instance.is_complete());

        instance.status = TemporaryPermissionGrantFlowStatus::Completed;
        assert!(instance.is_complete());
        assert!(!instance.is_running());
    }
}
