//! Use case type aliases for AuditLog aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateAuditLogDto, UpdateAuditLogDto};
use crate::application::service::AuditLogService;
use crate::domain::entity::AuditLog;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateAuditLogUseCase = CreateUseCase<AuditLog, CreateAuditLogDto, AuditLogService>;
pub type UpdateAuditLogUseCase = UpdateUseCase<AuditLog, UpdateAuditLogDto, AuditLogService>;
pub type GetAuditLogUseCase    = GetUseCase<AuditLog, AuditLogService>;
pub type DeleteAuditLogUseCase = DeleteUseCase<AuditLog, AuditLogService>;
pub type ListAuditLogUseCase   = ListUseCase<AuditLog, AuditLogService>;

// <<< CUSTOM
// END CUSTOM
