//! Use case type aliases for EffectivePermissionCache aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateEffectivePermissionCacheDto, UpdateEffectivePermissionCacheDto};
use crate::application::service::EffectivePermissionCacheService;
use crate::domain::entity::EffectivePermissionCache;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateEffectivePermissionCacheUseCase = CreateUseCase<EffectivePermissionCache, CreateEffectivePermissionCacheDto, EffectivePermissionCacheService>;
pub type UpdateEffectivePermissionCacheUseCase = UpdateUseCase<EffectivePermissionCache, UpdateEffectivePermissionCacheDto, EffectivePermissionCacheService>;
pub type GetEffectivePermissionCacheUseCase    = GetUseCase<EffectivePermissionCache, EffectivePermissionCacheService>;
pub type DeleteEffectivePermissionCacheUseCase = DeleteUseCase<EffectivePermissionCache, EffectivePermissionCacheService>;
pub type ListEffectivePermissionCacheUseCase   = ListUseCase<EffectivePermissionCache, EffectivePermissionCacheService>;

// <<< CUSTOM
// END CUSTOM
