//! UserOAuthLink REST handlers
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! Uses Axum and backbone-core's BackboneCrudHandler for all 12 CRUD endpoints.

use std::collections::HashMap;
use std::sync::Arc;

use axum::Router;
use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

// Backbone framework imports
use backbone_core::http::{ApiResponse, BackboneCrudHandler};

// Auth integration (optional)
#[cfg(feature = "auth")]
use backbone_auth::{AuthContext, AuthMiddleware};

// Domain imports
use crate::domain::entity::*;
use crate::application::service::{UserOAuthLinkService, ServiceError};

// DTO imports
use crate::presentation::dto::{CreateUserOAuthLinkDto, UpdateUserOAuthLinkDto, PatchUserOAuthLinkDto, UserOAuthLinkResponseDto};

use crate::domain::state_machine::{UserOAuthLinkState, UserOAuthLinkStateMachine, UserOAuthLinkTransition};
use backbone_core::state_machine::StateMachineBehavior;

/// Application error type
#[derive(Debug, thiserror::Error)]
pub enum UserOAuthLinkError {
    #[error("Not found: {0}")]
    NotFound(String),
    #[error("Validation error: {0}")]
    Validation(String),
    #[error("Database error: {0}")]
    Database(String),
    #[error("Internal error: {0}")]
    Internal(String),
    // Domain-specific errors from hook rules
    #[error("User already has an active link with this OAuth provider: {0}")]
    ProviderAlreadyLinked(String),
    #[error("OAuth provider user ID is already linked to another account: {0}")]
    ProviderUserAlreadyLinked(String),
    #[error("Provider user ID is required: {0}")]
    MissingProviderUserId(String),
    #[error("Invalid provider email format: {0}")]
    InvalidProviderEmail(String),
    #[error("User can only have one primary OAuth link: {0}")]
    MultiplePrimaryLinks(String),
    #[error("Cannot disable sync when there are unsynchronized changes: {0}")]
    UnsyncedChangesExist(String),
}

impl From<ServiceError> for UserOAuthLinkError {
    fn from(err: ServiceError) -> Self {
        match err {
            ServiceError::NotFound => Self::NotFound(err.to_string()),
            ServiceError::Validation(ref msg) => Self::Validation(msg.clone()),
            ServiceError::AlreadyExists(ref msg) => Self::Validation(msg.clone()),
            ServiceError::Repository(ref e) => Self::Database(e.to_string()),
            ServiceError::Internal(ref msg) => Self::Internal(msg.clone()),
        }
    }
}

impl axum::response::IntoResponse for UserOAuthLinkError {
    fn into_response(self) -> axum::response::Response {
        use axum::http::StatusCode;
        use axum::Json;

        let (status, code) = match &self {
            Self::NotFound(_) => (StatusCode::NOT_FOUND, "USEROAUTHLINK_NOT_FOUND"),
            Self::Validation(_) => (StatusCode::BAD_REQUEST, "USEROAUTHLINK_VALIDATION_ERROR"),
            Self::Database(_) => (StatusCode::INTERNAL_SERVER_ERROR, "USEROAUTHLINK_DATABASE_ERROR"),
            Self::Internal(_) => (StatusCode::INTERNAL_SERVER_ERROR, "USEROAUTHLINK_INTERNAL_ERROR"),
            Self::ProviderAlreadyLinked(_) => (StatusCode::UNPROCESSABLE_ENTITY, "USEROAUTHLINK_PROVIDER_ALREADY_LINKED"),
            Self::ProviderUserAlreadyLinked(_) => (StatusCode::UNPROCESSABLE_ENTITY, "USEROAUTHLINK_PROVIDER_USER_ALREADY_LINKED"),
            Self::MissingProviderUserId(_) => (StatusCode::UNPROCESSABLE_ENTITY, "USEROAUTHLINK_MISSING_PROVIDER_USER_ID"),
            Self::InvalidProviderEmail(_) => (StatusCode::UNPROCESSABLE_ENTITY, "USEROAUTHLINK_INVALID_PROVIDER_EMAIL"),
            Self::MultiplePrimaryLinks(_) => (StatusCode::UNPROCESSABLE_ENTITY, "USEROAUTHLINK_MULTIPLE_PRIMARY_LINKS"),
            Self::UnsyncedChangesExist(_) => (StatusCode::UNPROCESSABLE_ENTITY, "USEROAUTHLINK_UNSYNCED_CHANGES_EXIST"),
        };

        let body = serde_json::json!({
            "success": false,
            "error": code,
            "message": self.to_string(),
        });

        (status, Json(body)).into_response()
    }
}

/// Domain-specific error codes for UserOAuthLink
pub mod user_o_auth_link_errors {
    pub const PROVIDER_ALREADY_LINKED: &str = "USEROAUTHLINK_PROVIDER_ALREADY_LINKED";
    pub const PROVIDER_USER_ALREADY_LINKED: &str = "USEROAUTHLINK_PROVIDER_USER_ALREADY_LINKED";
    pub const MISSING_PROVIDER_USER_ID: &str = "USEROAUTHLINK_MISSING_PROVIDER_USER_ID";
    pub const INVALID_PROVIDER_EMAIL: &str = "USEROAUTHLINK_INVALID_PROVIDER_EMAIL";
    pub const MULTIPLE_PRIMARY_LINKS: &str = "USEROAUTHLINK_MULTIPLE_PRIMARY_LINKS";
    pub const UNSYNCED_CHANGES_EXIST: &str = "USEROAUTHLINK_UNSYNCED_CHANGES_EXIST";
}

// =============================================================================
// Route Configuration
// =============================================================================

/// Create Axum router with all 16 Backbone endpoints for UserOAuthLink.
///
/// # Routes
///
/// | Method | Path | Description |
/// |--------|------|-------------|
/// | GET | /user_o_auth_links | List with pagination |
/// | POST | /user_o_auth_links | Create new |
/// | GET | /user_o_auth_links/:id | Get by ID |
/// | PUT | /user_o_auth_links/:id | Full update |
/// | PATCH | /user_o_auth_links/:id | Partial update |
/// | DELETE | /user_o_auth_links/:id | Soft delete |
/// | POST | /user_o_auth_links/bulk | Bulk create |
/// | POST | /user_o_auth_links/upsert | Upsert |
/// | GET | /user_o_auth_links/trash | List deleted |
/// | POST | /user_o_auth_links/:id/restore | Restore |
/// | DELETE | /user_o_auth_links/empty | Empty trash |
/// | GET | /user_o_auth_links/:id/deleted | Get deleted by ID |
/// | DELETE | /user_o_auth_links/trash/:id | Permanent delete from trash |
/// | GET | /user_o_auth_links/count | Count active entities |
/// | GET | /user_o_auth_links/trash/count | Count deleted entities |
///
/// # Example
///
/// ```text
/// let service = Arc::new(UserOAuthLinkService::with_repository(repository));
/// let router = create_user_o_auth_link_routes(service);
/// ```
pub fn create_user_o_auth_link_routes(service: Arc<UserOAuthLinkService>) -> Router {
    BackboneCrudHandler::<UserOAuthLinkService, UserOAuthLink, CreateUserOAuthLinkDto, UpdateUserOAuthLinkDto, UserOAuthLinkResponseDto>::routes(
        service,
        "/user_o_auth_links",
    )
}

/// Create authenticated routes with auth middleware.
///
/// Requires the `auth` feature flag. The `AuthMiddleware` implementation
/// is responsible for extracting and validating tokens, then providing
/// an `AuthContext` via request extensions.
#[cfg(feature = "auth")]
pub fn create_protected_user_o_auth_link_routes<A: AuthMiddleware + 'static>(
    service: Arc<UserOAuthLinkService>,
    auth: Arc<A>,
) -> Router {
    use axum::middleware;
    use axum::response::IntoResponse;

    let auth_layer = auth.clone();
    create_user_o_auth_link_routes(service)
        .layer(middleware::from_fn(move |mut req: axum::extract::Request, next: axum::middleware::Next| {
            let auth = auth_layer.clone();
            async move {
                match auth.authenticate(&req).await {
                    Ok(ctx) => {
                        req.extensions_mut().insert(ctx);
                        next.run(req).await
                    }
                    Err(_) => {
                        (axum::http::StatusCode::UNAUTHORIZED,
                         axum::Json(serde_json::json!({
                             "success": false,
                             "error": "unauthorized",
                             "message": "Authentication required"
                         }))
                        ).into_response()
                    }
                }
            }
        }))
}

// =============================================================================
// State Transition Handlers
// =============================================================================

/// Execute unlink transition on a UserOAuthLink.
///
/// POST /user_o_auth_links/:id/transitions/unlink
pub async fn unlink_transition(
    axum::extract::State(service): axum::extract::State<Arc<UserOAuthLinkService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] auth: axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<UserOAuthLinkResponseDto>::not_found("UserOAuthLink", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<UserOAuthLinkResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = UserOAuthLinkTransition::Unlink.allowed_roles();
        let has_specific_perm = auth.has_permission("user_o_auth_link:transition:unlink");
        let has_update_perm = auth.has_permission("user_o_auth_link:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<UserOAuthLinkResponseDto>::error("Insufficient permissions for unlink transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: UserOAuthLinkState = entity.link_status.to_string().parse()
        .unwrap_or(UserOAuthLinkState::default());
    let sm = UserOAuthLinkStateMachine::from_state(current_state);
    if !sm.can_transition(UserOAuthLinkTransition::Unlink) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<UserOAuthLinkResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("link_status".to_string(), serde_json::Value::String("Unlinked".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: UserOAuthLinkResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<UserOAuthLinkResponseDto>::not_found("UserOAuthLink", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<UserOAuthLinkResponseDto>::error(e.to_string()))),
    }
}

/// Execute require_verification transition on a UserOAuthLink.
///
/// POST /user_o_auth_links/:id/transitions/require_verification
pub async fn require_verification_transition(
    axum::extract::State(service): axum::extract::State<Arc<UserOAuthLinkService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] auth: axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<UserOAuthLinkResponseDto>::not_found("UserOAuthLink", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<UserOAuthLinkResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = UserOAuthLinkTransition::RequireVerification.allowed_roles();
        let has_specific_perm = auth.has_permission("user_o_auth_link:transition:require_verification");
        let has_update_perm = auth.has_permission("user_o_auth_link:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<UserOAuthLinkResponseDto>::error("Insufficient permissions for require_verification transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: UserOAuthLinkState = entity.link_status.to_string().parse()
        .unwrap_or(UserOAuthLinkState::default());
    let sm = UserOAuthLinkStateMachine::from_state(current_state);
    if !sm.can_transition(UserOAuthLinkTransition::RequireVerification) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<UserOAuthLinkResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("link_status".to_string(), serde_json::Value::String("RequiresVerification".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: UserOAuthLinkResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<UserOAuthLinkResponseDto>::not_found("UserOAuthLink", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<UserOAuthLinkResponseDto>::error(e.to_string()))),
    }
}

/// Execute verify transition on a UserOAuthLink.
///
/// POST /user_o_auth_links/:id/transitions/verify
pub async fn verify_transition(
    axum::extract::State(service): axum::extract::State<Arc<UserOAuthLinkService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] auth: axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<UserOAuthLinkResponseDto>::not_found("UserOAuthLink", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<UserOAuthLinkResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = UserOAuthLinkTransition::Verify.allowed_roles();
        let has_specific_perm = auth.has_permission("user_o_auth_link:transition:verify");
        let has_update_perm = auth.has_permission("user_o_auth_link:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<UserOAuthLinkResponseDto>::error("Insufficient permissions for verify transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: UserOAuthLinkState = entity.link_status.to_string().parse()
        .unwrap_or(UserOAuthLinkState::default());
    let sm = UserOAuthLinkStateMachine::from_state(current_state);
    if !sm.can_transition(UserOAuthLinkTransition::Verify) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<UserOAuthLinkResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("link_status".to_string(), serde_json::Value::String("Linked".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: UserOAuthLinkResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<UserOAuthLinkResponseDto>::not_found("UserOAuthLink", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<UserOAuthLinkResponseDto>::error(e.to_string()))),
    }
}

/// Execute expire_verification transition on a UserOAuthLink.
///
/// POST /user_o_auth_links/:id/transitions/expire_verification
pub async fn expire_verification_transition(
    axum::extract::State(service): axum::extract::State<Arc<UserOAuthLinkService>>,
    axum::extract::Path(id): axum::extract::Path<String>,
    #[cfg(feature = "auth")] auth: axum::Extension<AuthContext>,
) -> impl axum::response::IntoResponse {
    use axum::{http::StatusCode, Json};

    // Get current entity
    let entity = match service.get_by_id(&id).await {
        Ok(Some(e)) => e,
        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<UserOAuthLinkResponseDto>::not_found("UserOAuthLink", &id))),
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<UserOAuthLinkResponseDto>::error(e.to_string()))),
    };

    // Check permission (if auth enabled)
    #[cfg(feature = "auth")]
    {
        let allowed_roles = UserOAuthLinkTransition::ExpireVerification.allowed_roles();
        let has_specific_perm = auth.has_permission("user_o_auth_link:transition:expire_verification");
        let has_update_perm = auth.has_permission("user_o_auth_link:update");
        if !has_specific_perm && !has_update_perm {
            return (StatusCode::FORBIDDEN, Json(ApiResponse::<UserOAuthLinkResponseDto>::error("Insufficient permissions for expire_verification transition")));
        }
    }

    // Create state machine from entity's actual status and validate transition
    let current_state: UserOAuthLinkState = entity.link_status.to_string().parse()
        .unwrap_or(UserOAuthLinkState::default());
    let sm = UserOAuthLinkStateMachine::from_state(current_state);
    if !sm.can_transition(UserOAuthLinkTransition::ExpireVerification) {
        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<UserOAuthLinkResponseDto>::error("Transition not allowed from current state")));
    }

    // Apply transition via partial update
    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();
    fields.insert("link_status".to_string(), serde_json::Value::String("Unlinked".to_string()));

    match service.partial_update(&id, fields).await {
        Ok(Some(updated)) => {
            let response: UserOAuthLinkResponseDto = updated.into();
            (StatusCode::OK, Json(ApiResponse::ok(response)))
        }
        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<UserOAuthLinkResponseDto>::not_found("UserOAuthLink", &id))),
        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<UserOAuthLinkResponseDto>::error(e.to_string()))),
    }
}

/// Create routes for state transitions.
pub fn create_user_o_auth_link_transition_routes(service: Arc<UserOAuthLinkService>) -> Router {
    use axum::routing::post;

    Router::new()
        .route("/user_o_auth_links/:id/transitions/unlink", post(unlink_transition))
        .route("/user_o_auth_links/:id/transitions/require_verification", post(require_verification_transition))
        .route("/user_o_auth_links/:id/transitions/verify", post(verify_transition))
        .route("/user_o_auth_links/:id/transitions/expire_verification", post(expire_verification_transition))
        .with_state(service)
}

