//! WorkflowStep REST handlers
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! Uses Axum and backbone-core's BackboneCrudHandler for all 12 CRUD endpoints.

use std::collections::HashMap;
use std::sync::Arc;

use axum::Router;
use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

// Backbone framework imports
use backbone_core::http::BackboneCrudHandler;

// Auth integration (optional)
#[cfg(feature = "auth")]
use backbone_auth::{AuthContext, AuthMiddleware};

// Domain imports
use crate::domain::entity::*;
use crate::application::service::{WorkflowStepService, ServiceError};

// DTO imports
use crate::presentation::dto::{CreateWorkflowStepDto, UpdateWorkflowStepDto, PatchWorkflowStepDto, WorkflowStepResponseDto};


/// Application error type
#[derive(Debug, thiserror::Error)]
pub enum WorkflowStepError {
    #[error("Not found: {0}")]
    NotFound(String),
    #[error("Validation error: {0}")]
    Validation(String),
    #[error("Database error: {0}")]
    Database(String),
    #[error("Internal error: {0}")]
    Internal(String),
}

impl From<ServiceError> for WorkflowStepError {
    fn from(err: ServiceError) -> Self {
        match err {
            ServiceError::NotFound => Self::NotFound(err.to_string()),
            ServiceError::Validation(ref msg) => Self::Validation(msg.clone()),
            ServiceError::AlreadyExists(ref msg) => Self::Validation(msg.clone()),
            ServiceError::Repository(ref e) => Self::Database(e.to_string()),
            ServiceError::Internal(ref msg) => Self::Internal(msg.clone()),
        }
    }
}

impl axum::response::IntoResponse for WorkflowStepError {
    fn into_response(self) -> axum::response::Response {
        use axum::http::StatusCode;
        use axum::Json;

        let (status, code) = match &self {
            Self::NotFound(_) => (StatusCode::NOT_FOUND, "WORKFLOWSTEP_NOT_FOUND"),
            Self::Validation(_) => (StatusCode::BAD_REQUEST, "WORKFLOWSTEP_VALIDATION_ERROR"),
            Self::Database(_) => (StatusCode::INTERNAL_SERVER_ERROR, "WORKFLOWSTEP_DATABASE_ERROR"),
            Self::Internal(_) => (StatusCode::INTERNAL_SERVER_ERROR, "WORKFLOWSTEP_INTERNAL_ERROR"),
        };

        let body = serde_json::json!({
            "success": false,
            "error": code,
            "message": self.to_string(),
        });

        (status, Json(body)).into_response()
    }
}

// =============================================================================
// Route Configuration
// =============================================================================

/// Create Axum router with all 16 Backbone endpoints for WorkflowStep.
///
/// # Routes
///
/// | Method | Path | Description |
/// |--------|------|-------------|
/// | GET | /workflow_steps | List with pagination |
/// | POST | /workflow_steps | Create new |
/// | GET | /workflow_steps/:id | Get by ID |
/// | PUT | /workflow_steps/:id | Full update |
/// | PATCH | /workflow_steps/:id | Partial update |
/// | DELETE | /workflow_steps/:id | Soft delete |
/// | POST | /workflow_steps/bulk | Bulk create |
/// | POST | /workflow_steps/upsert | Upsert |
/// | GET | /workflow_steps/trash | List deleted |
/// | POST | /workflow_steps/:id/restore | Restore |
/// | DELETE | /workflow_steps/empty | Empty trash |
/// | GET | /workflow_steps/:id/deleted | Get deleted by ID |
/// | DELETE | /workflow_steps/trash/:id | Permanent delete from trash |
/// | GET | /workflow_steps/count | Count active entities |
/// | GET | /workflow_steps/trash/count | Count deleted entities |
///
/// # Example
///
/// ```text
/// let service = Arc::new(WorkflowStepService::with_repository(repository));
/// let router = create_workflow_step_routes(service);
/// ```
pub fn create_workflow_step_routes(service: Arc<WorkflowStepService>) -> Router {
    BackboneCrudHandler::<WorkflowStepService, WorkflowStep, CreateWorkflowStepDto, UpdateWorkflowStepDto, WorkflowStepResponseDto>::routes(
        service,
        "/workflow_steps",
    )
}

/// Create authenticated routes with auth middleware.
///
/// Requires the `auth` feature flag. The `AuthMiddleware` implementation
/// is responsible for extracting and validating tokens, then providing
/// an `AuthContext` via request extensions.
#[cfg(feature = "auth")]
pub fn create_protected_workflow_step_routes<A: AuthMiddleware + 'static>(
    service: Arc<WorkflowStepService>,
    auth: Arc<A>,
) -> Router {
    use axum::middleware;
    use axum::response::IntoResponse;

    let auth_layer = auth.clone();
    create_workflow_step_routes(service)
        .layer(middleware::from_fn(move |mut req: axum::extract::Request, next: axum::middleware::Next| {
            let auth = auth_layer.clone();
            async move {
                match auth.authenticate(&req).await {
                    Ok(ctx) => {
                        req.extensions_mut().insert(ctx);
                        next.run(req).await
                    }
                    Err(_) => {
                        (axum::http::StatusCode::UNAUTHORIZED,
                         axum::Json(serde_json::json!({
                             "success": false,
                             "error": "unauthorized",
                             "message": "Authentication required"
                         }))
                        ).into_response()
                    }
                }
            }
        }))
}

